/** Interface copy only. Never translate or mutate sealed evidence with this module. */
export const displayLanguages = ['ar','en','bn','hi','ur','id','es','fr','de'] as const;
export type DisplayLanguage = typeof displayLanguages[number];
export type ClaimInputLanguage = DisplayLanguage;
const existingCopy = {
  ar: { subtitle: 'الدليل أولاً، ثم التفسير.', nav: 'كيف تعمل العدسة', eyebrow: 'مساحة هادئة لفحص الادعاءات', title: 'من القول،', title2: 'إلى دليل يمكن تتبّعه.', intro: 'اكتب ادعاءً بالعربية أو الإنجليزية. ابحث عن النص المرتبط به، وافحص سلامة الاقتباس، وافهم ما يدعمه الدليل — وما لا يحسمه.', inputTitle: 'ما القول الذي تريد فحصه؟', inputHint: 'ابدأ بعبارة واحدة واضحة. النتيجة تخص المصادر المتاحة هنا فقط.', placeholder: 'مثال: يذكر القرآن أن كل شيء حي جُعل من الماء.', submit: 'افحص الدليل', loading: 'جارٍ فحص المصادر…', presets: 'جرّب سؤالاً', examples: ['يذكر القرآن أن كل شيء حي جُعل من الماء.', 'يذكر القرآن أن الحياة لا ترتبط بالماء.', 'هناك حكم قرآني صريح عن تطبيق هاتف معيّن.'], scope: 'نطاق المصادر', available: 'مصدر جاهز للبحث', unavailable: 'المصادر قيد التجهيز', inferenceReady: 'التقييم الدلالي متاح', inferenceUnavailable: 'التقييم الدلالي غير متاح حالياً', coverageNote: 'تُعرض التغطية الفعلية؛ لا ندّعي البحث في جميع المصادر الإسلامية.', first: 'العثور على النص', firstNote: 'داخل المصادر المقبولة فقط', second: 'فحص الاقتباس', secondNote: 'النص والموضع والإصدار', third: 'قراءة العلاقة', thirdNote: 'تقييم دلالي بحدود واضحة', result: 'سجل الفحص', evidence: 'النصوص المسترجعة', noEvidence: 'لم تُسترجع نصوص لهذا الادعاء. لا يعني ذلك أن الادعاء صحيح أو خاطئ.', integrityPass: 'سلامة الاقتباس: اجتاز الفحص', integrityFail: 'سلامة الاقتباس: لم يجتز الفحص', source: 'افتح المصدر', details: 'الموضع وتفاصيل الفحص', limitations: 'حدود هذه النتيجة', notFatwa: 'هذه أداة لتتبّع الأدلة، وليست فتوى أو تصحيحاً مستقلاً للأحاديث.', emptyTitle: 'دع الدليل يأخذ مكانه.', emptyNote: 'تظهر هنا النتيجة والنص الأصلي وموضعه بعد الفحص. لا توجد نتائج معدّة مسبقاً.', error: 'تعذّر إكمال الفحص. حاول مرة أخرى.', langs: 'لغات العرض', beta: 'قريباً · يتطلب مراجعة لغوية', record: 'معرّف السجل', seal: 'بصمة السجل', relationship: 'العلاقة الدلالية', human: 'المراجعة العلمية', technical: 'التحقق التقني', translation: 'المراجعة اللغوية', supported: 'يدعمه المصدر المحدد', conflicting: 'يتعارض مع المصدر المحدد', insufficient: 'الدليل المتاح غير كافٍ', notEvaluated: 'لم يُجرَ التقييم الدلالي', disclaimer: 'العثور على اقتباس سليم لا يثبت وحده صحة تفسير الادعاء.' },
  en: { subtitle: 'Evidence first. Interpretation second.', nav: 'How the lens works', eyebrow: 'A quiet desk for examining claims', title: 'From a claim,', title2: 'to a source you can trace.', intro: 'Write a claim in Arabic or English. Find the related text, check the quotation, and understand what the evidence supports — and what it leaves unresolved.', inputTitle: 'What would you like to examine?', inputHint: 'Start with one clear statement. Results apply only to the sources available here.', placeholder: 'Example: The Quran says every living thing was made from water.', submit: 'Examine the evidence', loading: 'Checking the sources…', presets: 'Try a claim', examples: ['The Quran says every living thing was made from water.', 'The Quran says life has no connection to water.', 'The Quran gives an explicit ruling about a particular mobile app.'], scope: 'Source coverage', available: 'Source ready to search', unavailable: 'Sources being prepared', inferenceReady: 'Semantic assessment available', inferenceUnavailable: 'Semantic assessment currently unavailable', coverageNote: 'Actual coverage is shown. We do not claim to search every Islamic source.', first: 'Find the text', firstNote: 'Within admitted sources only', second: 'Check the quotation', secondNote: 'Text, location and edition', third: 'Examine the relationship', thirdNote: 'A bounded semantic assessment', result: 'Examination record', evidence: 'Retrieved passages', noEvidence: 'No passages were retrieved for this claim. This does not establish that the claim is true or false.', integrityPass: 'Quotation integrity: passed', integrityFail: 'Quotation integrity: failed', source: 'Open source', details: 'Location and verification details', limitations: 'Limits of this result', notFatwa: 'A tool for tracing evidence, not a fatwa or independent hadith authentication.', emptyTitle: 'Let the evidence take its place.', emptyNote: 'Your result, the original text and its location appear here after examination. No prewritten results.', error: 'The examination could not be completed. Please try again.', langs: 'Display languages', beta: 'Coming later · linguistic review required', record: 'Record ID', seal: 'Record fingerprint', relationship: 'Semantic relationship', human: 'Scholarly review', technical: 'Technical verification', translation: 'Linguistic review', supported: 'Supported within the selected corpus', conflicting: 'Conflicting within the selected corpus', insufficient: 'Available evidence is insufficient', notEvaluated: 'Semantic assessment not performed', disclaimer: 'A verified quotation alone does not establish a correct interpretation of the claim.' }
};
export type DisplayCopy = { [K in keyof typeof existingCopy.en]: K extends 'examples' ? string[] : string };
const bn: DisplayCopy = {
 subtitle:'আগে প্রমাণ, তারপর ব্যাখ্যা।',nav:'লেন্স কীভাবে কাজ করে',eyebrow:'দাবি পরীক্ষা করার শান্ত পরিসর',title:'একটি দাবি থেকে,',title2:'যাচাইযোগ্য উৎসের দিকে।',intro:'আরবি বা ইংরেজিতে একটি দাবি লিখুন। সংশ্লিষ্ট পাঠ খুঁজুন, উদ্ধৃতির যথার্থতা পরীক্ষা করুন এবং প্রমাণ কী সমর্থন করে আর কী অমীমাংসিত রাখে তা বুঝুন।',inputTitle:'কোন দাবিটি পরীক্ষা করতে চান?',inputHint:'একটি স্পষ্ট বক্তব্য দিয়ে শুরু করুন। ফলাফল কেবল এখানে উপলব্ধ উৎসগুলোর জন্য প্রযোজ্য।',placeholder:'দাবি আরবি বা ইংরেজিতে লিখুন।',submit:'প্রমাণ পরীক্ষা করুন',loading:'উৎস পরীক্ষা করা হচ্ছে…',presets:'একটি দাবি চেষ্টা করুন',examples:existingCopy.en.examples,scope:'উৎসের পরিধি',available:'উৎস অনুসন্ধানের জন্য প্রস্তুত',unavailable:'উৎস প্রস্তুত করা হচ্ছে',inferenceReady:'অর্থগত মূল্যায়ন উপলব্ধ',inferenceUnavailable:'অর্থগত মূল্যায়ন এখন উপলব্ধ নয়',coverageNote:'প্রকৃত পরিধি দেখানো হয়। আমরা সব ইসলামি উৎস অনুসন্ধানের দাবি করি না।',first:'পাঠ খুঁজুন',firstNote:'কেবল গৃহীত উৎসে',second:'উদ্ধৃতি পরীক্ষা করুন',secondNote:'পাঠ, অবস্থান ও সংস্করণ',third:'সম্পর্ক পরীক্ষা করুন',thirdNote:'স্পষ্ট সীমাসহ অর্থগত মূল্যায়ন',result:'পরীক্ষার রেকর্ড',evidence:'উদ্ধার করা পাঠ',noEvidence:'এই দাবির জন্য কোনো পাঠ উদ্ধার হয়নি। এতে দাবিটি সত্য বা মিথ্যা প্রমাণিত হয় না।',integrityPass:'উদ্ধৃতির যথার্থতা: পরীক্ষায় উত্তীর্ণ',integrityFail:'উদ্ধৃতির যথার্থতা: পরীক্ষায় ব্যর্থ',source:'উৎস খুলুন',details:'অবস্থান ও পরীক্ষার বিস্তারিত',limitations:'ফলাফলের সীমাবদ্ধতা',notFatwa:'এটি প্রমাণ অনুসরণের উপকরণ; ফতোয়া বা স্বতন্ত্র হাদিস প্রমাণীকরণ নয়।',emptyTitle:'প্রমাণকে সামনে আসতে দিন।',emptyNote:'পরীক্ষার পরে ফলাফল, মূল পাঠ ও তার অবস্থান এখানে দেখা যাবে। আগে থেকে লেখা ফলাফল নেই।',error:'পরীক্ষা সম্পন্ন করা যায়নি। আবার চেষ্টা করুন।',langs:'প্রদর্শনের ভাষা',beta:'খসড়া · স্বতন্ত্র ভাষাগত পর্যালোচনা হয়নি',record:'রেকর্ড পরিচিতি',seal:'রেকর্ডের ফিঙ্গারপ্রিন্ট',relationship:'অর্থগত সম্পর্ক',human:'বিশেষজ্ঞ পর্যালোচনা',technical:'প্রযুক্তিগত যাচাই',translation:'ভাষাগত পর্যালোচনা',supported:'নির্বাচিত উৎসসমষ্টির মধ্যে সমর্থিত',conflicting:'নির্বাচিত উৎসসমষ্টির সঙ্গে সাংঘর্ষিক',insufficient:'উপলব্ধ প্রমাণ অপর্যাপ্ত',notEvaluated:'অর্থগত মূল্যায়ন করা হয়নি',disclaimer:'সঠিক উদ্ধৃতি পাওয়া মাত্রই দাবির ব্যাখ্যা সঠিক প্রমাণিত হয় না।'
};
const hi: DisplayCopy = {
 subtitle:'पहले प्रमाण, फिर व्याख्या।',nav:'लेंस कैसे काम करता है',eyebrow:'दावों की जाँच के लिए शांत स्थान',title:'एक दावे से,',title2:'ऐसे स्रोत तक जिसे जाँचा जा सके।',intro:'अरबी या अंग्रेज़ी में दावा लिखें। संबंधित पाठ खोजें, उद्धरण की शुद्धता जाँचें और समझें कि प्रमाण क्या समर्थित करता है और क्या अनिर्णीत छोड़ता है।',inputTitle:'आप किस दावे की जाँच करना चाहते हैं?',inputHint:'एक स्पष्ट कथन से शुरू करें। परिणाम केवल यहाँ उपलब्ध स्रोतों पर लागू हैं।',placeholder:'दावा अरबी या अंग्रेज़ी में लिखें।',submit:'प्रमाण की जाँच करें',loading:'स्रोतों की जाँच हो रही है…',presets:'एक दावा आज़माएँ',examples:existingCopy.en.examples,scope:'स्रोतों का दायरा',available:'स्रोत खोज के लिए तैयार',unavailable:'स्रोत तैयार किए जा रहे हैं',inferenceReady:'अर्थगत मूल्यांकन उपलब्ध',inferenceUnavailable:'अर्थगत मूल्यांकन अभी उपलब्ध नहीं',coverageNote:'वास्तविक दायरा दिखाया जाता है। हम सभी इस्लामी स्रोतों में खोज करने का दावा नहीं करते।',first:'पाठ खोजें',firstNote:'केवल स्वीकृत स्रोतों में',second:'उद्धरण जाँचें',secondNote:'पाठ, स्थान और संस्करण',third:'संबंध की जाँच करें',thirdNote:'स्पष्ट सीमाओं के साथ अर्थगत मूल्यांकन',result:'जाँच का रिकॉर्ड',evidence:'प्राप्त पाठ',noEvidence:'इस दावे के लिए कोई पाठ नहीं मिला। इससे दावा सही या गलत सिद्ध नहीं होता।',integrityPass:'उद्धरण की शुद्धता: जाँच सफल',integrityFail:'उद्धरण की शुद्धता: जाँच असफल',source:'स्रोत खोलें',details:'स्थान और जाँच का विवरण',limitations:'इस परिणाम की सीमाएँ',notFatwa:'यह प्रमाण तक पहुँचने का साधन है; फ़तवा या स्वतंत्र हदीस प्रमाणीकरण नहीं।',emptyTitle:'प्रमाण को सामने आने दें।',emptyNote:'जाँच के बाद परिणाम, मूल पाठ और उसका स्थान यहाँ दिखेंगे। पहले से तैयार परिणाम नहीं हैं।',error:'जाँच पूरी नहीं हो सकी। फिर प्रयास करें।',langs:'प्रदर्शन की भाषाएँ',beta:'मसौदा · स्वतंत्र भाषाई समीक्षा नहीं हुई',record:'रिकॉर्ड पहचान',seal:'रिकॉर्ड की पहचान-छाप',relationship:'अर्थगत संबंध',human:'विशेषज्ञ समीक्षा',technical:'तकनीकी सत्यापन',translation:'भाषाई समीक्षा',supported:'चयनित स्रोत-संग्रह में समर्थित',conflicting:'चयनित स्रोत-संग्रह से विरोध',insufficient:'उपलब्ध प्रमाण अपर्याप्त',notEvaluated:'अर्थगत मूल्यांकन नहीं हुआ',disclaimer:'सही उद्धरण मिलना अपने आप दावे की व्याख्या को सही सिद्ध नहीं करता।'
};
const ur: DisplayCopy = {
 subtitle:'پہلے دلیل، پھر تشریح۔',nav:'عدسہ کیسے کام کرتا ہے',eyebrow:'دعووں کی جانچ کے لیے پُرسکون جگہ',title:'ایک دعوے سے،',title2:'قابلِ سراغ ماخذ تک۔',intro:'عربی یا انگریزی میں دعویٰ لکھیں۔ متعلقہ متن تلاش کریں، اقتباس کی صحت جانچیں، اور سمجھیں کہ دلیل کس بات کی تائید کرتی ہے اور کیا غیر طے شدہ رہتا ہے۔',inputTitle:'آپ کس دعوے کی جانچ کرنا چاہتے ہیں؟',inputHint:'ایک واضح بیان سے آغاز کریں۔ نتائج صرف یہاں دستیاب ماخذوں پر لاگو ہوتے ہیں۔',placeholder:'دعویٰ عربی یا انگریزی میں لکھیں۔',submit:'دلیل کی جانچ کریں',loading:'ماخذوں کی جانچ جاری ہے…',presets:'ایک دعویٰ آزمائیں',examples:existingCopy.en.examples,scope:'ماخذوں کا دائرہ',available:'ماخذ تلاش کے لیے تیار ہے',unavailable:'ماخذ تیار کیے جا رہے ہیں',inferenceReady:'معنوی جائزہ دستیاب ہے',inferenceUnavailable:'معنوی جائزہ فی الحال دستیاب نہیں',coverageNote:'اصل دائرۂ کار دکھایا جاتا ہے۔ ہم تمام اسلامی ماخذوں میں تلاش کا دعویٰ نہیں کرتے۔',first:'متن تلاش کریں',firstNote:'صرف قبول شدہ ماخذوں میں',second:'اقتباس کی جانچ کریں',secondNote:'متن، مقام اور نسخہ',third:'تعلق کا جائزہ لیں',thirdNote:'واضح حدود کے ساتھ معنوی جائزہ',result:'جانچ کا ریکارڈ',evidence:'حاصل شدہ متون',noEvidence:'اس دعوے کے لیے کوئی متن حاصل نہیں ہوا۔ اس سے دعویٰ درست یا غلط ثابت نہیں ہوتا۔',integrityPass:'اقتباس کی صحت: جانچ کامیاب',integrityFail:'اقتباس کی صحت: جانچ ناکام',source:'ماخذ کھولیں',details:'مقام اور جانچ کی تفصیلات',limitations:'اس نتیجے کی حدود',notFatwa:'یہ دلائل تک رسائی کا آلہ ہے؛ فتویٰ یا حدیث کی آزادانہ تصحیح نہیں۔',emptyTitle:'دلیل کو سامنے آنے دیں۔',emptyNote:'جانچ کے بعد نتیجہ، اصل متن اور اس کا مقام یہاں دکھائے جائیں گے۔ پہلے سے تیار نتائج نہیں ہیں۔',error:'جانچ مکمل نہیں ہو سکی۔ دوبارہ کوشش کریں۔',langs:'نمایش کی زبانیں',beta:'مسودہ · آزادانہ لسانی نظرثانی نہیں ہوئی',record:'ریکارڈ کی شناخت',seal:'ریکارڈ کا نشان',relationship:'معنوی تعلق',human:'علمی نظرثانی',technical:'تکنیکی تصدیق',translation:'لسانی نظرثانی',supported:'منتخب ماخذوں کے اندر تائید حاصل ہے',conflicting:'منتخب ماخذوں سے متعارض ہے',insufficient:'دستیاب دلیل ناکافی ہے',notEvaluated:'معنوی جائزہ نہیں لیا گیا',disclaimer:'درست اقتباس ملنا بذاتِ خود دعوے کی تشریح کو درست ثابت نہیں کرتا۔'
};
const id: DisplayCopy = {
 subtitle:'Bukti dahulu. Penafsiran kemudian.',nav:'Cara kerja lensa',eyebrow:'Ruang tenang untuk memeriksa klaim',title:'Dari sebuah klaim,',title2:'menuju sumber yang dapat ditelusuri.',intro:'Tulis klaim dalam bahasa Arab atau Inggris. Temukan teks terkait, periksa keutuhan kutipan, dan pahami apa yang didukung bukti serta apa yang belum terjawab.',inputTitle:'Klaim apa yang ingin Anda periksa?',inputHint:'Mulai dengan satu pernyataan jelas. Hasil hanya berlaku untuk sumber yang tersedia di sini.',placeholder:'Tulis klaim dalam bahasa Arab atau Inggris.',submit:'Periksa bukti',loading:'Memeriksa sumber…',presets:'Coba sebuah klaim',examples:existingCopy.en.examples,scope:'Cakupan sumber',available:'Sumber siap ditelusuri',unavailable:'Sumber sedang disiapkan',inferenceReady:'Penilaian makna tersedia',inferenceUnavailable:'Penilaian makna belum tersedia',coverageNote:'Cakupan sebenarnya ditampilkan. Kami tidak mengklaim menelusuri seluruh sumber Islam.',first:'Temukan teks',firstNote:'Hanya dalam sumber yang diterima',second:'Periksa kutipan',secondNote:'Teks, lokasi, dan edisi',third:'Periksa hubungan',thirdNote:'Penilaian makna dengan batas yang jelas',result:'Catatan pemeriksaan',evidence:'Teks yang ditemukan',noEvidence:'Tidak ada teks yang ditemukan untuk klaim ini. Ini tidak membuktikan bahwa klaim benar atau salah.',integrityPass:'Keutuhan kutipan: lolos pemeriksaan',integrityFail:'Keutuhan kutipan: gagal pemeriksaan',source:'Buka sumber',details:'Lokasi dan rincian pemeriksaan',limitations:'Batas hasil ini',notFatwa:'Alat untuk menelusuri bukti, bukan fatwa atau autentikasi hadis secara mandiri.',emptyTitle:'Biarkan bukti tampil.',emptyNote:'Hasil, teks asli, dan lokasinya tampil setelah pemeriksaan. Tidak ada hasil yang sudah disiapkan.',error:'Pemeriksaan tidak dapat diselesaikan. Silakan coba lagi.',langs:'Bahasa tampilan',beta:'Draf · belum ditinjau secara linguistik oleh pihak independen',record:'ID catatan',seal:'Sidik catatan',relationship:'Hubungan makna',human:'Tinjauan keilmuan',technical:'Verifikasi teknis',translation:'Tinjauan linguistik',supported:'Didukung dalam kumpulan sumber terpilih',conflicting:'Bertentangan dengan kumpulan sumber terpilih',insufficient:'Bukti yang tersedia tidak cukup',notEvaluated:'Penilaian makna belum dilakukan',disclaimer:'Kutipan yang terverifikasi saja tidak membuktikan bahwa penafsiran klaim benar.'
};

const es: DisplayCopy = {
 subtitle:'Primero la evidencia. Después, la interpretación.',nav:'Cómo funciona la lente',eyebrow:'Un espacio tranquilo para examinar afirmaciones',title:'De una afirmación,',title2:'a una fuente rastreable.',intro:'Escribe una afirmación en árabe o inglés. Busca el texto relacionado, comprueba la cita y entiende qué respalda la evidencia y qué queda sin resolver.',inputTitle:'¿Qué afirmación quieres examinar?',inputHint:'Empieza con una afirmación clara. Los resultados se limitan a las fuentes disponibles aquí.',placeholder:'Escribe la afirmación en árabe o inglés.',submit:'Examinar la evidencia',loading:'Comprobando las fuentes…',presets:'Prueba una afirmación',examples:existingCopy.en.examples,scope:'Cobertura de fuentes',available:'Fuente lista para buscar',unavailable:'Fuentes en preparación',inferenceReady:'Evaluación semántica disponible',inferenceUnavailable:'Evaluación semántica no disponible actualmente',coverageNote:'Se muestra la cobertura real. No afirmamos buscar en todas las fuentes islámicas.',first:'Encontrar el texto',firstNote:'Solo en fuentes admitidas',second:'Comprobar la cita',secondNote:'Texto, ubicación y edición',third:'Examinar la relación',thirdNote:'Evaluación semántica con límites claros',result:'Registro del examen',evidence:'Pasajes recuperados',noEvidence:'No se recuperaron pasajes para esta afirmación. Esto no demuestra que sea verdadera o falsa.',integrityPass:'Integridad de la cita: comprobación superada',integrityFail:'Integridad de la cita: comprobación fallida',source:'Abrir fuente',details:'Ubicación y detalles de verificación',limitations:'Límites de este resultado',notFatwa:'Una herramienta para rastrear evidencia; no una fetua ni una autenticación independiente de hadices.',emptyTitle:'Deja que aparezca la evidencia.',emptyNote:'El resultado, el texto original y su ubicación aparecerán después del examen. No hay resultados preparados.',error:'No se pudo completar el examen. Inténtalo de nuevo.',langs:'Idiomas de visualización',beta:'Borrador · sin revisión lingüística independiente',record:'ID del registro',seal:'Huella del registro',relationship:'Relación semántica',human:'Revisión especializada',technical:'Verificación técnica',translation:'Revisión lingüística',supported:'Respaldado dentro del corpus seleccionado',conflicting:'En conflicto con el corpus seleccionado',insufficient:'La evidencia disponible es insuficiente',notEvaluated:'Evaluación semántica no realizada',disclaimer:'Una cita verificada no demuestra por sí sola una interpretación correcta de la afirmación.'
};
const fr: DisplayCopy = {
 subtitle:'Les preuves d’abord. L’interprétation ensuite.',nav:'Comment fonctionne la loupe',eyebrow:'Un espace calme pour examiner les affirmations',title:'D’une affirmation,',title2:'à une source que l’on peut retrouver.',intro:'Écrivez une affirmation en arabe ou en anglais. Retrouvez le texte associé, vérifiez la citation et comprenez ce que les preuves étayent et ce qui reste indéterminé.',inputTitle:'Quelle affirmation voulez-vous examiner ?',inputHint:'Commencez par une affirmation claire. Les résultats se limitent aux sources disponibles ici.',placeholder:'Écrivez l’affirmation en arabe ou en anglais.',submit:'Examiner les preuves',loading:'Vérification des sources…',presets:'Essayer une affirmation',examples:existingCopy.en.examples,scope:'Couverture des sources',available:'Source prête à être recherchée',unavailable:'Sources en préparation',inferenceReady:'Évaluation sémantique disponible',inferenceUnavailable:'Évaluation sémantique actuellement indisponible',coverageNote:'La couverture réelle est affichée. Nous ne prétendons pas rechercher dans toutes les sources islamiques.',first:'Retrouver le texte',firstNote:'Uniquement dans les sources admises',second:'Vérifier la citation',secondNote:'Texte, emplacement et édition',third:'Examiner le lien',thirdNote:'Évaluation sémantique aux limites explicites',result:'Dossier d’examen',evidence:'Passages retrouvés',noEvidence:'Aucun passage n’a été retrouvé pour cette affirmation. Cela ne prouve pas qu’elle est vraie ou fausse.',integrityPass:'Intégrité de la citation : vérification réussie',integrityFail:'Intégrité de la citation : vérification échouée',source:'Ouvrir la source',details:'Emplacement et détails de vérification',limitations:'Limites de ce résultat',notFatwa:'Un outil pour retrouver les preuves, pas une fatwa ni une authentification indépendante des hadiths.',emptyTitle:'Laissez les preuves apparaître.',emptyNote:'Le résultat, le texte original et son emplacement apparaîtront après l’examen. Aucun résultat préétabli.',error:'L’examen n’a pas pu être terminé. Réessayez.',langs:'Langues d’affichage',beta:'Brouillon · sans révision linguistique indépendante',record:'Identifiant du dossier',seal:'Empreinte du dossier',relationship:'Lien sémantique',human:'Révision spécialisée',technical:'Vérification technique',translation:'Révision linguistique',supported:'Étayé dans le corpus sélectionné',conflicting:'En contradiction avec le corpus sélectionné',insufficient:'Les preuves disponibles sont insuffisantes',notEvaluated:'Évaluation sémantique non effectuée',disclaimer:'Une citation vérifiée ne suffit pas à établir que l’interprétation de l’affirmation est correcte.'
};
const de: DisplayCopy = {
 subtitle:'Erst der Beleg. Dann die Auslegung.',nav:'So funktioniert die Linse',eyebrow:'Ein ruhiger Ort zur Prüfung von Aussagen',title:'Von einer Aussage,',title2:'zu einer nachvollziehbaren Quelle.',intro:'Schreiben Sie eine Aussage auf Arabisch oder Englisch. Finden Sie den zugehörigen Text, prüfen Sie das Zitat und verstehen Sie, was der Beleg stützt und was offenbleibt.',inputTitle:'Welche Aussage möchten Sie prüfen?',inputHint:'Beginnen Sie mit einer klaren Aussage. Ergebnisse gelten nur für die hier verfügbaren Quellen.',placeholder:'Schreiben Sie die Aussage auf Arabisch oder Englisch.',submit:'Belege prüfen',loading:'Quellen werden geprüft…',presets:'Eine Aussage ausprobieren',examples:existingCopy.en.examples,scope:'Quellenabdeckung',available:'Quelle zur Suche bereit',unavailable:'Quellen werden vorbereitet',inferenceReady:'Semantische Bewertung verfügbar',inferenceUnavailable:'Semantische Bewertung derzeit nicht verfügbar',coverageNote:'Die tatsächliche Abdeckung wird angezeigt. Wir behaupten nicht, alle islamischen Quellen zu durchsuchen.',first:'Text finden',firstNote:'Nur in zugelassenen Quellen',second:'Zitat prüfen',secondNote:'Text, Fundstelle und Ausgabe',third:'Zusammenhang prüfen',thirdNote:'Semantische Bewertung mit klaren Grenzen',result:'Prüfprotokoll',evidence:'Gefundene Textstellen',noEvidence:'Für diese Aussage wurden keine Textstellen gefunden. Dies beweist nicht, dass die Aussage wahr oder falsch ist.',integrityPass:'Zitatintegrität: Prüfung bestanden',integrityFail:'Zitatintegrität: Prüfung fehlgeschlagen',source:'Quelle öffnen',details:'Fundstelle und Prüfdetails',limitations:'Grenzen dieses Ergebnisses',notFatwa:'Ein Werkzeug zum Nachverfolgen von Belegen, keine Fatwa oder unabhängige Hadith-Authentifizierung.',emptyTitle:'Lassen Sie die Belege sichtbar werden.',emptyNote:'Nach der Prüfung erscheinen hier das Ergebnis, der Originaltext und seine Fundstelle. Keine vorgefertigten Ergebnisse.',error:'Die Prüfung konnte nicht abgeschlossen werden. Versuchen Sie es erneut.',langs:'Anzeigesprachen',beta:'Entwurf · nicht unabhängig sprachlich geprüft',record:'Protokoll-ID',seal:'Fingerabdruck des Protokolls',relationship:'Semantischer Zusammenhang',human:'Fachliche Prüfung',technical:'Technische Verifikation',translation:'Sprachliche Prüfung',supported:'Innerhalb des ausgewählten Korpus gestützt',conflicting:'Im Widerspruch zum ausgewählten Korpus',insufficient:'Die verfügbaren Belege reichen nicht aus',notEvaluated:'Semantische Bewertung nicht durchgeführt',disclaimer:'Ein verifiziertes Zitat allein beweist keine korrekte Auslegung der Aussage.'
};
const interfaceCopy: Readonly<Record<DisplayLanguage, DisplayCopy>> = {
 ar: {...existingCopy.ar, beta:'مسودة عرض · لم تُراجع لغوياً بشكل مستقل'},
 en: {...existingCopy.en, beta:'Display draft · not independently linguistically reviewed'}, bn,hi,ur,id,es,fr,de
};
export const displayLanguageMetadata = {
 ar:{nativeName:'العربية',direction:'rtl',reviewStatus:'not_independently_reviewed',draft:true,claimInputSupported:true},
 en:{nativeName:'English',direction:'ltr',reviewStatus:'not_independently_reviewed',draft:true,claimInputSupported:true},
 bn:{nativeName:'বাংলা',direction:'ltr',reviewStatus:'not_independently_reviewed',draft:true,claimInputSupported:true},
 hi:{nativeName:'हिन्दी',direction:'ltr',reviewStatus:'not_independently_reviewed',draft:true,claimInputSupported:true},
 ur:{nativeName:'اردو',direction:'rtl',reviewStatus:'not_independently_reviewed',draft:true,claimInputSupported:true},
 id:{nativeName:'Bahasa Indonesia',direction:'ltr',reviewStatus:'not_independently_reviewed',draft:true,claimInputSupported:true},
 es:{nativeName:'Español',direction:'ltr',reviewStatus:'not_independently_reviewed',draft:true,claimInputSupported:true},
 fr:{nativeName:'Français',direction:'ltr',reviewStatus:'not_independently_reviewed',draft:true,claimInputSupported:true},
 de:{nativeName:'Deutsch',direction:'ltr',reviewStatus:'not_independently_reviewed',draft:true,claimInputSupported:true}
} as const;
/** Display language does not change the input language or rerun verification. */
export function isClaimInputLanguage(language:DisplayLanguage): language is ClaimInputLanguage { return displayLanguages.includes(language); }
export function isOriginalSummaryLanguage(language:DisplayLanguage):language is 'ar'|'en' {return language==='ar'||language==='en';}
export const displayNotices:Record<DisplayLanguage,{input:string;draft:string;translating:string;translated:string;original:string;unavailable:string;quran:string;hadith:string}>={
 ar:{input:'لغة الادعاء: العربية أو الإنجليزية فقط؛ تغيير لغة العرض لا يعيد الفحص.',draft:'مسودة عرض لم تُراجع لغوياً بشكل مستقل.',translating:'جارٍ ترجمة شرح النتيجة…',translated:'ترجمة لشرح المشروع، وليست ترجمة لنص المصدر. لم تُراجع بشكل مستقل.',original:'الشرح الأصلي',unavailable:'ترجمة الشرح غير متاحة؛ يظهر الشرح الأصلي دون تغيير.',quran:'القرآن الكريم',hadith:'الأحاديث'},
 en:{input:'Claim input: Arabic or English only. Changing display language does not rerun verification.',draft:'Display draft; not independently linguistically reviewed.',translating:'Translating the result explanation…',translated:'Translation of the project explanation, not the source text. Not independently reviewed.',original:'Original explanation',unavailable:'Explanation translation unavailable; the original explanation is unchanged.',quran:'Quran',hadith:'Hadith'},
 bn:{input:'দাবি কেবল আরবি বা ইংরেজিতে লিখুন। প্রদর্শনের ভাষা বদলালে যাচাই আবার চলে না।',draft:'প্রদর্শনের খসড়া; স্বতন্ত্র ভাষাগত পর্যালোচনা হয়নি।',translating:'ফলাফলের ব্যাখ্যা অনুবাদ করা হচ্ছে…',translated:'এটি প্রকল্পের ব্যাখ্যার অনুবাদ, উৎসের পাঠের অনুবাদ নয়। স্বতন্ত্র পর্যালোচনা হয়নি।',original:'মূল ব্যাখ্যা',unavailable:'ব্যাখ্যার অনুবাদ পাওয়া যাচ্ছে না; অপরিবর্তিত মূল ব্যাখ্যা দেখানো হচ্ছে।',quran:'কুরআন',hadith:'হাদিস'},
 hi:{input:'दावा केवल अरबी या अंग्रेज़ी में लिखें। प्रदर्शन भाषा बदलने से सत्यापन दोबारा नहीं चलता।',draft:'प्रदर्शन का मसौदा; स्वतंत्र भाषाई समीक्षा नहीं हुई।',translating:'परिणाम की व्याख्या का अनुवाद हो रहा है…',translated:'यह परियोजना की व्याख्या का अनुवाद है, स्रोत के पाठ का नहीं। स्वतंत्र समीक्षा नहीं हुई।',original:'मूल व्याख्या',unavailable:'व्याख्या का अनुवाद उपलब्ध नहीं; अपरिवर्तित मूल व्याख्या दिखाई जा रही है।',quran:'कुरआन',hadith:'हदीस'},
 ur:{input:'دعویٰ صرف عربی یا انگریزی میں لکھیں۔ نمایش کی زبان بدلنے سے تصدیق دوبارہ نہیں ہوتی۔',draft:'نمایش کا مسودہ؛ آزادانہ لسانی نظرثانی نہیں ہوئی۔',translating:'نتیجے کی تشریح کا ترجمہ جاری ہے…',translated:'یہ منصوبے کی تشریح کا ترجمہ ہے، ماخذ کے متن کا نہیں۔ آزادانہ نظرثانی نہیں ہوئی۔',original:'اصل تشریح',unavailable:'تشریح کا ترجمہ دستیاب نہیں؛ اصل تشریح بغیر تبدیلی دکھائی جا رہی ہے۔',quran:'قرآن',hadith:'احادیث'},
 id:{input:'Tulis klaim hanya dalam bahasa Arab atau Inggris. Mengganti bahasa tampilan tidak mengulang verifikasi.',draft:'Draf tampilan; belum ditinjau secara linguistik oleh pihak independen.',translating:'Menerjemahkan penjelasan hasil…',translated:'Terjemahan penjelasan proyek, bukan teks sumber. Belum ditinjau secara independen.',original:'Penjelasan asli',unavailable:'Terjemahan penjelasan tidak tersedia; penjelasan asli tetap ditampilkan tanpa perubahan.',quran:'Al-Quran',hadith:'Hadis'},
 es:{input:'Escribe la afirmación solo en árabe o inglés. Cambiar el idioma de visualización no repite la verificación.',draft:'Borrador de visualización; sin revisión lingüística independiente.',translating:'Traduciendo la explicación del resultado…',translated:'Traducción de la explicación del proyecto, no del texto fuente. Sin revisión independiente.',original:'Explicación original',unavailable:'Traducción de la explicación no disponible; se muestra la explicación original sin cambios.',quran:'Corán',hadith:'Hadices'},
 fr:{input:'Écrivez l’affirmation uniquement en arabe ou en anglais. Changer la langue d’affichage ne relance pas la vérification.',draft:'Brouillon d’affichage ; sans révision linguistique indépendante.',translating:'Traduction de l’explication du résultat…',translated:'Traduction de l’explication du projet, pas du texte source. Sans révision indépendante.',original:'Explication originale',unavailable:'Traduction de l’explication indisponible ; l’explication originale reste inchangée.',quran:'Coran',hadith:'Hadiths'},
 de:{input:'Schreiben Sie die Aussage nur auf Arabisch oder Englisch. Ein Wechsel der Anzeigesprache wiederholt die Prüfung nicht.',draft:'Anzeigeentwurf; nicht unabhängig sprachlich geprüft.',translating:'Die Ergebniserklärung wird übersetzt…',translated:'Übersetzung der Projekterklärung, nicht des Quelltexts. Nicht unabhängig geprüft.',original:'Originalerklärung',unavailable:'Die Übersetzung der Erklärung ist nicht verfügbar; die Originalerklärung bleibt unverändert.',quran:'Koran',hadith:'Hadithe'}
};
export const statusCopy:Record<DisplayLanguage,Record<string,string>>={
 ar:{passed:'اجتاز فحص السلامة',not_run:'لم يُجرَ الفحص',no_candidates:'لم تُسترجع نصوص',not_reviewed:'لم تُجرَ مراجعة بشرية',not_assessed:'لم تُقيّم العلاقة',supports:'يدعم الادعاء',contradicts:'يتعارض مع الادعاء',partial:'يدعم جزءاً فقط',unrelated:'غير مرتبط بالادعاء'},
 en:{passed:'Integrity checks passed',not_run:'Not checked',no_candidates:'No passages retrieved',not_reviewed:'Not human-reviewed',not_assessed:'Relationship not assessed',supports:'Supports the claim',contradicts:'Contradicts the claim',partial:'Partial support',unrelated:'Unrelated to the claim'},
 bn:{passed:'যথার্থতার পরীক্ষায় উত্তীর্ণ',not_run:'পরীক্ষা করা হয়নি',no_candidates:'কোনো পাঠ উদ্ধার হয়নি',not_reviewed:'মানুষের পর্যালোচনা হয়নি',not_assessed:'সম্পর্ক মূল্যায়ন করা হয়নি',supports:'দাবিকে সমর্থন করে',contradicts:'দাবির বিরোধিতা করে',partial:'আংশিক সমর্থন',unrelated:'দাবির সঙ্গে সম্পর্কিত নয়'},
 hi:{passed:'शुद्धता की जाँच सफल',not_run:'जाँच नहीं हुई',no_candidates:'कोई पाठ प्राप्त नहीं हुआ',not_reviewed:'मानवीय समीक्षा नहीं हुई',not_assessed:'संबंध का मूल्यांकन नहीं हुआ',supports:'दावे का समर्थन करता है',contradicts:'दावे का विरोध करता है',partial:'आंशिक समर्थन',unrelated:'दावे से असंबंधित'},
 ur:{passed:'صحت کی جانچ کامیاب',not_run:'جانچ نہیں ہوئی',no_candidates:'کوئی متن حاصل نہیں ہوا',not_reviewed:'انسانی نظرثانی نہیں ہوئی',not_assessed:'تعلق کا جائزہ نہیں لیا گیا',supports:'دعوے کی تائید کرتا ہے',contradicts:'دعوے سے متعارض ہے',partial:'جزوی تائید',unrelated:'دعوے سے غیر متعلق'},
 id:{passed:'Pemeriksaan keutuhan lolos',not_run:'Belum diperiksa',no_candidates:'Tidak ada teks ditemukan',not_reviewed:'Belum ditinjau manusia',not_assessed:'Hubungan belum dinilai',supports:'Mendukung klaim',contradicts:'Bertentangan dengan klaim',partial:'Dukungan sebagian',unrelated:'Tidak terkait dengan klaim'},
 es:{passed:'Comprobaciones de integridad superadas',not_run:'No comprobado',no_candidates:'No se recuperaron pasajes',not_reviewed:'Sin revisión humana',not_assessed:'Relación no evaluada',supports:'Respalda la afirmación',contradicts:'Contradice la afirmación',partial:'Respaldo parcial',unrelated:'Sin relación con la afirmación'},
 fr:{passed:'Vérifications d’intégrité réussies',not_run:'Non vérifié',no_candidates:'Aucun passage retrouvé',not_reviewed:'Sans révision humaine',not_assessed:'Lien non évalué',supports:'Étaye l’affirmation',contradicts:'Contredit l’affirmation',partial:'Appui partiel',unrelated:'Sans lien avec l’affirmation'},
 de:{passed:'Integritätsprüfungen bestanden',not_run:'Nicht geprüft',no_candidates:'Keine Textstellen gefunden',not_reviewed:'Nicht von Menschen geprüft',not_assessed:'Zusammenhang nicht bewertet',supports:'Stützt die Aussage',contradicts:'Widerspricht der Aussage',partial:'Teilweise gestützt',unrelated:'Ohne Bezug zur Aussage'}
};
export const providerUnavailableCopy:Record<DisplayLanguage,string>={
 ar:'التقييم بالذكاء الاصطناعي غير مفعّل بعد. عُثر على النصوص فقط، ولم تُحكم علاقتها بالادعاء.',
 en:'AI assessment is not enabled yet. Passages were retrieved, but their relationship to the claim has not been assessed.',
 bn:'এআই মূল্যায়ন এখনো চালু হয়নি। শুধু পাঠ উদ্ধার হয়েছে; দাবির সঙ্গে তাদের সম্পর্ক মূল্যায়ন করা হয়নি।',
 hi:'एआई मूल्यांकन अभी सक्षम नहीं है। केवल पाठ प्राप्त हुए हैं; दावे से उनके संबंध का मूल्यांकन नहीं हुआ।',
 ur:'مصنوعی ذہانت کا جائزہ ابھی فعال نہیں۔ صرف متون حاصل ہوئے ہیں؛ دعوے سے ان کا تعلق نہیں جانچا گیا۔',
 id:'Penilaian AI belum diaktifkan. Teks telah ditemukan, tetapi hubungannya dengan klaim belum dinilai.',
 es:'La evaluación con IA aún no está activada. Se recuperaron pasajes, pero no se ha evaluado su relación con la afirmación.',
 fr:'L’évaluation par IA n’est pas encore activée. Des passages ont été retrouvés, mais leur lien avec l’affirmation n’a pas été évalué.',
 de:'Die KI-Bewertung ist noch nicht aktiviert. Textstellen wurden gefunden, ihr Bezug zur Aussage wurde jedoch nicht bewertet.'
};
export const scopeNoticeCopy:Partial<Record<DisplayLanguage,Record<string,string>>>={
 bn:{INPUT_INVALID:'৫ থেকে ১২০০ অক্ষরের একটি স্পষ্ট দাবি লিখুন।',PERSONAL_RULING_REFERRAL:'এই ব্যক্তিগত পরিস্থিতির জন্য যোগ্য বিশেষজ্ঞের পরামর্শ দরকার। IsnadLens ব্যক্তিগত ফতোয়া দেয় না।',SENSITIVE_SCOPE_REFERRAL:'এই বিষয় এখানে স্বয়ংক্রিয় মূল্যায়নের সীমার বাইরে; যোগ্য বিশেষজ্ঞের পর্যালোচনা প্রয়োজন।',PRIVATE_DATA_REFERRAL:'দাবি পরীক্ষার আগে ব্যক্তিগত যোগাযোগের তথ্য সরিয়ে দিন।',INSTRUCTION_INJECTION:'পরীক্ষার নিয়ম বদলানোর নির্দেশনা ছাড়া দাবিটি লিখুন।',INPUT_LANGUAGE_MISMATCH:'নির্বাচিত দাবির ভাষার সঙ্গে পাঠ মেলেনি। আরবি বা ইংরেজি বেছে নিন।'},
 hi:{INPUT_INVALID:'५ से १२०० अक्षरों का स्पष्ट दावा लिखें।',PERSONAL_RULING_REFERRAL:'इस व्यक्तिगत स्थिति में योग्य विशेषज्ञ की सलाह आवश्यक है। IsnadLens व्यक्तिगत फ़तवा नहीं देता।',SENSITIVE_SCOPE_REFERRAL:'यह विषय यहाँ स्वचालित मूल्यांकन के दायरे से बाहर है; योग्य विशेषज्ञ की समीक्षा आवश्यक है।',PRIVATE_DATA_REFERRAL:'दावे की जाँच से पहले निजी संपर्क जानकारी हटाएँ।',INSTRUCTION_INJECTION:'जाँच के नियम बदलने के निर्देश दिए बिना दावा लिखें।',INPUT_LANGUAGE_MISMATCH:'पाठ चुनी गई दावा-भाषा से मेल नहीं खाता। अरबी या अंग्रेज़ी चुनें।'},
 ur:{INPUT_INVALID:'۵ سے ۱۲۰۰ حروف کا واضح دعویٰ لکھیں۔',PERSONAL_RULING_REFERRAL:'اس ذاتی صورت حال میں اہل ماہر سے رجوع کریں۔ IsnadLens ذاتی فتویٰ نہیں دیتا۔',SENSITIVE_SCOPE_REFERRAL:'یہ موضوع یہاں خودکار جائزے کے دائرے سے باہر ہے؛ اہل ماہر کی نظرثانی درکار ہے۔',PRIVATE_DATA_REFERRAL:'دعوے کی جانچ سے پہلے ذاتی رابطے کی معلومات ہٹا دیں۔',INSTRUCTION_INJECTION:'جانچ کے اصول بدلنے کی ہدایات کے بغیر دعویٰ لکھیں۔',INPUT_LANGUAGE_MISMATCH:'متن منتخب دعوے کی زبان سے مطابقت نہیں رکھتا۔ عربی یا انگریزی منتخب کریں۔'},
 id:{INPUT_INVALID:'Tulis klaim jelas sepanjang 5–1.200 karakter.',PERSONAL_RULING_REFERRAL:'Situasi pribadi ini memerlukan ahli yang berkualifikasi. IsnadLens tidak memberikan fatwa pribadi.',SENSITIVE_SCOPE_REFERRAL:'Topik ini di luar cakupan penilaian otomatis di sini dan memerlukan tinjauan ahli.',PRIVATE_DATA_REFERRAL:'Hapus informasi kontak pribadi sebelum memeriksa klaim.',INSTRUCTION_INJECTION:'Tulis klaim tanpa instruksi untuk mengubah aturan pemeriksaan.',INPUT_LANGUAGE_MISMATCH:'Teks tidak sesuai dengan bahasa masukan yang dipilih. Pilih bahasa Arab atau Inggris.'}
};
Object.assign(scopeNoticeCopy,{
 es:{INPUT_INVALID:'Escribe una afirmación clara de entre 5 y 1.200 caracteres.',PERSONAL_RULING_REFERRAL:'Esta situación personal necesita un especialista cualificado. IsnadLens no emite fetuas personales.',SENSITIVE_SCOPE_REFERRAL:'Este tema queda fuera de la evaluación automática aquí y requiere revisión especializada.',PRIVATE_DATA_REFERRAL:'Elimina los datos de contacto personales antes de examinar la afirmación.',INSTRUCTION_INJECTION:'Escribe la afirmación sin instrucciones para modificar las reglas de examen.',INPUT_LANGUAGE_MISMATCH:'El texto no coincide con el idioma de entrada seleccionado. Elige árabe o inglés.'},
 fr:{INPUT_INVALID:'Écrivez une affirmation claire de 5 à 1 200 caractères.',PERSONAL_RULING_REFERRAL:'Cette situation personnelle nécessite un spécialiste qualifié. IsnadLens ne délivre pas de fatwas personnelles.',SENSITIVE_SCOPE_REFERRAL:'Ce sujet dépasse l’évaluation automatique proposée ici et nécessite une révision spécialisée.',PRIVATE_DATA_REFERRAL:'Retirez les coordonnées personnelles avant d’examiner l’affirmation.',INSTRUCTION_INJECTION:'Écrivez l’affirmation sans instructions visant à modifier les règles d’examen.',INPUT_LANGUAGE_MISMATCH:'Le texte ne correspond pas à la langue de saisie sélectionnée. Choisissez l’arabe ou l’anglais.'},
 de:{INPUT_INVALID:'Schreiben Sie eine klare Aussage mit 5 bis 1.200 Zeichen.',PERSONAL_RULING_REFERRAL:'Diese persönliche Situation erfordert eine qualifizierte Fachperson. IsnadLens erteilt keine persönlichen Fatwas.',SENSITIVE_SCOPE_REFERRAL:'Dieses Thema liegt außerhalb der automatischen Bewertung hier und erfordert eine fachliche Prüfung.',PRIVATE_DATA_REFERRAL:'Entfernen Sie persönliche Kontaktdaten, bevor Sie die Aussage prüfen.',INSTRUCTION_INJECTION:'Schreiben Sie die Aussage ohne Anweisungen zur Änderung der Prüfregeln.',INPUT_LANGUAGE_MISMATCH:'Der Text entspricht nicht der gewählten Eingabesprache. Wählen Sie Arabisch oder Englisch.'}
});
export const claimInputLabels:Record<DisplayLanguage,string>={ar:'لغة الادعاء',en:'Claim input language',bn:'দাবির ভাষা',hi:'दावे की भाषा',ur:'دعوے کی زبان',id:'Bahasa masukan klaim',es:'Idioma de la afirmación',fr:'Langue de l’affirmation',de:'Eingabesprache der Aussage'};
export const sourceIdentificationCopy:Record<DisplayLanguage,{auto:string;identified:string;ambiguous:string;notIdentified:string;reference:string;gradeBoundary:string}>={
 ar:{auto:'تحديد المصدر تلقائياً',identified:'المصدر المطابق',ambiguous:'تحديد المصدر غير حاسم. اختر القرآن أو الحديث يدوياً لمتابعة الفحص.',notIdentified:'لم يُحدد المصدر من المجموعات المتاحة. اختر المصدر يدوياً؛ هذا لا يثبت غياب النص عن جميع المصادر.',reference:'المواضع المرشحة',gradeBoundary:'موثوقية المصدر وسلامة الاقتباس تختلفان عن درجة الحديث. درجة الحديث أدناه من الناشر، وليست حكماً مستقلاً منا.'},
 en:{auto:'Auto-detect source',identified:'Matched source',ambiguous:'Source identification is ambiguous. Select Quran or Hadith manually to continue.',notIdentified:'No source was identified within the available collections. Select a source manually; this does not establish absence from all sources.',reference:'Candidate references',gradeBoundary:'Source trust and quotation integrity are separate from hadith grading. The grade below is supplied by the publisher, not independently assigned here.'},
 bn:{auto:'উৎস স্বয়ংক্রিয়ভাবে শনাক্ত করুন',identified:'মিলে যাওয়া উৎস',ambiguous:'উৎস শনাক্তকরণ অনিশ্চিত। পরীক্ষা চালাতে কুরআন বা হাদিস নিজে বেছে নিন।',notIdentified:'উপলব্ধ সংগ্রহে উৎস শনাক্ত হয়নি। উৎস নিজে বেছে নিন; এতে সব উৎসে পাঠটি অনুপস্থিত প্রমাণিত হয় না।',reference:'সম্ভাব্য অবস্থান',gradeBoundary:'উৎসের বিশ্বাসযোগ্যতা ও উদ্ধৃতির যথার্থতা হাদিসের মান নির্ধারণ থেকে আলাদা। নিচের মান প্রকাশকের দেওয়া, এখানে স্বাধীনভাবে নির্ধারিত নয়।'},
 hi:{auto:'स्रोत स्वतः पहचानें',identified:'मिलता हुआ स्रोत',ambiguous:'स्रोत की पहचान निश्चित नहीं है। जाँच जारी रखने के लिए कुरआन या हदीस स्वयं चुनें।',notIdentified:'उपलब्ध संग्रहों में स्रोत की पहचान नहीं हुई। स्रोत स्वयं चुनें; इससे सभी स्रोतों में पाठ का अभाव सिद्ध नहीं होता।',reference:'संभावित संदर्भ',gradeBoundary:'स्रोत की विश्वसनीयता और उद्धरण की शुद्धता हदीस के दर्जे से अलग हैं। नीचे का दर्जा प्रकाशक ने दिया है, यहाँ स्वतंत्र रूप से नहीं।'},
 ur:{auto:'ماخذ خودکار طور پر پہچانیں',identified:'مطابق ماخذ',ambiguous:'ماخذ کی شناخت غیر حتمی ہے۔ جانچ جاری رکھنے کے لیے قرآن یا حدیث خود منتخب کریں۔',notIdentified:'دستیاب مجموعوں میں ماخذ کی شناخت نہیں ہوئی۔ ماخذ خود منتخب کریں؛ اس سے تمام ماخذوں میں متن کی عدم موجودگی ثابت نہیں ہوتی۔',reference:'ممکنہ حوالہ جات',gradeBoundary:'ماخذ کی معتبریت اور اقتباس کی صحت، حدیث کے درجے سے الگ ہیں۔ درج ذیل درجہ ناشر کا ہے، یہاں آزادانہ طور پر مقرر نہیں کیا گیا۔'},
 id:{auto:'Deteksi sumber otomatis',identified:'Sumber yang cocok',ambiguous:'Identifikasi sumber belum pasti. Pilih Al-Quran atau Hadis secara manual untuk melanjutkan.',notIdentified:'Sumber belum teridentifikasi dalam koleksi yang tersedia. Pilih sumber secara manual; ini tidak membuktikan teks tidak ada di semua sumber.',reference:'Rujukan kandidat',gradeBoundary:'Kepercayaan terhadap sumber dan keutuhan kutipan berbeda dari derajat hadis. Derajat di bawah berasal dari penerbit, bukan penilaian mandiri di sini.'},
 es:{auto:'Detectar fuente automáticamente',identified:'Fuente coincidente',ambiguous:'La identificación de la fuente es ambigua. Selecciona Corán o Hadices manualmente para continuar.',notIdentified:'No se identificó la fuente en las colecciones disponibles. Selecciona una fuente manualmente; esto no demuestra su ausencia en todas las fuentes.',reference:'Referencias candidatas',gradeBoundary:'La confianza en la fuente y la integridad de la cita son distintas de la clasificación del hadiz. La clasificación siguiente procede del editor, no de una evaluación independiente nuestra.'},
 fr:{auto:'Détecter la source automatiquement',identified:'Source correspondante',ambiguous:'L’identification de la source est ambiguë. Sélectionnez Coran ou Hadiths manuellement pour continuer.',notIdentified:'Aucune source n’a été identifiée dans les collections disponibles. Sélectionnez une source manuellement ; cela ne prouve pas son absence de toutes les sources.',reference:'Références possibles',gradeBoundary:'La fiabilité de la source et l’intégrité de la citation sont distinctes du degré d’authenticité du hadith. Le degré ci-dessous provient de l’éditeur, pas d’une évaluation indépendante de notre part.'},
 de:{auto:'Quelle automatisch erkennen',identified:'Passende Quelle',ambiguous:'Die Quellenzuordnung ist mehrdeutig. Wählen Sie Koran oder Hadithe manuell, um fortzufahren.',notIdentified:'In den verfügbaren Sammlungen wurde keine Quelle erkannt. Wählen Sie die Quelle manuell; dies beweist nicht die Abwesenheit in allen Quellen.',reference:'Mögliche Fundstellen',gradeBoundary:'Quellenvertrauen und Zitatintegrität sind von der Hadith-Einstufung getrennt. Die folgende Einstufung stammt vom Herausgeber, nicht von einer unabhängigen Bewertung durch uns.'}
};
export const sourceIdentificationMethodCopy:Record<DisplayLanguage,{stated:string;matched:string;unverified:string;unavailable:string}>={
 ar:{stated:'المصدر المذكور في ادعائك',matched:'اقتباس مطابق داخل المصادر المقبولة',unverified:'نسبة المصدر هنا من كلامك؛ لا تعني أن الاقتباس طابق المصدر. تُفحص صحة النسبة لاحقاً.',unavailable:'المصدر المحدد غير متاح للفحص حالياً أو لم يجتز فحص السلامة؛ لم يُتحقق من النسبة.'},
 en:{stated:'Source stated in your claim',matched:'Quotation matched in our admitted sources',unverified:'This source attribution comes from your claim; it is not a verified quotation match. Attribution is examined in the subsequent check.',unavailable:'The selected source is currently unavailable or failed integrity checks; the attribution has not been verified.'},
 bn:{stated:'আপনার দাবিতে উল্লেখ করা উৎস',matched:'গৃহীত উৎসে উদ্ধৃতি মিলে গেছে',unverified:'এই উৎস-উল্লেখ আপনার দাবি থেকে নেওয়া; এটি যাচাইকৃত উদ্ধৃতির মিল নয়। পরবর্তী পরীক্ষায় উৎস-উল্লেখ যাচাই করা হয়।',unavailable:'নির্বাচিত উৎস এখন পাওয়া যাচ্ছে না বা যথার্থতার পরীক্ষায় ব্যর্থ হয়েছে; উৎস-উল্লেখ যাচাই হয়নি।'},
 hi:{stated:'आपके दावे में बताया गया स्रोत',matched:'हमारे स्वीकृत स्रोतों में उद्धरण मिला',unverified:'यह स्रोत-उल्लेख आपके दावे से आया है; यह सत्यापित उद्धरण-मिलान नहीं है। अगली जाँच में स्रोत-उल्लेख की जाँच होती है।',unavailable:'चुना गया स्रोत अभी उपलब्ध नहीं है या शुद्धता की जाँच में असफल हुआ; स्रोत-उल्लेख सत्यापित नहीं है।'},
 ur:{stated:'آپ کے دعوے میں بیان کردہ ماخذ',matched:'قبول شدہ ماخذوں میں اقتباس کا متن ملا',unverified:'یہ ماخذ کی نسبت آپ کے دعوے سے لی گئی ہے؛ یہ اقتباس کے تصدیق شدہ ملاپ کا ثبوت نہیں۔ اگلی جانچ میں نسبت کی پڑتال ہوتی ہے۔',unavailable:'منتخب ماخذ فی الحال دستیاب نہیں یا صحت کی جانچ میں ناکام ہوا؛ نسبت کی تصدیق نہیں ہوئی۔'},
 id:{stated:'Sumber yang disebutkan dalam klaim Anda',matched:'Kutipan cocok dalam sumber yang telah diterima',unverified:'Atribusi sumber ini berasal dari klaim Anda, bukan kecocokan kutipan yang terverifikasi. Atribusi diperiksa pada tahap berikutnya.',unavailable:'Sumber yang dipilih belum tersedia atau gagal pemeriksaan keutuhan; atribusi belum diverifikasi.'},
 es:{stated:'Fuente indicada en tu afirmación',matched:'Cita coincidente en nuestras fuentes admitidas',unverified:'Esta atribución procede de tu afirmación; no es una coincidencia verificada de la cita. La atribución se examina en la siguiente comprobación.',unavailable:'La fuente seleccionada no está disponible o no superó las comprobaciones de integridad; la atribución no se ha verificado.'},
 fr:{stated:'Source indiquée dans votre affirmation',matched:'Citation retrouvée dans nos sources admises',unverified:'Cette attribution provient de votre affirmation ; ce n’est pas une correspondance vérifiée de la citation. L’attribution est examinée à l’étape suivante.',unavailable:'La source sélectionnée est indisponible ou a échoué aux vérifications d’intégrité ; l’attribution n’a pas été vérifiée.'},
 de:{stated:'In Ihrer Aussage angegebene Quelle',matched:'Zitat in unseren zugelassenen Quellen gefunden',unverified:'Diese Quellenangabe stammt aus Ihrer Aussage; sie ist kein verifizierter Zitatabgleich. Die Zuordnung wird im nächsten Prüfschritt untersucht.',unavailable:'Die ausgewählte Quelle ist nicht verfügbar oder hat die Integritätsprüfungen nicht bestanden; die Zuordnung wurde nicht verifiziert.'}
};
const passageVoiceBase:Record<DisplayLanguage,{listen:string;stop:string;unavailableVoice:string;synthesizedNotRecitation:string;translation:string;publishedTranslation:string}>={
 ar:{listen:'استمع',stop:'إيقاف',unavailableVoice:'لا يتوفر صوت مناسب لهذه اللغة على جهازك.',synthesizedNotRecitation:'قراءة آلية مساعدة، وليست تلاوة قرآنية.',translation:'ترجمة الشرح',publishedTranslation:'ترجمة المصدر المنشورة'},
 en:{listen:'Listen',stop:'Stop',unavailableVoice:'No suitable voice for this language is available on your device.',synthesizedNotRecitation:'Assistive synthesized reading, not Quran recitation.',translation:'Explanation translation',publishedTranslation:'Published source translation'},
 bn:{listen:'শুনুন',stop:'বন্ধ করুন',unavailableVoice:'আপনার যন্ত্রে এই ভাষার উপযুক্ত কণ্ঠ নেই।',synthesizedNotRecitation:'সহায়ক কৃত্রিম কণ্ঠে পাঠ; কুরআন তিলাওয়াত নয়।',translation:'ব্যাখ্যার অনুবাদ',publishedTranslation:'উৎসের প্রকাশিত অনুবাদ'},
 hi:{listen:'सुनें',stop:'रोकें',unavailableVoice:'आपके उपकरण पर इस भाषा की उपयुक्त आवाज़ उपलब्ध नहीं है।',synthesizedNotRecitation:'सहायक कृत्रिम वाचन, कुरआन की तिलावत नहीं।',translation:'व्याख्या का अनुवाद',publishedTranslation:'स्रोत का प्रकाशित अनुवाद'},
 ur:{listen:'سنیں',stop:'روکیں',unavailableVoice:'آپ کے آلے پر اس زبان کی موزوں آواز دستیاب نہیں۔',synthesizedNotRecitation:'معاون مصنوعی آواز سے پڑھنا، قرآن کی تلاوت نہیں۔',translation:'تشریح کا ترجمہ',publishedTranslation:'ماخذ کا شائع شدہ ترجمہ'},
 id:{listen:'Dengarkan',stop:'Hentikan',unavailableVoice:'Suara yang sesuai untuk bahasa ini tidak tersedia di perangkat Anda.',synthesizedNotRecitation:'Pembacaan sintetis untuk bantuan, bukan tilawah Al-Quran.',translation:'Terjemahan penjelasan',publishedTranslation:'Terjemahan sumber yang diterbitkan'},
 es:{listen:'Escuchar',stop:'Detener',unavailableVoice:'No hay una voz adecuada para este idioma en tu dispositivo.',synthesizedNotRecitation:'Lectura sintetizada de apoyo, no recitación del Corán.',translation:'Traducción de la explicación',publishedTranslation:'Traducción publicada de la fuente'},
 fr:{listen:'Écouter',stop:'Arrêter',unavailableVoice:'Aucune voix adaptée à cette langue n’est disponible sur votre appareil.',synthesizedNotRecitation:'Lecture de synthèse vocale d’assistance, pas une récitation du Coran.',translation:'Traduction de l’explication',publishedTranslation:'Traduction publiée de la source'},
 de:{listen:'Anhören',stop:'Stoppen',unavailableVoice:'Auf Ihrem Gerät ist keine passende Stimme für diese Sprache verfügbar.',synthesizedNotRecitation:'Unterstützende synthetische Vorlesefunktion, keine Koranrezitation.',translation:'Übersetzung der Erklärung',publishedTranslation:'Veröffentlichte Übersetzung der Quelle'}
};
type PassageControls={voice:string;translationLanguage:string;loadingPassage:string;unavailablePassage:string;remoteVoiceNotice:string;openTranslationSource:string;publisherFootnotes:string;editionNotice:string};
const passageControls:Record<DisplayLanguage,PassageControls>={
 ar:{voice:'الصوت',translationLanguage:'لغة ترجمة النص',loadingPassage:'جارٍ تحميل النص المنشور…',unavailablePassage:'لا يتوفر نص منشور مطابق لهذه اللغة والإحالة.',remoteVoiceNotice:'قد يعالج مزوّد الصوت النص خارج جهازك حسب خدمة الصوت المختارة.',openTranslationSource:'افتح مصدر الترجمة',publisherFootnotes:'حواشي الناشر',editionNotice:'هذه الترجمة من إصدار المصدر المحدد؛ قد تختلف ألفاظها عن ترجمات أخرى.'},
 en:{voice:'Voice',translationLanguage:'Passage translation language',loadingPassage:'Loading the published passage…',unavailablePassage:'No matching published passage is available for this language and reference.',remoteVoiceNotice:'The selected voice service may process this text outside your device.',openTranslationSource:'Open translation source',publisherFootnotes:'Publisher footnotes',editionNotice:'This translation belongs to the identified source edition; wording may differ from other translations.'},
 bn:{voice:'কণ্ঠ',translationLanguage:'পাঠের অনুবাদের ভাষা',loadingPassage:'প্রকাশিত পাঠ লোড হচ্ছে…',unavailablePassage:'এই ভাষা ও উল্লেখের জন্য মিলে যাওয়া প্রকাশিত পাঠ নেই।',remoteVoiceNotice:'নির্বাচিত কণ্ঠসেবা আপনার যন্ত্রের বাইরে এই পাঠ প্রক্রিয়াকরণ করতে পারে।',openTranslationSource:'অনুবাদের উৎস খুলুন',publisherFootnotes:'প্রকাশকের পাদটীকা',editionNotice:'এই অনুবাদ নির্দিষ্ট উৎসের সংস্করণ থেকে নেওয়া; অন্য অনুবাদের ভাষা ভিন্ন হতে পারে।'},
 hi:{voice:'आवाज़',translationLanguage:'पाठ के अनुवाद की भाषा',loadingPassage:'प्रकाशित पाठ लोड हो रहा है…',unavailablePassage:'इस भाषा और संदर्भ के लिए मेल खाता प्रकाशित पाठ उपलब्ध नहीं है।',remoteVoiceNotice:'चुनी गई आवाज़ सेवा इस पाठ को आपके उपकरण के बाहर संसाधित कर सकती है।',openTranslationSource:'अनुवाद का स्रोत खोलें',publisherFootnotes:'प्रकाशक की टिप्पणियाँ',editionNotice:'यह अनुवाद निर्दिष्ट स्रोत-संस्करण से है; अन्य अनुवादों की शब्दावली भिन्न हो सकती है।'},
 ur:{voice:'آواز',translationLanguage:'متن کے ترجمے کی زبان',loadingPassage:'شائع شدہ متن لوڈ ہو رہا ہے…',unavailablePassage:'اس زبان اور حوالے کے لیے مطابق شائع شدہ متن دستیاب نہیں۔',remoteVoiceNotice:'منتخب صوتی خدمت اس متن کو آپ کے آلے سے باہر پراسیس کر سکتی ہے۔',openTranslationSource:'ترجمے کا ماخذ کھولیں',publisherFootnotes:'ناشر کے حواشی',editionNotice:'یہ ترجمہ متعین ماخذ کے نسخے سے ہے؛ دوسرے ترجموں کے الفاظ مختلف ہو سکتے ہیں۔'},
 id:{voice:'Suara',translationLanguage:'Bahasa terjemahan teks',loadingPassage:'Memuat teks yang diterbitkan…',unavailablePassage:'Teks terbitan yang cocok tidak tersedia untuk bahasa dan rujukan ini.',remoteVoiceNotice:'Layanan suara yang dipilih dapat memproses teks ini di luar perangkat Anda.',openTranslationSource:'Buka sumber terjemahan',publisherFootnotes:'Catatan kaki penerbit',editionNotice:'Terjemahan ini berasal dari edisi sumber yang disebutkan; pilihan kata dapat berbeda dari terjemahan lain.'},
 es:{voice:'Voz',translationLanguage:'Idioma de traducción del pasaje',loadingPassage:'Cargando el pasaje publicado…',unavailablePassage:'No hay un pasaje publicado coincidente para este idioma y referencia.',remoteVoiceNotice:'El servicio de voz seleccionado puede procesar este texto fuera de tu dispositivo.',openTranslationSource:'Abrir fuente de la traducción',publisherFootnotes:'Notas del editor',editionNotice:'Esta traducción pertenece a la edición indicada de la fuente; su redacción puede diferir de otras traducciones.'},
 fr:{voice:'Voix',translationLanguage:'Langue de traduction du passage',loadingPassage:'Chargement du passage publié…',unavailablePassage:'Aucun passage publié correspondant n’est disponible pour cette langue et cette référence.',remoteVoiceNotice:'Le service vocal sélectionné peut traiter ce texte hors de votre appareil.',openTranslationSource:'Ouvrir la source de traduction',publisherFootnotes:'Notes de l’éditeur',editionNotice:'Cette traduction appartient à l’édition indiquée de la source ; sa formulation peut différer d’autres traductions.'},
 de:{voice:'Stimme',translationLanguage:'Übersetzungssprache der Textstelle',loadingPassage:'Die veröffentlichte Textstelle wird geladen…',unavailablePassage:'Für diese Sprache und Fundstelle ist keine passende veröffentlichte Textstelle verfügbar.',remoteVoiceNotice:'Der gewählte Sprachdienst kann diesen Text außerhalb Ihres Geräts verarbeiten.',openTranslationSource:'Übersetzungsquelle öffnen',publisherFootnotes:'Fußnoten des Herausgebers',editionNotice:'Diese Übersetzung gehört zur angegebenen Quellenausgabe; der Wortlaut kann von anderen Übersetzungen abweichen.'}
};
export const passageVoiceCopy=Object.fromEntries(displayLanguages.map(language=>[language,{...passageVoiceBase[language],...passageControls[language]}])) as Record<DisplayLanguage,typeof passageVoiceBase.ar & PassageControls>;
export const naturalSearchCopy:Record<DisplayLanguage,{auto:string;searched:string;expanded:string;lexical:string;ambiguous:string;pigExample:string}>={
 ar:{auto:'ابحث في القرآن والحديث تلقائياً',searched:'بحثنا عن أدلة لادعائك في مجموعتي القرآن والحديث المقبولتين؛ هذا ليس ادعاءً بمطابقة اقتباس.',expanded:'ساعد النموذج في اختيار كلمات بحث مرتبطة بالمعنى، ثم فُحصت النصوص المسترجعة.',lexical:'استُخدمت كلمات ادعائك للبحث المباشر؛ قد يفوت البحث نصوصاً تعبّر عن المعنى بألفاظ أخرى.',ambiguous:'ظهر النص في أكثر من مصدر؛ يجري فحص الأدلة من المجموعتين دون افتراض نسبة واحدة.',pigExample:'أكل لحم الخنزير حرام.'},
 en:{auto:'Search Quran and Hadith automatically',searched:'We searched the admitted Quran and Hadith collections for evidence about your claim; this is not a quotation-match claim.',expanded:'The model helped choose related search words, then the retrieved passages were examined.',lexical:'Your claim words were used for direct search; passages expressing the same meaning differently may be missed.',ambiguous:'The text appears in more than one source; evidence from both collections is examined without assuming a single attribution.',pigExample:'pig eating is haram'},
 bn:{auto:'কুরআন ও হাদিসে স্বয়ংক্রিয় অনুসন্ধান',searched:'আপনার দাবির প্রমাণের জন্য গৃহীত কুরআন ও হাদিস সংগ্রহে অনুসন্ধান করা হয়েছে; এটি উদ্ধৃতি মিলে যাওয়ার দাবি নয়।',expanded:'মডেল সংশ্লিষ্ট অনুসন্ধানের শব্দ বেছে নিতে সাহায্য করেছে; এরপর উদ্ধার করা পাঠ পরীক্ষা করা হয়েছে।',lexical:'সরাসরি অনুসন্ধানে আপনার দাবির শব্দ ব্যবহার করা হয়েছে; ভিন্ন শব্দে একই অর্থ প্রকাশ করা পাঠ বাদ পড়তে পারে।',ambiguous:'পাঠ একাধিক উৎসে আছে; একটিমাত্র উৎস ধরে না নিয়ে উভয় সংগ্রহের প্রমাণ পরীক্ষা করা হচ্ছে।',pigExample:'pig eating is haram'},
 hi:{auto:'कुरआन और हदीस में स्वतः खोजें',searched:'आपके दावे के प्रमाण के लिए स्वीकृत कुरआन और हदीस संग्रहों में खोज हुई; यह उद्धरण के मिलान का दावा नहीं है।',expanded:'मॉडल ने संबंधित खोज-शब्द चुनने में मदद की; फिर मिले पाठों की जाँच हुई।',lexical:'सीधी खोज में आपके दावे के शब्द इस्तेमाल हुए; उसी अर्थ को अलग शब्दों में व्यक्त करने वाले पाठ छूट सकते हैं।',ambiguous:'पाठ एक से अधिक स्रोतों में है; एक ही स्रोत मान लिए बिना दोनों संग्रहों के प्रमाण की जाँच हो रही है।',pigExample:'pig eating is haram'},
 ur:{auto:'قرآن اور حدیث میں خودکار تلاش',searched:'آپ کے دعوے کے دلائل کے لیے قبول شدہ قرآن اور حدیث کے مجموعوں میں تلاش ہوئی؛ یہ اقتباس کے ملاپ کا دعویٰ نہیں۔',expanded:'ماڈل نے متعلقہ تلاش کے الفاظ چننے میں مدد کی؛ پھر حاصل شدہ متون کی جانچ ہوئی۔',lexical:'براہ راست تلاش میں آپ کے دعوے کے الفاظ استعمال ہوئے؛ مختلف الفاظ میں یکساں معنی والے متون رہ سکتے ہیں۔',ambiguous:'متن ایک سے زیادہ ماخذوں میں ہے؛ ایک نسبت فرض کیے بغیر دونوں مجموعوں کے دلائل جانچے جا رہے ہیں۔',pigExample:'pig eating is haram'},
 id:{auto:'Cari Al-Quran dan Hadis secara otomatis',searched:'Kami mencari bukti untuk klaim Anda dalam koleksi Al-Quran dan Hadis yang diterima; ini bukan klaim kecocokan kutipan.',expanded:'Model membantu memilih kata pencarian terkait, lalu teks yang ditemukan diperiksa.',lexical:'Kata dalam klaim digunakan untuk pencarian langsung; teks bermakna sama dengan kata berbeda mungkin terlewat.',ambiguous:'Teks muncul di lebih dari satu sumber; bukti dari kedua koleksi diperiksa tanpa mengasumsikan satu atribusi.',pigExample:'pig eating is haram'},
 es:{auto:'Buscar Corán y Hadices automáticamente',searched:'Buscamos evidencia para tu afirmación en las colecciones admitidas del Corán y los hadices; no afirmamos una coincidencia de cita.',expanded:'El modelo ayudó a elegir palabras de búsqueda relacionadas; después se examinaron los pasajes recuperados.',lexical:'Se usaron las palabras de tu afirmación para buscar directamente; pueden omitirse pasajes que expresen lo mismo de otra forma.',ambiguous:'El texto aparece en más de una fuente; se examina la evidencia de ambas colecciones sin suponer una atribución única.',pigExample:'pig eating is haram'},
 fr:{auto:'Rechercher automatiquement dans le Coran et les hadiths',searched:'Nous avons recherché des preuves pour votre affirmation dans les collections admises du Coran et des hadiths ; ce n’est pas une affirmation de correspondance de citation.',expanded:'Le modèle a aidé à choisir des mots de recherche associés, puis les passages retrouvés ont été examinés.',lexical:'Les mots de votre affirmation ont servi à la recherche directe ; des passages exprimant le même sens autrement peuvent être manqués.',ambiguous:'Le texte apparaît dans plusieurs sources ; les preuves des deux collections sont examinées sans supposer une attribution unique.',pigExample:'pig eating is haram'},
 de:{auto:'Koran und Hadithe automatisch durchsuchen',searched:'Wir haben in den zugelassenen Koran- und Hadith-Sammlungen nach Belegen für Ihre Aussage gesucht; dies ist keine Behauptung eines Zitatabgleichs.',expanded:'Das Modell half bei der Auswahl verwandter Suchwörter; danach wurden die gefundenen Textstellen geprüft.',lexical:'Ihre Aussagewörter wurden zur direkten Suche genutzt; gleichbedeutende Textstellen mit anderem Wortlaut können übersehen werden.',ambiguous:'Der Text erscheint in mehr als einer Quelle; Belege beider Sammlungen werden ohne Annahme einer einzigen Zuordnung geprüft.',pigExample:'pig eating is haram'}
};
export const intakeCopy:Record<DisplayLanguage,{automatic:string;detected:string;ambiguous:string;input:string;intro:string;placeholder:string;boundary:string;originalExplanationOnly:string}>={
 ar:{automatic:'تحديد اللغة تلقائياً',detected:'لغة الادعاء المحددة',ambiguous:'لم تُحدد اللغة بثقة. اختر لغة الادعاء يدوياً ثم أعد الفحص.',input:'اكتب بلغتك؛ نحدد اللغة تلقائياً أو يمكنك اختيار إحدى اللغات التسع. تغيير لغة العرض لا يعيد فحص الادعاء.',intro:'اكتب ادعاءً بلغتك. نبحث عن الأدلة المرتبطة بمعناه ونفحص نصوص المصدر، مع إظهار ما يدعمه الدليل وما يبقى غير محسوم.',placeholder:'مثال: هل أكل لحم الخنزير حرام؟',boundary:'قد نستخدم شرحاً مساعداً لعبارتك للبحث في المصادر العربية والإنجليزية المقبولة. يبقى ادعاؤك ونص المصدر الأصلي محفوظين دون تغيير.',originalExplanationOnly:'يظهر الشرح الأصلي. لم نطلب ترجمة إضافية تلقائياً؛ اختر لغة العرض إذا أردت ترجمة شرح النتيجة.'},
 en:{automatic:'Detect language automatically',detected:'Detected claim language',ambiguous:'The language could not be identified confidently. Select the claim language manually and examine again.',input:'Write in your language; we detect it automatically, or you can select one of nine languages. Changing display language does not rerun verification.',intro:'Write a claim in your language. We search for evidence related to its meaning and examine the source text, showing what the evidence supports and what remains unresolved.',placeholder:'Example: Is eating pork forbidden?',boundary:'We may use an assisting interpretation of your wording to search admitted Arabic and English sources. Your original claim and the source text remain unchanged.',originalExplanationOnly:'The original explanation is shown. No extra translation was requested automatically; choose a display language to request a translated result explanation.'},
 bn:{automatic:'ভাষা স্বয়ংক্রিয়ভাবে শনাক্ত করুন',detected:'শনাক্ত করা দাবির ভাষা',ambiguous:'ভাষা নিশ্চিতভাবে শনাক্ত হয়নি। দাবির ভাষা নিজে বেছে নিয়ে আবার পরীক্ষা করুন।',input:'আপনার ভাষায় লিখুন; আমরা ভাষা শনাক্ত করি, অথবা আপনি নয়টি ভাষার একটি বেছে নিতে পারেন। প্রদর্শনের ভাষা বদলালে যাচাই আবার চলে না।',intro:'আপনার ভাষায় দাবি লিখুন। আমরা তার অর্থের সঙ্গে সম্পর্কিত প্রমাণ খুঁজি ও উৎসের পাঠ পরীক্ষা করি; প্রমাণ কী সমর্থন করে আর কী অমীমাংসিত তা দেখাই।',placeholder:'উদাহরণ: শূকরের মাংস খাওয়া কি হারাম?',boundary:'গৃহীত আরবি ও ইংরেজি উৎসে অনুসন্ধানে আপনার কথার সহায়ক ব্যাখ্যা ব্যবহার করা হতে পারে। আপনার মূল দাবি ও উৎসের পাঠ অপরিবর্তিত থাকে।',originalExplanationOnly:'মূল ব্যাখ্যা দেখানো হচ্ছে। অতিরিক্ত অনুবাদ স্বয়ংক্রিয়ভাবে চাওয়া হয়নি; ব্যাখ্যার অনুবাদ চাইলে প্রদর্শনের ভাষা বেছে নিন।'},
 hi:{automatic:'भाषा स्वतः पहचानें',detected:'पहचानी गई दावे की भाषा',ambiguous:'भाषा की पहचान निश्चित नहीं हो सकी। दावे की भाषा स्वयं चुनकर दोबारा जाँच करें।',input:'अपनी भाषा में लिखें; हम भाषा पहचानते हैं, या आप नौ भाषाओं में से एक चुन सकते हैं। प्रदर्शन भाषा बदलने से सत्यापन दोबारा नहीं चलता।',intro:'अपनी भाषा में दावा लिखें। हम उसके अर्थ से संबंधित प्रमाण खोजते और स्रोत का पाठ जाँचते हैं; प्रमाण क्या समर्थित करता है और क्या अनिर्णीत है, दिखाते हैं।',placeholder:'उदाहरण: क्या सूअर का मांस खाना हराम है?',boundary:'स्वीकृत अरबी और अंग्रेज़ी स्रोतों में खोज के लिए आपके शब्दों की सहायक व्याख्या का उपयोग हो सकता है। आपका मूल दावा और स्रोत का पाठ अपरिवर्तित रहते हैं।',originalExplanationOnly:'मूल व्याख्या दिखाई जा रही है। अतिरिक्त अनुवाद स्वतः नहीं माँगा गया; अनुवाद चाहें तो प्रदर्शन भाषा चुनें।'},
 ur:{automatic:'زبان خودکار طور پر پہچانیں',detected:'شناخت شدہ دعوے کی زبان',ambiguous:'زبان کی پُراعتماد شناخت نہیں ہو سکی۔ دعوے کی زبان خود منتخب کرکے دوبارہ جانچ کریں۔',input:'اپنی زبان میں لکھیں؛ ہم زبان پہچانتے ہیں، یا آپ نو زبانوں میں سے ایک منتخب کر سکتے ہیں۔ نمایش کی زبان بدلنے سے تصدیق دوبارہ نہیں ہوتی۔',intro:'اپنی زبان میں دعویٰ لکھیں۔ ہم اس کے معنی سے متعلق دلائل تلاش کرکے ماخذ کا متن جانچتے ہیں، اور دکھاتے ہیں کہ دلیل کیا ثابت کرتی ہے اور کیا غیر طے شدہ رہتا ہے۔',placeholder:'مثال: کیا سور کا گوشت کھانا حرام ہے؟',boundary:'قبول شدہ عربی اور انگریزی ماخذوں میں تلاش کے لیے آپ کے الفاظ کی معاون تشریح استعمال ہو سکتی ہے۔ اصل دعویٰ اور ماخذ کا متن بغیر تبدیلی محفوظ رہتے ہیں۔',originalExplanationOnly:'اصل تشریح دکھائی جا رہی ہے۔ اضافی ترجمہ خودکار طور پر نہیں مانگا گیا؛ ترجمہ چاہیں تو نمایش کی زبان منتخب کریں۔'},
 id:{automatic:'Deteksi bahasa otomatis',detected:'Bahasa klaim yang terdeteksi',ambiguous:'Bahasa belum teridentifikasi dengan yakin. Pilih bahasa klaim secara manual lalu periksa lagi.',input:'Tulis dalam bahasa Anda; kami mendeteksinya otomatis, atau Anda dapat memilih satu dari sembilan bahasa. Mengganti bahasa tampilan tidak mengulang verifikasi.',intro:'Tulis klaim dalam bahasa Anda. Kami mencari bukti yang berkaitan dengan maknanya dan memeriksa teks sumber, menunjukkan apa yang didukung bukti dan apa yang belum terjawab.',placeholder:'Contoh: Apakah makan daging babi haram?',boundary:'Kami dapat menggunakan penafsiran pembantu atas kata-kata Anda untuk mencari sumber Arab dan Inggris yang diterima. Klaim asli dan teks sumber tidak diubah.',originalExplanationOnly:'Penjelasan asli ditampilkan. Terjemahan tambahan tidak diminta otomatis; pilih bahasa tampilan untuk meminta terjemahan penjelasan hasil.'},
 es:{automatic:'Detectar idioma automáticamente',detected:'Idioma detectado de la afirmación',ambiguous:'No se pudo identificar el idioma con confianza. Selecciona el idioma manualmente y vuelve a examinar.',input:'Escribe en tu idioma; lo detectamos automáticamente, o puedes elegir uno de nueve idiomas. Cambiar el idioma de visualización no repite la verificación.',intro:'Escribe una afirmación en tu idioma. Buscamos evidencia relacionada con su significado y examinamos el texto fuente, mostrando qué respalda la evidencia y qué queda sin resolver.',placeholder:'Ejemplo: ¿Está prohibido comer cerdo?',boundary:'Podemos usar una interpretación auxiliar de tus palabras para buscar en fuentes admitidas en árabe e inglés. La afirmación original y el texto fuente no se modifican.',originalExplanationOnly:'Se muestra la explicación original. No se solicitó una traducción adicional automáticamente; elige un idioma de visualización para traducir la explicación.'},
 fr:{automatic:'Détecter la langue automatiquement',detected:'Langue détectée de l’affirmation',ambiguous:'La langue n’a pas pu être identifiée avec confiance. Sélectionnez-la manuellement et relancez l’examen.',input:'Écrivez dans votre langue ; nous la détectons automatiquement, ou vous pouvez choisir parmi neuf langues. Changer la langue d’affichage ne relance pas la vérification.',intro:'Écrivez une affirmation dans votre langue. Nous recherchons des preuves liées à son sens et examinons le texte source, en montrant ce qui est étayé et ce qui reste indéterminé.',placeholder:'Exemple : Est-il interdit de manger du porc ?',boundary:'Nous pouvons utiliser une interprétation auxiliaire de vos mots pour rechercher dans les sources arabes et anglaises admises. L’affirmation originale et le texte source restent inchangés.',originalExplanationOnly:'L’explication originale est affichée. Aucune traduction supplémentaire n’a été demandée automatiquement ; choisissez une langue d’affichage pour la traduire.'},
 de:{automatic:'Sprache automatisch erkennen',detected:'Erkannte Sprache der Aussage',ambiguous:'Die Sprache konnte nicht sicher erkannt werden. Wählen Sie die Eingabesprache manuell und prüfen Sie erneut.',input:'Schreiben Sie in Ihrer Sprache; wir erkennen sie automatisch, oder Sie wählen eine von neun Sprachen. Ein Wechsel der Anzeigesprache wiederholt die Prüfung nicht.',intro:'Schreiben Sie eine Aussage in Ihrer Sprache. Wir suchen nach Belegen für ihre Bedeutung und prüfen den Quelltext, wobei sichtbar bleibt, was gestützt ist und was offenbleibt.',placeholder:'Beispiel: Ist es verboten, Schweinefleisch zu essen?',boundary:'Wir können eine unterstützende Deutung Ihrer Worte nutzen, um zugelassene arabische und englische Quellen zu durchsuchen. Originalaussage und Quelltext bleiben unverändert.',originalExplanationOnly:'Die Originalerklärung wird angezeigt. Es wurde keine zusätzliche Übersetzung automatisch angefordert; wählen Sie eine Anzeigesprache, um die Erklärung übersetzen zu lassen.'}
};
export const displayCopy=Object.fromEntries(displayLanguages.map(language=>[language,{...interfaceCopy[language],intro:intakeCopy[language].intro,placeholder:intakeCopy[language].placeholder}])) as Readonly<Record<DisplayLanguage,DisplayCopy>>;
const nativePigExamples:Record<DisplayLanguage,string>={ar:'أكل لحم الخنزير حرام.',en:'pig eating is haram',bn:'শূকরের মাংস খাওয়া হারাম।',hi:'सूअर का मांस खाना हराम है।',ur:'سور کا گوشت کھانا حرام ہے۔',id:'Makan daging babi itu haram.',es:'Comer carne de cerdo está prohibido.',fr:'Manger du porc est interdit.',de:'Schweinefleisch zu essen ist verboten.'};
for(const language of displayLanguages){
 displayNotices[language].input=intakeCopy[language].input;
 naturalSearchCopy[language].pigExample=nativePigExamples[language];
 if(scopeNoticeCopy[language])scopeNoticeCopy[language]!.INPUT_LANGUAGE_MISMATCH=intakeCopy[language].ambiguous;
}

