/** Interface copy only. Never translate or mutate sealed evidence with this module. */
export const displayLanguages = ['ar','en','bn','hi','ur','id'] as const;
export type DisplayLanguage = typeof displayLanguages[number];
export type ClaimInputLanguage = 'ar' | 'en';
const existingCopy = {
  ar: { subtitle: 'الدليل أولاً، ثم التفسير.', nav: 'كيف تعمل العدسة', eyebrow: 'مساحة هادئة لفحص الادعاءات', title: 'من القول،', title2: 'إلى دليل يمكن تتبّعه.', intro: 'اكتب ادعاءً بالعربية أو الإنجليزية. ابحث عن النص المرتبط به، وافحص سلامة الاقتباس، وافهم ما يدعمه الدليل — وما لا يحسمه.', inputTitle: 'ما القول الذي تريد فحصه؟', inputHint: 'ابدأ بعبارة واحدة واضحة. النتيجة تخص المصادر المتاحة هنا فقط.', placeholder: 'مثال: يذكر القرآن أن كل شيء حي جُعل من الماء.', submit: 'افحص الدليل', loading: 'جارٍ فحص المصادر…', presets: 'جرّب سؤالاً', examples: ['يذكر القرآن أن كل شيء حي جُعل من الماء.', 'يذكر القرآن أن الحياة لا ترتبط بالماء.', 'هناك حكم قرآني صريح عن تطبيق هاتف معيّن.'], scope: 'نطاق المصادر', available: 'مصدر جاهز للبحث', unavailable: 'المصادر قيد التجهيز', inferenceReady: 'التقييم الدلالي متاح', inferenceUnavailable: 'التقييم الدلالي غير متاح حالياً', coverageNote: 'تُعرض التغطية الفعلية؛ لا ندّعي البحث في جميع المصادر الإسلامية.', first: 'العثور على النص', firstNote: 'داخل المصادر المقبولة فقط', second: 'فحص الاقتباس', secondNote: 'النص والموضع والإصدار', third: 'قراءة العلاقة', thirdNote: 'تقييم دلالي بحدود واضحة', result: 'سجل الفحص', evidence: 'النصوص المسترجعة', noEvidence: 'لم تُسترجع نصوص لهذا الادعاء. لا يعني ذلك أن الادعاء صحيح أو خاطئ.', integrityPass: 'سلامة الاقتباس: اجتاز الفحص', integrityFail: 'سلامة الاقتباس: لم يجتز الفحص', source: 'افتح المصدر', details: 'الموضع وتفاصيل الفحص', limitations: 'حدود هذه النتيجة', notFatwa: 'هذه أداة لتتبّع الأدلة، وليست فتوى أو تصحيحاً مستقلاً للأحاديث.', emptyTitle: 'دع الدليل يأخذ مكانه.', emptyNote: 'تظهر هنا النتيجة والنص الأصلي وموضعه بعد الفحص. لا توجد نتائج معدّة مسبقاً.', error: 'تعذّر إكمال الفحص. حاول مرة أخرى.', langs: 'لغات العرض', beta: 'قريباً · يتطلب مراجعة لغوية', record: 'معرّف السجل', seal: 'بصمة السجل', relationship: 'العلاقة الدلالية', human: 'المراجعة العلمية', technical: 'التحقق التقني', translation: 'المراجعة اللغوية', supported: 'يدعمه المصدر المحدد', conflicting: 'يتعارض مع المصدر المحدد', insufficient: 'الدليل المتاح غير كافٍ', notEvaluated: 'لم يُجرَ التقييم الدلالي', disclaimer: 'العثور على اقتباس سليم لا يثبت وحده صحة تفسير الادعاء.' },
  en: { subtitle: 'Evidence first. Interpretation second.', nav: 'How the lens works', eyebrow: 'A quiet desk for examining claims', title: 'From a claim,', title2: 'to a source you can trace.', intro: 'Write a claim in Arabic or English. Find the related text, check the quotation, and understand what the evidence supports — and what it leaves unresolved.', inputTitle: 'What would you like to examine?', inputHint: 'Start with one clear statement. Results apply only to the sources available here.', placeholder: 'Example: The Quran says every living thing was made from water.', submit: 'Examine the evidence', loading: 'Checking the sources…', presets: 'Try a claim', examples: ['The Quran says every living thing was made from water.', 'The Quran says life has no connection to water.', 'The Quran gives an explicit ruling about a particular mobile app.'], scope: 'Source coverage', available: 'Source ready to search', unavailable: 'Sources being prepared', inferenceReady: 'Semantic assessment available', inferenceUnavailable: 'Semantic assessment currently unavailable', coverageNote: 'Actual coverage is shown. We do not claim to search every Islamic source.', first: 'Find the text', firstNote: 'Within admitted sources only', second: 'Check the quotation', secondNote: 'Text, location and edition', third: 'Examine the relationship', thirdNote: 'A bounded semantic assessment', result: 'Examination record', evidence: 'Retrieved passages', noEvidence: 'No passages were retrieved for this claim. This does not establish that the claim is true or false.', integrityPass: 'Quotation integrity: passed', integrityFail: 'Quotation integrity: failed', source: 'Open source', details: 'Location and verification details', limitations: 'Limits of this result', notFatwa: 'A tool for tracing evidence, not a fatwa or independent hadith authentication.', emptyTitle: 'Let the evidence take its place.', emptyNote: 'Your result, the original text and its location appear here after examination. No prewritten results.', error: 'The examination could not be completed. Please try again.', langs: 'Display languages', beta: 'Coming later · linguistic review required', record: 'Record ID', seal: 'Record fingerprint', relationship: 'Semantic relationship', human: 'Scholarly review', technical: 'Technical verification', translation: 'Linguistic review', supported: 'Supported within the selected corpus', conflicting: 'Conflicting within the selected corpus', insufficient: 'Available evidence is insufficient', notEvaluated: 'Semantic assessment not performed', disclaimer: 'A verified quotation alone does not establish a correct interpretation of the claim.' }
};
export type DisplayCopy = { [K in keyof typeof existingCopy.en]: K extends 'examples' ? string[] : string };
const bn: DisplayCopy = {
 subtitle:'আগে প্রমাণ, তারপর ব্যাখ্যা।',nav:'লেন্স কীভাবে কাজ করে',eyebrow:'দাবি পরীক্ষা করার শান্ত পরিসর',title:'একটি দাবি থেকে,',title2:'যাচাইযোগ্য উৎসের দিকে।',intro:'আরবি বা ইংরেজিতে একটি দাবি লিখুন। সংশ্লিষ্ট পাঠ খুঁজুন, উদ্ধৃতির যথার্থতা পরীক্ষা করুন এবং প্রমাণ কী সমর্থন করে আর কী অমীমাংসিত রাখে তা বুঝুন।',inputTitle:'কোন দাবিটি পরীক্ষা করতে চান?',inputHint:'একটি স্পষ্ট বক্তব্য দিয়ে শুরু করুন। ফলাফল কেবল এখানে উপলব্ধ উৎসগুলোর জন্য প্রযোজ্য।',placeholder:'দাবি আরবি বা ইংরেজিতে লিখুন।',submit:'প্রমাণ পরীক্ষা করুন',loading:'উৎস পরীক্ষা করা হচ্ছে…',presets:'একটি দাবি চেষ্টা করুন',examples:existingCopy.en.examples,scope:'উৎসের পরিধি',available:'উৎস অনুসন্ধানের জন্য প্রস্তুত',unavailable:'উৎস প্রস্তুত করা হচ্ছে',inferenceReady:'অর্থগত মূল্যায়ন উপলব্ধ',inferenceUnavailable:'অর্থগত মূল্যায়ন এখন উপলব্ধ নয়',coverageNote:'প্রকৃত পরিধি দেখানো হয়। আমরা সব ইসলামি উৎস অনুসন্ধানের দাবি করি না।',first:'পাঠ খুঁজুন',firstNote:'কেবল গৃহীত উৎসে',second:'উদ্ধৃতি পরীক্ষা করুন',secondNote:'পাঠ, অবস্থান ও সংস্করণ',third:'সম্পর্ক পরীক্ষা করুন',thirdNote:'স্পষ্ট সীমাসহ অর্থগত মূল্যায়ন',result:'পরীক্ষার রেকর্ড',evidence:'উদ্ধার করা পাঠ',noEvidence:'এই দাবির জন্য কোনো পাঠ উদ্ধার হয়নি। এতে দাবিটি সত্য বা মিথ্যা প্রমাণিত হয় না।',integrityPass:'উদ্ধৃতির যথার্থতা: পরীক্ষায় উত্তীর্ণ',integrityFail:'উদ্ধৃতির যথার্থতা: পরীক্ষায় ব্যর্থ',source:'উৎস খুলুন',details:'অবস্থান ও পরীক্ষার বিস্তারিত',limitations:'ফলাফলের সীমাবদ্ধতা',notFatwa:'এটি প্রমাণ অনুসরণের উপকরণ; ফতোয়া বা স্বতন্ত্র হাদিস প্রমাণীকরণ নয়।',emptyTitle:'প্রমাণকে সামনে আসতে দিন।',emptyNote:'পরীক্ষার পরে ফলাফল, মূল পাঠ ও তার অবস্থান এখানে দেখা যাবে। আগে থেকে লেখা ফলাফল নেই।',error:'পরীক্ষা সম্পন্ন করা যায়নি। আবার চেষ্টা করুন।',langs:'প্রদর্শনের ভাষা',beta:'খসড়া · স্বতন্ত্র ভাষাগত পর্যালোচনা হয়নি',record:'রেকর্ড পরিচিতি',seal:'রেকর্ডের ফিঙ্গারপ্রিন্ট',relationship:'অর্থগত সম্পর্ক',human:'বিশেষজ্ঞ পর্যালোচনা',technical:'প্রযুক্তিগত যাচাই',translation:'ভাষাগত পর্যালোচনা',supported:'নির্বাচিত উৎসসমষ্টির মধ্যে সমর্থিত',conflicting:'নির্বাচিত উৎসসমষ্টির সঙ্গে সাংঘর্ষিক',insufficient:'উপলব্ধ প্রমাণ অপর্যাপ্ত',notEvaluated:'অর্থগত মূল্যায়ন করা হয়নি',disclaimer:'সঠিক উদ্ধৃতি পাওয়া মাত্রই দাবির ব্যাখ্যা সঠিক প্রমাণিত হয় না।'
};
const hi: DisplayCopy = {
 subtitle:'पहले प्रमाण, फिर व्याख्या।',nav:'लेंस कैसे काम करता है',eyebrow:'दावों की जाँच के लिए शांत स्थान',title:'एक दावे से,',title2:'ऐसे स्रोत तक जिसे जाँचा जा सके।',intro:'अरबी या अंग्रेज़ी में दावा लिखें। संबंधित पाठ खोजें, उद्धरण की शुद्धता जाँचें और समझें कि प्रमाण क्या समर्थित करता है और क्या अनिर्णीत छोड़ता है।',inputTitle:'आप किस दावे की जाँच करना चाहते हैं?',inputHint:'एक स्पष्ट कथन से शुरू करें। परिणाम केवल यहाँ उपलब्ध स्रोतों पर लागू हैं।',placeholder:'दावा अरबी या अंग्रेज़ी में लिखें।',submit:'प्रमाण की जाँच करें',loading:'स्रोतों की जाँच हो रही है…',presets:'एक दावा आज़माएँ',examples:existingCopy.en.examples,scope:'स्रोतों का दायरा',available:'स्रोत खोज के लिए तैयार',unavailable:'स्रोत तैयार किए जा रहे हैं',inferenceReady:'अर्थगत मूल्यांकन उपलब्ध',inferenceUnavailable:'अर्थगत मूल्यांकन अभी उपलब्ध नहीं',coverageNote:'वास्तविक दायरा दिखाया जाता है। हम सभी इस्लामी स्रोतों में खोज करने का दावा नहीं करते।',first:'पाठ खोजें',firstNote:'केवल स्वीकृत स्रोतों में',second:'उद्धरण जाँचें',secondNote:'पाठ, स्थान और संस्करण',third:'संबंध की जाँच करें',thirdNote:'स्पष्ट सीमाओं के साथ अर्थगत मूल्यांकन',result:'जाँच का रिकॉर्ड',evidence:'प्राप्त पाठ',noEvidence:'इस दावे के लिए कोई पाठ नहीं मिला। इससे दावा सही या गलत सिद्ध नहीं होता।',integrityPass:'उद्धरण की शुद्धता: जाँच सफल',integrityFail:'उद्धरण की शुद्धता: जाँच असफल',source:'स्रोत खोलें',details:'स्थान और जाँच का विवरण',limitations:'इस परिणाम की सीमाएँ',notFatwa:'यह प्रमाण तक पहुँचने का साधन है; फ़तवा या स्वतंत्र हदीस प्रमाणीकरण नहीं।',emptyTitle:'प्रमाण को सामने आने दें।',emptyNote:'जाँच के बाद परिणाम, मूल पाठ और उसका स्थान यहाँ दिखेंगे। पहले से तैयार परिणाम नहीं हैं।',error:'जाँच पूरी नहीं हो सकी। फिर प्रयास करें।',langs:'प्रदर्शन की भाषाएँ',beta:'मसौदा · स्वतंत्र भाषाई समीक्षा नहीं हुई',record:'रिकॉर्ड पहचान',seal:'रिकॉर्ड की पहचान-छाप',relationship:'अर्थगत संबंध',human:'विशेषज्ञ समीक्षा',technical:'तकनीकी सत्यापन',translation:'भाषाई समीक्षा',supported:'चयनित स्रोत-संग्रह में समर्थित',conflicting:'चयनित स्रोत-संग्रह से विरोध',insufficient:'उपलब्ध प्रमाण अपर्याप्त',notEvaluated:'अर्थगत मूल्यांकन नहीं हुआ',disclaimer:'सही उद्धरण मिलना अपने आप दावे की व्याख्या को सही सिद्ध नहीं करता।'
};
const ur: DisplayCopy = {
 subtitle:'پہلے دلیل، پھر تشریح۔',nav:'عدسہ کیسے کام کرتا ہے',eyebrow:'دعووں کی جانچ کے لیے پُرسکون جگہ',title:'ایک دعوے سے،',title2:'قابلِ سراغ ماخذ تک۔',intro:'عربی یا انگریزی میں دعویٰ لکھیں۔ متعلقہ متن تلاش کریں، اقتباس کی صحت جانچیں، اور سمجھیں کہ دلیل کس بات کی تائید کرتی ہے اور کیا غیر طے شدہ رہتا ہے۔',inputTitle:'آپ کس دعوے کی جانچ کرنا چاہتے ہیں؟',inputHint:'ایک واضح بیان سے آغاز کریں۔ نتائج صرف یہاں دستیاب ماخذوں پر لاگو ہوتے ہیں۔',placeholder:'دعویٰ عربی یا انگریزی میں لکھیں۔',submit:'دلیل کی جانچ کریں',loading:'ماخذوں کی جانچ جاری ہے…',presets:'ایک دعویٰ آزمائیں',examples:existingCopy.en.examples,scope:'ماخذوں کا دائرہ',available:'ماخذ تلاش کے لیے تیار ہے',unavailable:'ماخذ تیار کیے جا رہے ہیں',inferenceReady:'معنوی جائزہ دستیاب ہے',inferenceUnavailable:'معنوی جائزہ فی الحال دستیاب نہیں',coverageNote:'اصل دائرۂ کار دکھایا جاتا ہے۔ ہم تمام اسلامی ماخذوں میں تلاش کا دعویٰ نہیں کرتے۔',first:'متن تلاش کریں',firstNote:'صرف قبول شدہ ماخذوں میں',second:'اقتباس کی جانچ کریں',secondNote:'متن، مقام اور نسخہ',third:'تعلق کا جائزہ لیں',thirdNote:'واضح حدود کے ساتھ معنوی جائزہ',result:'جانچ کا ریکارڈ',evidence:'حاصل شدہ متون',noEvidence:'اس دعوے کے لیے کوئی متن حاصل نہیں ہوا۔ اس سے دعویٰ درست یا غلط ثابت نہیں ہوتا۔',integrityPass:'اقتباس کی صحت: جانچ کامیاب',integrityFail:'اقتباس کی صحت: جانچ ناکام',source:'ماخذ کھولیں',details:'مقام اور جانچ کی تفصیلات',limitations:'اس نتیجے کی حدود',notFatwa:'یہ دلائل تک رسائی کا آلہ ہے؛ فتویٰ یا حدیث کی آزادانہ تصحیح نہیں۔',emptyTitle:'دلیل کو سامنے آنے دیں۔',emptyNote:'جانچ کے بعد نتیجہ، اصل متن اور اس کا مقام یہاں دکھائے جائیں گے۔ پہلے سے تیار نتائج نہیں ہیں۔',error:'جانچ مکمل نہیں ہو سکی۔ دوبارہ کوشش کریں۔',langs:'نمایش کی زبانیں',beta:'مسودہ · آزادانہ لسانی نظرثانی نہیں ہوئی',record:'ریکارڈ کی شناخت',seal:'ریکارڈ کا نشان',relationship:'معنوی تعلق',human:'علمی نظرثانی',technical:'تکنیکی تصدیق',translation:'لسانی نظرثانی',supported:'منتخب ماخذوں کے اندر تائید حاصل ہے',conflicting:'منتخب ماخذوں سے متعارض ہے',insufficient:'دستیاب دلیل ناکافی ہے',notEvaluated:'معنوی جائزہ نہیں لیا گیا',disclaimer:'درست اقتباس ملنا بذاتِ خود دعوے کی تشریح کو درست ثابت نہیں کرتا۔'
};
const id: DisplayCopy = {
 subtitle:'Bukti dahulu. Penafsiran kemudian.',nav:'Cara kerja lensa',eyebrow:'Ruang tenang untuk memeriksa klaim',title:'Dari sebuah klaim,',title2:'menuju sumber yang dapat ditelusuri.',intro:'Tulis klaim dalam bahasa Arab atau Inggris. Temukan teks terkait, periksa keutuhan kutipan, dan pahami apa yang didukung bukti serta apa yang belum terjawab.',inputTitle:'Klaim apa yang ingin Anda periksa?',inputHint:'Mulai dengan satu pernyataan jelas. Hasil hanya berlaku untuk sumber yang tersedia di sini.',placeholder:'Tulis klaim dalam bahasa Arab atau Inggris.',submit:'Periksa bukti',loading:'Memeriksa sumber…',presets:'Coba sebuah klaim',examples:existingCopy.en.examples,scope:'Cakupan sumber',available:'Sumber siap ditelusuri',unavailable:'Sumber sedang disiapkan',inferenceReady:'Penilaian makna tersedia',inferenceUnavailable:'Penilaian makna belum tersedia',coverageNote:'Cakupan sebenarnya ditampilkan. Kami tidak mengklaim menelusuri seluruh sumber Islam.',first:'Temukan teks',firstNote:'Hanya dalam sumber yang diterima',second:'Periksa kutipan',secondNote:'Teks, lokasi, dan edisi',third:'Periksa hubungan',thirdNote:'Penilaian makna dengan batas yang jelas',result:'Catatan pemeriksaan',evidence:'Teks yang ditemukan',noEvidence:'Tidak ada teks yang ditemukan untuk klaim ini. Ini tidak membuktikan bahwa klaim benar atau salah.',integrityPass:'Keutuhan kutipan: lolos pemeriksaan',integrityFail:'Keutuhan kutipan: gagal pemeriksaan',source:'Buka sumber',details:'Lokasi dan rincian pemeriksaan',limitations:'Batas hasil ini',notFatwa:'Alat untuk menelusuri bukti, bukan fatwa atau autentikasi hadis secara mandiri.',emptyTitle:'Biarkan bukti tampil.',emptyNote:'Hasil, teks asli, dan lokasinya tampil setelah pemeriksaan. Tidak ada hasil yang sudah disiapkan.',error:'Pemeriksaan tidak dapat diselesaikan. Silakan coba lagi.',langs:'Bahasa tampilan',beta:'Draf · belum ditinjau secara linguistik oleh pihak independen',record:'ID catatan',seal:'Sidik catatan',relationship:'Hubungan makna',human:'Tinjauan keilmuan',technical:'Verifikasi teknis',translation:'Tinjauan linguistik',supported:'Didukung dalam kumpulan sumber terpilih',conflicting:'Bertentangan dengan kumpulan sumber terpilih',insufficient:'Bukti yang tersedia tidak cukup',notEvaluated:'Penilaian makna belum dilakukan',disclaimer:'Kutipan yang terverifikasi saja tidak membuktikan bahwa penafsiran klaim benar.'
};

export const displayCopy: Readonly<Record<DisplayLanguage, DisplayCopy>> = {
 ar: {...existingCopy.ar, beta:'مسودة عرض · لم تُراجع لغوياً بشكل مستقل'},
 en: {...existingCopy.en, beta:'Display draft · not independently linguistically reviewed'}, bn,hi,ur,id
};
export const displayLanguageMetadata = {
 ar:{nativeName:'العربية',direction:'rtl',reviewStatus:'not_independently_reviewed',draft:true,claimInputSupported:true},
 en:{nativeName:'English',direction:'ltr',reviewStatus:'not_independently_reviewed',draft:true,claimInputSupported:true},
 bn:{nativeName:'বাংলা',direction:'ltr',reviewStatus:'not_independently_reviewed',draft:true,claimInputSupported:false},
 hi:{nativeName:'हिन्दी',direction:'ltr',reviewStatus:'not_independently_reviewed',draft:true,claimInputSupported:false},
 ur:{nativeName:'اردو',direction:'rtl',reviewStatus:'not_independently_reviewed',draft:true,claimInputSupported:false},
 id:{nativeName:'Bahasa Indonesia',direction:'ltr',reviewStatus:'not_independently_reviewed',draft:true,claimInputSupported:false}
} as const;
/** Display language does not change the input language or rerun verification. */
export function isClaimInputLanguage(language:DisplayLanguage): language is ClaimInputLanguage { return language==='ar'||language==='en'; }

