import type {ClaimLanguage} from './claim-language';
const labels:Record<ClaimLanguage,string[]>={
 en:['Image input','Choose an image','Read image','Reading…','Review the extracted text','Use this claim','Remove image','Reading unavailable. Try a clearer image or type.','Image preview','Choose or paste a PNG, JPEG or WebP, up to 10 MB. Google receives it only when you press Read image; the free service may use it to improve products. Remove private information first.','Check the wording before verification. Image reading does not establish authenticity or truth.','Select a claim','Visible text','Image reading is unavailable. You can still type.','Reading is uncertain. Check against the image or upload a clearer crop.','No readable text found. Type the claim you want checked.'],
 ar:['إدخال صورة','اختر صورة','اقرأ الصورة','جارٍ القراءة…','راجع النص المستخرج','استخدم الادعاء','احذف الصورة','تعذرت القراءة. جرّب صورة أوضح أو اكتب.','معاينة الصورة','اختر أو الصق PNG أو JPEG أو WebP حتى 10 ميغابايت. تُرسل إلى Google فقط عند ضغط اقرأ الصورة، وقد تستخدمها الخدمة المجانية لتحسين منتجاتها. احذف المعلومات الخاصة أولاً.','راجع النص قبل التحقق. قراءة الصورة لا تثبت أصالتها أو صحة الادعاء.','اختر ادعاءً','النص الظاهر','قراءة الصور غير متاحة. يمكنك الكتابة.','القراءة غير مؤكدة. قارن بالصورة أو أرسل جزءاً أوضح.','لم يُعثر على نص مقروء. اكتب الادعاء المطلوب فحصه.'],
 bn:['ছবি ইনপুট','ছবি বেছে নিন','ছবি পড়ুন','পড়া হচ্ছে…','উদ্ধার করা পাঠ যাচাই করুন','এই দাবি ব্যবহার করুন','ছবি সরান','পড়া যায়নি। পরিষ্কার ছবি দিন বা লিখুন।','ছবির পূর্বরূপ','PNG, JPEG বা WebP বেছে নিন বা পেস্ট করুন, সর্বোচ্চ 10 MB। পড়ুন চাপলেই Google-এ যায়; বিনামূল্যের পরিষেবা পণ্য উন্নয়নে ব্যবহার করতে পারে। আগে ব্যক্তিগত তথ্য সরান।','যাচাইয়ের আগে শব্দ দেখুন। ছবি পড়া সত্যতা প্রমাণ করে না।','দাবি বেছে নিন','দৃশ্যমান পাঠ','ছবি পড়া অনুপলব্ধ। লিখতে পারেন।','পাঠ অনিশ্চিত। ছবির সঙ্গে মিলিয়ে দেখুন বা পরিষ্কার অংশ দিন।','পাঠ পাওয়া যায়নি। যে দাবি যাচাই চান তা লিখুন।'],
 hi:['चित्र इनपुट','चित्र चुनें','चित्र पढ़ें','पढ़ रहे हैं…','निकाला गया पाठ जाँचें','यह दावा इस्तेमाल करें','चित्र हटाएँ','पढ़ नहीं पाए। साफ़ चित्र दें या लिखें।','चित्र पूर्वावलोकन','PNG, JPEG या WebP चुनें या पेस्ट करें, अधिकतम 10 MB। पढ़ें दबाने पर ही Google को भेजा जाता है; निःशुल्क सेवा उत्पाद सुधार के लिए इस्तेमाल कर सकती है। निजी जानकारी पहले हटाएँ।','सत्यापन से पहले शब्द जाँचें। चित्र पढ़ना प्रामाणिकता या सत्य साबित नहीं करता।','दावा चुनें','दिखाई देने वाला पाठ','चित्र पढ़ना उपलब्ध नहीं। आप लिख सकते हैं।','पाठ अनिश्चित है। चित्र से मिलाएँ या साफ़ हिस्सा दें।','पढ़ने योग्य पाठ नहीं मिला। जाँचने का दावा लिखें।'],
 ur:['تصویر سے متن','تصویر چنیں','تصویر پڑھیں','پڑھ رہے ہیں…','نکالا گیا متن دیکھیں','یہ دعویٰ استعمال کریں','تصویر ہٹائیں','پڑھ نہیں سکے۔ واضح تصویر دیں یا لکھیں۔','تصویر کا منظر','PNG، JPEG یا WebP چنیں یا پیسٹ کریں، زیادہ سے زیادہ 10 MB۔ پڑھیں دبانے پر ہی Google کو بھیجی جاتی ہے؛ مفت سروس اسے مصنوعات بہتر بنانے میں استعمال کر سکتی ہے۔ پہلے نجی معلومات ہٹائیں۔','تصدیق سے پہلے الفاظ دیکھیں۔ تصویر پڑھنا اصلیت یا سچ ثابت نہیں کرتا۔','دعویٰ چنیں','نظر آنے والا متن','تصویر پڑھنا دستیاب نہیں۔ لکھ سکتے ہیں۔','متن غیر یقینی ہے۔ تصویر سے ملائیں یا واضح حصہ دیں۔','قابلِ مطالعہ متن نہیں ملا۔ مطلوبہ دعویٰ لکھیں۔'],
 id:['Masukan gambar','Pilih gambar','Baca gambar','Membaca…','Tinjau teks yang dibaca','Gunakan klaim ini','Hapus gambar','Gagal membaca. Coba gambar lebih jelas atau ketik.','Pratinjau gambar','Pilih atau tempel PNG, JPEG, WebP hingga 10 MB. Google menerimanya hanya setelah Baca gambar; layanan gratis dapat memakainya untuk meningkatkan produk. Hapus informasi pribadi dahulu.','Periksa kata-kata sebelum verifikasi. Pembacaan gambar tidak membuktikan keaslian atau kebenaran.','Pilih klaim','Teks terlihat','Pembacaan gambar tidak tersedia. Anda bisa mengetik.','Pembacaan tidak pasti. Cocokkan dengan gambar atau unggah potongan lebih jelas.','Tidak ada teks terbaca. Ketik klaim yang ingin diperiksa.'],
 es:['Entrada de imagen','Elegir imagen','Leer imagen','Leyendo…','Revisar el texto extraído','Usar esta afirmación','Quitar imagen','No se pudo leer. Prueba una imagen más clara o escribe.','Vista previa','Elige o pega PNG, JPEG o WebP de hasta 10 MB. Google la recibe solo al pulsar Leer imagen; el servicio gratuito puede usarla para mejorar productos. Elimina los datos privados primero.','Revisa las palabras antes de verificar. Leer la imagen no demuestra autenticidad ni verdad.','Elegir afirmación','Texto visible','Lectura de imágenes no disponible. Puedes escribir.','Lectura incierta. Compara con la imagen o carga un recorte más claro.','No hay texto legible. Escribe la afirmación que quieres comprobar.'],
 fr:['Saisie par image','Choisir une image','Lire l’image','Lecture…','Relire le texte extrait','Utiliser cette affirmation','Retirer l’image','Lecture impossible. Essayez une image plus nette ou écrivez.','Aperçu','Choisissez ou collez un PNG, JPEG ou WebP, jusqu’à 10 Mo. Google reçoit l’image seulement après Lire l’image ; le service gratuit peut l’utiliser pour améliorer ses produits. Retirez les données privées avant.','Vérifiez les mots avant l’examen. La lecture ne prouve ni authenticité ni vérité.','Choisir une affirmation','Texte visible','Lecture indisponible. Vous pouvez écrire.','Lecture incertaine. Comparez à l’image ou envoyez un extrait plus net.','Aucun texte lisible. Écrivez l’affirmation à examiner.'],
 de:['Bildeingabe','Bild auswählen','Bild lesen','Wird gelesen…','Erkannten Text prüfen','Diese Aussage verwenden','Bild entfernen','Lesen fehlgeschlagen. Klareres Bild versuchen oder tippen.','Bildvorschau','PNG, JPEG oder WebP bis 10 MB auswählen oder einfügen. Google erhält es erst bei Bild lesen; der kostenlose Dienst kann es zur Produktverbesserung verwenden. Private Angaben vorher entfernen.','Wortlaut vor der Prüfung kontrollieren. Bilderkennung beweist weder Echtheit noch Wahrheit.','Aussage wählen','Sichtbarer Text','Bilderkennung nicht verfügbar. Sie können tippen.','Lesen unsicher. Mit dem Bild vergleichen oder einen klareren Ausschnitt hochladen.','Kein lesbarer Text. Die zu prüfende Aussage eingeben.']
};
export const imageCopy=(language:ClaimLanguage)=>labels[language];
export const imageQuotaCopy:Record<ClaimLanguage,string>={en:'The free reader is busy or at its quota. Try later or type the claim.',ar:'القارئ المجاني مشغول أو بلغ الحد المسموح. جرّب لاحقاً أو اكتب الادعاء.',bn:'বিনামূল্যের পাঠক ব্যস্ত বা সীমায় পৌঁছেছে। পরে চেষ্টা করুন বা দাবি লিখুন।',hi:'निःशुल्क पाठक व्यस्त है या सीमा पूरी हो गई। बाद में प्रयास करें या दावा लिखें।',ur:'مفت قاری مصروف ہے یا حد پوری ہو گئی۔ بعد میں کوشش کریں یا دعویٰ لکھیں۔',id:'Pembaca gratis sibuk atau mencapai kuota. Coba nanti atau ketik klaim.',es:'El lector gratuito está ocupado o agotó su cuota. Inténtalo más tarde o escribe.',fr:'Le lecteur gratuit est occupé ou son quota est atteint. Réessayez plus tard ou écrivez.',de:'Der kostenlose Leser ist ausgelastet oder hat sein Kontingent erreicht. Später versuchen oder tippen.'};
