import type {DisplayLanguage} from './display-copy';

// Interface text only: publisher quotations, names, licences and audit data stay verbatim.
const languages = ['bn','hi','ur','id','es','fr','de'] as const;
export const interfaceTranslations:Record<string,string[]> = {
 'Excerpt':['উদ্ধৃতাংশ','अंश','اقتباس','Kutipan','Extracto','Extrait','Auszug'],
 'Published translation · excerpt · English':['প্রকাশিত অনুবাদ · অংশ · ইংরেজি','प्रकाशित अनुवाद · अंश · अंग्रेज़ी','شائع شدہ ترجمہ · اقتباس · انگریزی','Terjemahan terbitan · kutipan · Inggris','Traducción publicada · extracto · inglés','Traduction publiée · extrait · anglais','Veröffentlichte Übersetzung · Auszug · Englisch'],
 'Read full verse':['সম্পূর্ণ আয়াত পড়ুন','पूरी आयत पढ़ें','مکمل آیت پڑھیں','Baca ayat lengkap','Leer aleya completa','Lire le verset entier','Ganzen Vers lesen'],
 'Decision and trust':['সিদ্ধান্ত ও ভরসা','निर्णय और भरोसा','فیصلہ اور توکل','Keputusan dan tawakal','Decisión y confianza','Décision et confiance','Entscheidung und Vertrauen'],
 'Consultation, then decision':['পরামর্শ, তারপর সিদ্ধান্ত','परामर्श, फिर निर्णय','مشورہ، پھر فیصلہ','Musyawarah, lalu keputusan','Consulta y después decisión','Consultation, puis décision','Beratung, dann Entscheidung'],
 'Full source and example details':['সম্পূর্ণ উৎস ও উদাহরণের বিবরণ','पूरा स्रोत और उदाहरण विवरण','مکمل ماخذ اور مثال کی تفصیل','Sumber lengkap dan detail contoh','Fuente completa y detalles del ejemplo','Source complète et détails de l’exemple','Vollständige Quelle und Beispieldetails'],
 'This example displays a curated explanation and verbatim excerpts, using evidence retained from an earlier assessment. Opening it makes no AI call.':['এই উদাহরণে আগের মূল্যায়নের সংরক্ষিত প্রমাণ থেকে প্রস্তুত ব্যাখ্যা ও হুবহু উদ্ধৃতি দেখানো হয়েছে। এটি খুললে AI কল হয় না।','यह उदाहरण पिछले मूल्यांकन के सुरक्षित साक्ष्य से तैयार व्याख्या और अक्षरशः अंश दिखाता है। इसे खोलने पर AI कॉल नहीं होती।','اس مثال میں سابقہ جائزے کے محفوظ شواہد سے مرتب وضاحت اور لفظ بہ لفظ اقتباسات ہیں۔ اسے کھولنے پر AI کال نہیں ہوتی۔','Contoh ini menampilkan penjelasan terkurasi dan kutipan persis dari bukti penilaian sebelumnya. Membukanya tidak memanggil AI.','Este ejemplo muestra una explicación preparada y extractos literales de pruebas de una evaluación anterior. Abrirlo no realiza llamadas de IA.','Cet exemple présente une explication préparée et des extraits exacts issus d’une évaluation antérieure. Son ouverture ne lance aucun appel IA.','Dieses Beispiel zeigt eine kuratierte Erklärung und wörtliche Auszüge aus einer früheren Bewertung. Beim Öffnen erfolgt kein KI-Aufruf.'],
 'Mishary Rashid Alafasy · full verse':['মিশারি রাশিদ আলাফাসি · সম্পূর্ণ আয়াত','मिशारी राशिद अलअफ़ासी · पूरी आयत','مشاری راشد العفاسی · مکمل آیت','Mishary Rashid Alafasy · ayat lengkap','Mishary Rashid Alafasy · aleya completa','Mishary Rashid Alafasy · verset entier','Mishary Rashid Alafasy · ganzer Vers'],
 'Recitation could not load. Tap to try again.':['তিলাওয়াত লোড হয়নি। আবার চেষ্টা করুন।','तिलावत लोड नहीं हुई। फिर कोशिश करें।','تلاوت لوڈ نہیں ہوئی۔ دوبارہ کوشش کریں۔','Tilawah gagal dimuat. Ketuk untuk mencoba lagi.','No se pudo cargar la recitación. Pulsa para reintentar.','La récitation n’a pas pu être chargée. Appuyez pour réessayer.','Rezitation konnte nicht geladen werden. Zum Wiederholen antippen.'],
 'The PDF could not download. Please try again.':['PDF ডাউনলোড হয়নি। আবার চেষ্টা করুন।','PDF डाउनलोड नहीं हुआ। फिर कोशिश करें।','PDF ڈاؤن لوڈ نہیں ہوا۔ دوبارہ کوشش کریں۔','PDF tidak dapat diunduh. Coba lagi.','No se pudo descargar el PDF. Inténtalo de nuevo.','Le PDF n’a pas pu être téléchargé. Réessayez.','Das PDF konnte nicht heruntergeladen werden. Bitte erneut versuchen.'],
 'Details':['বিবরণ','विवरण','تفصیل','Detail','Detalles','Détails','Details'],
 'Select source corpus':['উৎসের সংগ্রহ বেছে নিন','स्रोत संग्रह चुनें','ماخذ کا مجموعہ منتخب کریں','Pilih kumpulan sumber','Seleccionar colección de fuentes','Choisir le corpus','Quellensammlung wählen'],
 'verses':['আয়াত','आयतें','آیات','ayat','aleyas','versets','Verse'],
 'records':['রেকর্ড','अभिलेख','ریکارڈ','catatan','registros','entrées','Einträge'],
 'Available source languages':['উৎসের উপলব্ধ ভাষা','उपलब्ध स्रोत भाषाएँ','ماخذ کی دستیاب زبانیں','Bahasa sumber tersedia','Idiomas de fuentes disponibles','Langues des sources disponibles','Verfügbare Quellensprachen'],
 'Translation coverage varies by language; not every hadith has every translation. Hadith grades are supplied by the publisher, not independently authenticated here.':['ভাষাভেদে অনুবাদের পরিসর আলাদা; সব হাদিসের সব অনুবাদ নেই। হাদিসের মান প্রকাশকের দেওয়া, এখানে স্বাধীনভাবে নির্ধারিত নয়।','अनुवाद की उपलब्धता भाषा के अनुसार बदलती है; हर हदीस का हर अनुवाद नहीं है। हदीस की श्रेणी प्रकाशक की है, यहाँ स्वतंत्र प्रमाणन नहीं होता।','ترجمے کی دستیابی زبان کے لحاظ سے مختلف ہے؛ ہر حدیث کا ہر ترجمہ نہیں۔ حدیث کا درجہ ناشر کا ہے، یہاں آزاد تصحیح نہیں ہوتی۔','Cakupan terjemahan berbeda menurut bahasa; tidak semua hadis memiliki setiap terjemahan. Derajat hadis berasal dari penerbit, bukan autentikasi independen di sini.','La cobertura varía por idioma; no todos los hadices tienen todas las traducciones. Las clasificaciones son del editor, sin autenticación independiente aquí.','La couverture varie selon la langue ; chaque hadith n’a pas toutes les traductions. Les classifications proviennent de l’éditeur, sans authentification indépendante ici.','Der Übersetzungsumfang variiert je Sprache. Nicht jeder Hadith hat jede Übersetzung. Einstufungen stammen vom Herausgeber, ohne unabhängige Authentifizierung hier.'],
 'Publisher hadith grade':['প্রকাশকের হাদিসের মান','प्रकाशक का हदीस वर्गीकरण','ناشر کا حدیث پر حکم','Derajat hadis dari penerbit','Clasificación del hadiz del editor','Classification du hadith par l’éditeur','Hadith-Einstufung des Herausgebers'],
 'Text licence':['পাঠের লাইসেন্স','पाठ लाइसेंस','متن کا لائسنس','Lisensi teks','Licencia del texto','Licence du texte','Textlizenz'],
 'Copyright and source notices':['কপিরাইট ও উৎসের নোটিশ','कॉपीराइट और स्रोत सूचनाएँ','حقوق اشاعت اور ماخذ کی اطلاعات','Hak cipta dan pemberitahuan sumber','Avisos de derechos y fuentes','Droits d’auteur et mentions des sources','Urheberrecht und Quellenhinweise'],
 'Search details':['অনুসন্ধানের বিবরণ','खोज विवरण','تلاش کی تفصیل','Detail pencarian','Detalles de búsqueda','Détails de recherche','Suchdetails'],
 'No model evaluation':['মডেল মূল্যায়ন নেই','मॉडल मूल्यांकन नहीं','ماڈل کا جائزہ نہیں','Tanpa penilaian model','Sin evaluación del modelo','Aucune évaluation du modèle','Keine Modellbewertung'],
 'Read context: preceding and following verses':['প্রসঙ্গ পড়ুন: আগের ও পরের আয়াত','संदर्भ पढ़ें: पिछली और अगली आयतें','سیاق پڑھیں: پچھلی اور اگلی آیات','Baca konteks: ayat sebelum dan sesudah','Leer contexto: aleyas anterior y siguiente','Lire le contexte : versets précédent et suivant','Kontext lesen: vorheriger und folgender Vers'],
 'Neighbouring text from the same source provides context; it is not an independent verdict on the claim.':['একই উৎসের আশেপাশের পাঠ প্রসঙ্গ দেয়; এটি দাবির স্বাধীন রায় নয়।','उसी स्रोत का आसपास का पाठ संदर्भ देता है; यह दावे पर स्वतंत्र निर्णय नहीं है।','اسی ماخذ کا آس پاس کا متن سیاق دیتا ہے؛ دعوے پر الگ حکم نہیں۔','Teks sekitar dari sumber yang sama memberi konteks, bukan putusan independen atas klaim.','El texto cercano de la misma fuente aporta contexto, no un veredicto independiente.','Les passages voisins de la même source apportent du contexte, pas un verdict indépendant.','Benachbarter Text derselben Quelle liefert Kontext, kein unabhängiges Urteil zur Behauptung.'],
 'Preceding verse':['আগের আয়াত','पिछली आयत','پچھلی آیت','Ayat sebelumnya','Aleya anterior','Verset précédent','Vorheriger Vers'],
 'Following verse':['পরের আয়াত','अगली आयत','اگلی آیت','Ayat berikutnya','Aleya siguiente','Verset suivant','Folgender Vers'],
 '✓ Matches admitted source text':['✓ গৃহীত উৎসের পাঠের সঙ্গে মেলে','✓ स्वीकृत स्रोत पाठ से मेल खाता है','✓ منظور شدہ ماخذ سے مطابق','✓ Cocok dengan teks sumber yang diterima','✓ Coincide con el texto admitido','✓ Correspond au texte source admis','✓ Stimmt mit dem zugelassenen Quellentext überein'],
 'Integrity check failed':['অখণ্ডতার পরীক্ষা ব্যর্থ','अखंडता जाँच विफल','سالمیت کی جانچ ناکام','Pemeriksaan integritas gagal','Falló la comprobación de integridad','Échec du contrôle d’intégrité','Integritätsprüfung fehlgeschlagen'],
 'Original publisher fields · not model grading':['প্রকাশকের মূল তথ্য · মডেলের মান নির্ধারণ নয়','प्रकाशक के मूल फ़ील्ड · मॉडल का वर्गीकरण नहीं','ناشر کے اصل خانے · ماڈل کا حکم نہیں','Bidang asli penerbit · bukan penilaian model','Datos originales del editor · no clasificación del modelo','Champs originaux de l’éditeur · pas une classification du modèle','Originale Herausgeberfelder · keine Modelleinstufung'],
 'Fields are displayed unchanged in the publisher language. These are not independent authentication or scholarly review by IsnadLens.':['তথ্য প্রকাশকের ভাষায় অপরিবর্তিত দেখানো হয়েছে। এটি IsnadLens-এর স্বাধীন সত্যায়ন বা আলেমের পর্যালোচনা নয়।','फ़ील्ड प्रकाशक की भाषा में बिना बदलाव दिखते हैं। यह IsnadLens का स्वतंत्र प्रमाणन या विद्वत समीक्षा नहीं है।','خانے ناشر کی زبان میں بغیر تبدیلی ہیں۔ یہ IsnadLens کی آزاد تصحیح یا علمی مراجعت نہیں۔','Bidang ditampilkan tanpa perubahan dalam bahasa penerbit. Ini bukan autentikasi independen atau tinjauan ulama oleh IsnadLens.','Los datos se muestran sin cambios en el idioma del editor. No constituyen autenticación independiente ni revisión erudita de IsnadLens.','Les champs restent inchangés dans la langue de l’éditeur. Ils ne constituent pas une authentification indépendante ni une révision savante par IsnadLens.','Felder bleiben in der Sprache des Herausgebers unverändert. Sie sind keine unabhängige Authentifizierung oder wissenschaftliche Prüfung durch IsnadLens.'],
 'Publisher takhrij':['প্রকাশকের তাখরিজ','प्रकाशक का तख़रीज','ناشر کی تخریج','Takhrij penerbit','Takhrij del editor','Takhrij de l’éditeur','Takhrij des Herausgebers'],
 'Publisher explanation':['প্রকাশকের ব্যাখ্যা','प्रकाशक की व्याख्या','ناشر کی تشریح','Penjelasan penerbit','Explicación del editor','Explication de l’éditeur','Erklärung des Herausgebers'],
 'Publisher benefits':['প্রকাশকের শিক্ষণীয় বিষয়','प्रकाशक के लाभ','ناشر کے فوائد','Faedah penerbit','Enseñanzas del editor','Enseignements de l’éditeur','Lehren des Herausgebers'],
 'Publisher reference':['প্রকাশকের তথ্যসূত্র','प्रकाशक का संदर्भ','ناشر کا حوالہ','Referensi penerbit','Referencia del editor','Référence de l’éditeur','Referenz des Herausgebers'],
 'Original hadith text':['হাদিসের মূল পাঠ','मूल हदीस पाठ','حدیث کا اصل متن','Teks hadis asli','Texto original del hadiz','Texte original du hadith','Originaler Hadithtext'],
 'Publisher word meanings':['প্রকাশকের শব্দার্থ','प्रकाशक के शब्दार्थ','ناشر کے لفظی معانی','Arti kata penerbit','Significados del editor','Sens des mots de l’éditeur','Wortbedeutungen des Herausgebers'],
 'Publisher title':['প্রকাশকের শিরোনাম','प्रकाशक का शीर्षक','ناشر کا عنوان','Judul penerbit','Título del editor','Titre de l’éditeur','Titel des Herausgebers'],
 'Publisher ID':['প্রকাশকের আইডি','प्रकाशक ID','ناشر کی شناخت','ID penerbit','ID del editor','Identifiant de l’éditeur','Herausgeber-ID'],
 'Publisher link':['প্রকাশকের লিংক','प्रकाशक लिंक','ناشر کا ربط','Tautan penerbit','Enlace del editor','Lien de l’éditeur','Herausgeberlink'],
 'Please wait {seconds} seconds before trying again.':['আবার চেষ্টা করার আগে {seconds} সেকেন্ড অপেক্ষা করুন।','फिर प्रयास करने से पहले {seconds} सेकंड प्रतीक्षा करें।','دوبارہ کوشش سے پہلے {seconds} سیکنڈ انتظار کریں۔','Tunggu {seconds} detik sebelum mencoba lagi.','Espera {seconds} segundos antes de reintentar.','Patientez {seconds} secondes avant de réessayer.','Vor dem nächsten Versuch {seconds} Sekunden warten.'],
 'This request took too long. Your question is kept; try again later.':['অনুরোধে বেশি সময় লেগেছে। প্রশ্ন রাখা আছে; পরে চেষ্টা করুন।','अनुरोध में अधिक समय लगा। आपका प्रश्न सुरक्षित है; बाद में प्रयास करें।','درخواست میں زیادہ وقت لگا۔ سوال محفوظ ہے؛ بعد میں کوشش کریں۔','Permintaan terlalu lama. Pertanyaan tetap tersimpan; coba lagi nanti.','La solicitud tardó demasiado. Conservamos tu pregunta; reintenta más tarde.','La demande a pris trop de temps. Votre question est conservée ; réessayez plus tard.','Die Anfrage dauerte zu lange. Die Frage bleibt erhalten; später erneut versuchen.'],
};
export function interfaceText(language:DisplayLanguage,arabic:string,english:string):string {
 if(language==='ar')return arabic;
 if(language==='en')return english;
 return interfaceTranslations[english]?.[languages.indexOf(language)]??english;
}
