import type {DisplayLanguage} from './display-copy';
import type {JourneyItem} from './pilgrimage-journey';
const languages=['bn','hi','ur','id','es','fr','de'] as const;
// Learning prompts, not religious answers. Original source references are preserved.
const labels:Record<string,string[]>={
 ihram:['ইহরাম ও নিয়ত','इहराम और नीयत','احرام اور نیت','Ihram & niat','Ihram e intención','Ihram et intention','Ihram und Absicht'],
 tawaf:['তাওয়াফ','तवाफ़','طواف','Tawaf','Tawaf','Tawaf','Tawaf'],
 sai:['সাঈ · সাফা ও মারওয়া','सई · सफ़ा और मरवा','سعی · صفا اور مروہ','Sai · Safa & Marwah','Sai · Safa y Marwa','Saï · Safa et Marwa','Sai · Safa und Marwa'],
 completion:['চুল মুণ্ডন বা ছোট করা','बाल मुंडवाना या छोटे करना','حلق یا بال چھوٹے کرنا','Mencukur atau memendekkan rambut','Afeitar o recortar el cabello','Raser ou raccourcir les cheveux','Haare rasieren oder kürzen'],
 forms:['তামাত্তু, কিরান ও ইফরাদ','तमत्तु, क़िरान और इफ़राद','تمتع، قران اور افراد','Tamattu, Qiran & Ifrad','Tamattu, Qiran e Ifrad','Tamattu, Qiran et Ifrad','Tamattu, Qiran und Ifrad'],
 mina:['মিনা','मिना','منیٰ','Mina','Mina','Mina','Mina'],
 arafah:['আরাফা','अरफ़ा','عرفات','Arafah','Arafat','Arafat','Arafat'],
 muzdalifah:['মুযদালিফা','मुज़दलिफ़ा','مزدلفہ','Muzdalifah','Muzdalifa','Muzdalifa','Muzdalifa'],
 jamarat:['জামারাত','जमरात','جمرات','Jamarat','Yamarat','Jamarat','Dschamarat'],
 ifada:['তাওয়াফে ইফাদা','तवाफ़ अल-इफ़ादा','طوافِ افاضہ','Tawaf Ifadah','Tawaf al-Ifada','Tawaf al-Ifada','Tawaf al-Ifada'],
 farewell:['বিদায়ী তাওয়াফ','विदाई तवाफ़','طوافِ وداع','Tawaf perpisahan','Tawaf de despedida','Tawaf d’adieu','Abschieds-Tawaf'],
};
const questions:Record<string,string[]>={
 ihram:['হজ ও উমরার ইহরামে প্রবেশের স্থান সম্পর্কে হাদিসের উৎসগুলো কী বলে?','हज और उमरा के इहराम में प्रवेश के स्थानों के बारे में हदीस के स्रोत क्या कहते हैं?','حج اور عمرہ کے احرام کے مقامات کے بارے میں احادیث کیا کہتی ہیں؟','Apa yang disebutkan sumber hadis tentang tempat memasuki ihram untuk Haji dan Umrah?','¿Qué dicen las fuentes de hadices sobre los lugares para entrar en ihram para el Hach y la Umra?','Que disent les sources de hadiths sur les lieux d’entrée en ihram pour le Hajj et la Omra ?','Was sagen die Hadithquellen über die Orte zum Eintritt in den Ihram für Hajj und Umra?'],
 tawaf:['তাওয়াফের চক্করের সংখ্যা সম্পর্কে হাদিস কী বলে?','तवाफ़ के चक्करों की संख्या के बारे में हदीस क्या बताती है?','طواف کے چکروں کی تعداد کے بارے میں حدیث کیا بیان کرتی ہے؟','Apa yang disebutkan hadis tentang jumlah putaran Tawaf?','¿Qué relata el hadiz sobre el número de vueltas del Tawaf?','Que rapporte le hadith sur le nombre de tours du Tawaf ?','Was berichtet der Hadith über die Anzahl der Tawaf-Runden?'],
 sai:['সাফা থেকে সাঈ শুরু ও মারওয়ায় শেষ করা সম্পর্কে হাদিসের উৎসগুলো কী বলে?','सफ़ा से सई शुरू करके मरवा पर समाप्त करने के बारे में हदीस के स्रोत क्या कहते हैं?','صفا سے سعی شروع اور مروہ پر ختم کرنے کے بارے میں احادیث کیا کہتی ہیں؟','Apa yang disebutkan hadis tentang memulai Sai di Safa dan mengakhirinya di Marwah?','¿Qué dicen los hadices sobre comenzar el Sai en Safa y terminarlo en Marwa?','Que disent les hadiths sur le début du Saï à Safa et sa fin à Marwa ?','Was sagen die Hadithe über den Beginn des Sai bei Safa und das Ende bei Marwa?'],
 completion:['হজের আনুষ্ঠানিকতার পর চুল মুণ্ডন বা ছোট করা সম্পর্কে হাদিসের উৎসগুলো কী বলে?','तीर्थयात्रा के अनुष्ठानों के बाद बाल मुंडवाने या छोटे करने के बारे में हदीस के स्रोत क्या कहते हैं?','مناسک کے بعد حلق یا بال چھوٹے کرنے کے بارے میں احادیث کیا کہتی ہیں؟','Apa yang disebutkan hadis tentang mencukur atau memendekkan rambut setelah manasik?','¿Qué dicen los hadices sobre afeitar o recortar el cabello después de los ritos de peregrinación?','Que disent les hadiths sur le rasage ou le raccourcissement des cheveux après les rites ?','Was sagen die Hadithe über das Rasieren oder Kürzen der Haare nach den Pilgerriten?'],
 forms:['হজের ধরন তামাত্তু, কিরান ও ইফরাদ সম্পর্কে হাদিসের উৎসগুলো কী বলে?','हज के प्रकार तमत्तु, क़िरान और इफ़राद के बारे में हदीस के स्रोत क्या कहते हैं?','حج کی اقسام تمتع، قران اور افراد کے بارے میں احادیث کیا کہتی ہیں؟','Apa yang disebutkan hadis tentang jenis Haji: Tamattu, Qiran dan Ifrad?','¿Qué dicen los hadices sobre las formas del Hach: Tamattu, Qiran e Ifrad?','Que disent les hadiths sur les formes du Hajj : Tamattu, Qiran et Ifrad ?','Was sagen die Hadithe über die Hajj-Formen Tamattu, Qiran und Ifrad?'],
 mina:['হজের সময় মিনায় যাওয়া সম্পর্কে হাদিস কী বলে?','हज के दौरान मिना जाने के बारे में हदीस क्या बताती है?','حج کے دوران منیٰ جانے کے بارے میں حدیث کیا بیان کرتی ہے؟','Apa yang disebutkan hadis tentang pergi ke Mina saat Haji?','¿Qué relata el hadiz sobre ir a Mina durante el Hach?','Que rapporte le hadith sur le fait de se rendre à Mina pendant le Hajj ?','Was berichtet der Hadith über den Weg nach Mina während des Hajj?'],
 arafah:['হজের সময় আরাফায় অবস্থান সম্পর্কে হাদিস কী বলে?','हज के दौरान अरफ़ा में ठहरने के बारे में हदीस क्या बताती है?','حج میں وقوفِ عرفات کے بارے میں حدیث کیا بیان کرتی ہے؟','Apa yang disebutkan hadis tentang wukuf di Arafah saat Haji?','¿Qué relata el hadiz sobre la estancia en Arafat durante el Hach?','Que rapporte le hadith sur la station à Arafat pendant le Hajj ?','Was berichtet der Hadith über den Aufenthalt in Arafat während des Hajj?'],
 muzdalifah:['আরাফাত থেকে ফেরার পর আল্লাহকে স্মরণ করা সম্পর্কে কুরআন কী বলে?','अरफ़ात से लौटने के बाद अल्लाह को याद करने के बारे में क़ुरआन क्या कहता है?','عرفات سے روانگی کے بعد اللہ کے ذکر کے بارے میں قرآن کیا کہتا ہے؟','Apa yang disebutkan Al-Quran tentang mengingat Allah setelah meninggalkan Arafat?','¿Qué dice el Corán sobre recordar a Alá después de salir de Arafat?','Que dit le Coran sur le rappel d’Allah après le départ d’Arafat ?','Was sagt der Koran über das Gedenken Allahs nach dem Aufbruch von Arafat?'],
 jamarat:['হজের সময় জামারাত সম্পর্কে হাদিসের উৎসগুলো কী বলে?','हज के दौरान जमरात के बारे में हदीस के स्रोत क्या बताते हैं?','حج کے دوران جمرات کے بارے میں احادیث کیا بیان کرتی ہیں؟','Apa yang disebutkan hadis tentang Jamarat saat Haji?','¿Qué relatan los hadices sobre los Yamarat durante el Hach?','Que rapportent les hadiths sur les Jamarat pendant le Hajj ?','Was berichten die Hadithe über die Dschamarat während des Hajj?'],
 ifada:['হজের সময় তাওয়াফে ইফাদা সম্পর্কে হাদিসের উৎসগুলো কী বলে?','हज के दौरान तवाफ़ अल-इफ़ादा के बारे में हदीस के स्रोत क्या बताते हैं?','حج کے دوران طوافِ افاضہ کے بارے میں احادیث کیا بیان کرتی ہیں؟','Apa yang disebutkan hadis tentang Tawaf Ifadah saat Haji?','¿Qué relatan los hadices sobre el Tawaf al-Ifada durante el Hach?','Que rapportent les hadiths sur le Tawaf al-Ifada pendant le Hajj ?','Was berichten die Hadithe über den Tawaf al-Ifada während des Hajj?'],
 farewell:['বিদায়ী তাওয়াফ সম্পর্কে হাদিসের উৎসগুলো কী বলে?','विदाई तवाफ़ के बारे में हदीस के स्रोत क्या कहते हैं?','طوافِ وداع کے بارے میں احادیث کیا کہتی ہیں؟','Apa yang disebutkan hadis tentang Tawaf perpisahan?','¿Qué dicen los hadices sobre el Tawaf de despedida?','Que disent les hadiths sur le Tawaf d’adieu ?','Was sagen die Hadithe über den Abschieds-Tawaf?'],
};
export function journeyTopic(item:JourneyItem,language:DisplayLanguage){
 if(language==='ar')return {label:item.label_ar,question:item.question_ar};
 if(language==='en')return {label:item.label_en,question:item.question_en};
 const index=languages.indexOf(language);
 return {label:labels[item.id][index],question:questions[item.id][index]};
}
const notes:Record<DisplayLanguage,[string,string,string]>={
 ar:['تنقّل بين موضوعات العمرة، ثم افحص سؤالك بالأدلة.','هذه موضوعات للتعلّم، وليست ترتيباً ملزماً لجميع أنواع الحج. التمتع والقران والإفراد تختلف في بعض الأعمال والتوقيت.','اختيار موضوع لا يسجل إتمام النسك ولا يصدر حكماً على حالتك. عداد الطواف يسجل جلسة واحدة؛ امسحه باختيارك قبل طواف آخر.'],
 en:['Explore the Umrah topics, then examine your question against the evidence.','These are learning topics, not a mandatory sequence for every form of Hajj. Tamattu, Qiran and Ifrad differ in some actions and timing.','Selecting a topic does not record ritual completion or issue a ruling on your situation. The Tawaf counter tracks one session; reset it yourself before another Tawaf.'],
 bn:['উমরার বিষয়গুলো দেখুন, তারপর প্রমাণ দিয়ে প্রশ্ন যাচাই করুন।','এগুলো শেখার বিষয়, সব ধরনের হজের বাধ্যতামূলক ক্রম নয়। তামাত্তু, কিরান ও ইফরাদের কিছু কাজ ও সময় আলাদা।','বিষয় বাছাই করলে ইবাদত সম্পন্ন হিসেবে নথিভুক্ত হয় না, ব্যক্তিগত রায়ও দেওয়া হয় না। তাওয়াফের কাউন্টার এক সেশন ধরে; পরের তাওয়াফের আগে নিজে রিসেট করুন।'],
 hi:['उमरा के विषय देखें, फिर साक्ष्यों से अपना प्रश्न जाँचें।','ये सीखने के विषय हैं, हर प्रकार के हज का अनिवार्य क्रम नहीं। तमत्तु, क़िरान और इफ़राद के कुछ कार्य और समय अलग हैं।','विषय चुनने से अनुष्ठान पूरा दर्ज नहीं होता और व्यक्तिगत फ़ैसला नहीं मिलता। तवाफ़ काउंटर एक सत्र रखता है; अगले तवाफ़ से पहले स्वयं रीसेट करें।'],
 ur:['عمرہ کے موضوعات دیکھیں، پھر اپنے سوال کو دلائل سے جانچیں۔','یہ سیکھنے کے موضوعات ہیں، ہر قسم کے حج کی لازمی ترتیب نہیں۔ تمتع، قران اور افراد کے کچھ اعمال اور اوقات مختلف ہیں۔','موضوع منتخب کرنے سے نسک مکمل درج نہیں ہوتا اور ذاتی حکم نہیں ملتا۔ طواف کاؤنٹر ایک نشست گنتا ہے؛ اگلے طواف سے پہلے خود ری سیٹ کریں۔'],
 id:['Jelajahi topik Umrah, lalu periksa pertanyaan Anda dengan bukti.','Ini topik pembelajaran, bukan urutan wajib untuk setiap jenis Haji. Tamattu, Qiran dan Ifrad berbeda dalam beberapa tindakan dan waktu.','Memilih topik tidak mencatat selesainya ibadah atau memberi putusan pribadi. Penghitung Tawaf mencatat satu sesi; reset sendiri sebelum Tawaf berikutnya.'],
 es:['Explora los temas de la Umra y examina tu pregunta con las pruebas.','Son temas de aprendizaje, no una secuencia obligatoria para todas las formas del Hach. Tamattu, Qiran e Ifrad difieren en algunas acciones y tiempos.','Elegir un tema no registra la finalización del rito ni emite un dictamen personal. El contador registra una sesión de Tawaf; reinícialo antes de otro Tawaf.'],
 fr:['Explorez les thèmes de la Omra, puis examinez votre question avec les preuves.','Ce sont des thèmes d’apprentissage, pas une séquence obligatoire pour toutes les formes du Hajj. Tamattu, Qiran et Ifrad diffèrent sur certains actes et horaires.','Choisir un thème n’enregistre pas l’accomplissement du rite et ne rend pas d’avis personnel. Le compteur suit une session de Tawaf ; réinitialisez-le avant un autre Tawaf.'],
 de:['Erkunden Sie die Umra-Themen und prüfen Sie Ihre Frage anhand der Belege.','Dies sind Lernthemen, keine verbindliche Reihenfolge für jede Hajj-Form. Tamattu, Qiran und Ifrad unterscheiden sich in einigen Handlungen und Zeiten.','Die Themenwahl vermerkt keinen abgeschlossenen Ritus und gibt kein persönliches Urteil. Der Tawaf-Zähler erfasst eine Sitzung; vor einem weiteren Tawaf selbst zurücksetzen.'],
};
export const journeyNotes=(language:DisplayLanguage)=>notes[language];
