import type {DisplayLanguage} from './display-copy';
import {starterQuestions} from './starter-questions';
export const landingExample={id:'sample-tawakkul-effort',question_en:starterQuestions('en','main','auto')[0],question_ar:starterQuestions('ar','main','auto')[0],headline_en:'No. Trust in Allah goes alongside practical effort.',headline_ar:'لا. التوكل على الله يصاحب الأخذ بالأسباب.',summary_en:'No. Quran 3:159 places consultation and a firm decision before reliance on Allah. The cited passage presents decision-making and trust together; it does not tell you to abandon planning or practical effort.',summary_ar:'لا. تذكر الآية 3:159 المشاورة والعزم قبل التوكل على الله. يجمع النص المستشهد به بين اتخاذ القرار والتوكل؛ ولا يدعو إلى ترك التخطيط أو الأخذ بالأسباب.'};
const translations:Record<DisplayLanguage,[string,string,string,string]>={
 en:[landingExample.headline_en,landingExample.summary_en,'Source-based illustrative example','Use this example question'],
 ar:[landingExample.headline_ar,landingExample.summary_ar,'مثال توضيحي مستند إلى النص','استخدم سؤال المثال'],
 bn:['না। আল্লাহর ওপর ভরসা বাস্তব প্রচেষ্টার সঙ্গে চলে।','না। কুরআন ৩:১৫৯-এ আল্লাহর ওপর ভরসার আগে পরামর্শ ও দৃঢ় সিদ্ধান্তের কথা আছে। উদ্ধৃত অংশ সিদ্ধান্ত গ্রহণ ও ভরসাকে একসঙ্গে উপস্থাপন করে; পরিকল্পনা বা বাস্তব প্রচেষ্টা ছেড়ে দিতে বলে না।','উৎসভিত্তিক উদাহরণ · ইংরেজি থেকে অনূদিত','এই উদাহরণের প্রশ্ন ব্যবহার করুন'],
 hi:['नहीं। अल्लाह पर भरोसा व्यावहारिक प्रयास के साथ चलता है।','नहीं। कुरआन 3:159 में अल्लाह पर भरोसे से पहले परामर्श और दृढ़ निर्णय का उल्लेख है। उद्धृत अंश निर्णय लेने और भरोसे को साथ प्रस्तुत करता है; योजना या व्यावहारिक प्रयास छोड़ने को नहीं कहता।','स्रोत आधारित उदाहरण · अंग्रेज़ी से अनुवादित','इस उदाहरण का प्रश्न इस्तेमाल करें'],
 ur:['نہیں۔ اللہ پر توکل عملی کوشش کے ساتھ ہوتا ہے۔','نہیں۔ قرآن 3:159 میں اللہ پر توکل سے پہلے مشاورت اور پختہ فیصلے کا ذکر ہے۔ اقتباس فیصلہ کرنے اور توکل کو ساتھ بیان کرتا ہے؛ یہ منصوبہ بندی یا عملی کوشش چھوڑنے کو نہیں کہتا۔','ماخذ پر مبنی مثال · انگریزی سے ترجمہ','اس مثال کا سوال استعمال کریں'],
 id:['Tidak. Tawakal kepada Allah berjalan bersama usaha nyata.','Tidak. Al-Quran 3:159 menyebut musyawarah dan keputusan yang teguh sebelum bertawakal kepada Allah. Kutipan tersebut mengaitkan pengambilan keputusan dan tawakal; bukan menyuruh meninggalkan perencanaan atau usaha nyata.','Contoh berbasis sumber · diterjemahkan dari bahasa Inggris','Gunakan pertanyaan contoh ini'],
 es:['No. Confiar en Allah va de la mano del esfuerzo práctico.','No. El Corán 3:159 sitúa la consulta y una decisión firme antes de confiar en Allah. El pasaje citado presenta la toma de decisiones y la confianza juntas; no indica que debas abandonar la planificación ni el esfuerzo práctico.','Ejemplo basado en fuentes · traducido del inglés','Usar esta pregunta de ejemplo'],
 fr:['Non. La confiance en Allah accompagne les efforts concrets.','Non. Le Coran 3:159 place la consultation et une décision ferme avant la confiance en Allah. Le passage cité associe la prise de décision et la confiance ; il ne demande pas d’abandonner la planification ou les efforts concrets.','Exemple fondé sur les sources · traduit de l’anglais','Utiliser cette question d’exemple'],
 de:['Nein. Vertrauen auf Allah geht mit praktischem Bemühen einher.','Nein. Koran 3:159 nennt Beratung und einen festen Entschluss vor dem Vertrauen auf Allah. Die zitierte Passage verbindet Entscheidungsfindung und Vertrauen; sie fordert nicht dazu auf, Planung oder praktisches Bemühen aufzugeben.','Quellenbasiertes Beispiel · aus dem Englischen übersetzt','Diese Beispielfrage verwenden'],
};
export function landingExampleCopy(language:DisplayLanguage){const [headline,summary,banner,use]=translations[language];return {question:starterQuestions(language,'main','auto')[0],headline,summary,banner,use};}
