import type {DisplayLanguage} from './display-copy';
type Copy={title:string;intro:string;examples:string[];main:string;tools:string};
export const pilgrimageCopy:Record<DisplayLanguage,Copy>={
  ar:{title:'مرافق العمرة والحج',intro:'اسأل عن العمرة والحج بكلماتك. نربط الإجابة بالأدلة، ونحوّل الأسئلة الأخرى إلى أداة التحقق الرئيسية.',examples:['هل يبدأ السعي من الصفا؟','كم شوطاً في الطواف؟','ماذا يقول القرآن عن الصفا والمروة؟'],main:'التحقق الرئيسي',tools:'المواقيت والتقويم'},
  en:{title:'Umrah & Hajj companion',intro:'Ask about pilgrimage in your own words. Answers use source evidence; other questions go to the main verification tool.',examples:['Does Sai begin at Safa?','How many circuits are there in Tawaf?','What does the Quran say about Safa and Marwah?'],main:'Main verification',tools:'Prayer times & calendar'},
  bn:{title:'উমরাহ ও হজ সহায়ক',intro:'নিজের ভাষায় উমরাহ ও হজের প্রশ্ন করুন। উত্তর উৎসভিত্তিক; অন্য প্রশ্ন প্রধান যাচাই টুলে পাঠানো হবে।',examples:['সাঈ কি সাফা থেকে শুরু হয়?','তাওয়াফে কত চক্কর আছে?'],main:'প্রধান যাচাই',tools:'নামাজের সময় ও ক্যালেন্ডার'},
  hi:{title:'उमराह और हज सहायक',intro:'अपने शब्दों में उमराह और हज के प्रश्न पूछें। उत्तर स्रोतों पर आधारित हैं; अन्य प्रश्न मुख्य सत्यापन टूल में भेजे जाते हैं।',examples:['क्या सई सफा से शुरू होती है?','तवाफ में कितने चक्कर होते हैं?'],main:'मुख्य सत्यापन',tools:'नमाज़ का समय और कैलेंडर'},
  ur:{title:'عمرہ اور حج کا معاون',intro:'عمرہ اور حج کے بارے میں اپنے الفاظ میں پوچھیں۔ جواب ماخذوں پر مبنی ہیں؛ دوسرے سوالات مرکزی تصدیقی ٹول کی طرف بھیجے جاتے ہیں۔',examples:['کیا سعی صفا سے شروع ہوتی ہے؟','طواف میں کتنے چکر ہوتے ہیں؟'],main:'مرکزی تصدیق',tools:'نماز کے اوقات اور تقویم'},
  id:{title:'Pendamping Umrah & Haji',intro:'Tanyakan tentang Umrah dan Haji dengan kata-kata sendiri. Jawaban memakai bukti sumber; pertanyaan lain diarahkan ke alat verifikasi utama.',examples:['Apakah Sai dimulai dari Safa?','Berapa putaran dalam Tawaf?'],main:'Verifikasi utama',tools:'Waktu salat & kalender'},
  es:{title:'Asistente de Umrah y Hajj',intro:'Pregunta sobre la peregrinación con tus propias palabras. Las respuestas se basan en fuentes; otras preguntas se remiten a la herramienta principal.',examples:['¿El Sai comienza en Safa?','¿Cuántas vueltas tiene el Tawaf?'],main:'Verificación principal',tools:'Oración y calendario'},
  fr:{title:'Compagnon Omra et Hajj',intro:'Posez vos questions sur le pèlerinage avec vos propres mots. Les réponses reposent sur les sources ; les autres questions sont orientées vers l’outil principal.',examples:['Le Saï commence-t-il à Safa ?','Combien de tours comporte le Tawaf ?'],main:'Vérification principale',tools:'Prières et calendrier'},
  de:{title:'Umrah- und Hadsch-Begleiter',intro:'Stelle Fragen zur Pilgerfahrt in eigenen Worten. Antworten stützen sich auf Quellen; andere Fragen werden an die Hauptprüfung verwiesen.',examples:['Beginnt Sai bei Safa?','Wie viele Runden hat Tawaf?'],main:'Hauptprüfung',tools:'Gebetszeiten und Kalender'},
};
