import type {DisplayLanguage} from './display-copy';
// Interface copy only. Counter calculations and source quotations are unchanged.
const rows:Record<DisplayLanguage,string[]>={
en:['Round counter','Where have you reached?','Record each completed circuit or Sai leg yourself. Progress stays on this device; the counter does not certify ritual validity.','Tawaf','Sai','Recorded','Remaining from your record','Completed one','Undo','Unsure of my count','Reset','Clear this counter’s record?','The counter cannot settle a doubtful count. Editing the record does not resolve the religious ruling; ask a qualified guide about your situation.','Seven recorded. This does not certify ritual validity or completion of its other requirements.','Saved progress could not be restored or stored. Keep track of the count yourself.','Count reference: HadeethEnc, 3309','This report describes the Farewell Hajj. Its Hajj-specific Ihram instructions are not automatically a standalone Umrah guide.'],
ar:['عداد الأشواط','أين وصلت؟','سجّل كل شوط مكتمل بنفسك. الحفظ على هذا الجهاز فقط؛ لا يثبت العداد صحة النسك.','الطواف','السعي','المسجّل','المتبقي حسب السجل','أكملت شوطاً','تراجع','لست متأكداً من العدد','مسح','مسح سجل هذا العداد؟','لا يستطيع العداد حسم الشك. تعديل السجل لا يحسم الحكم الشرعي؛ اسأل مرشداً مؤهلاً عن حالتك.','تم تسجيل سبعة. هذا لا يؤكد صحة النسك أو اكتمال بقية أعماله.','تعذر استرجاع السجل أو حفظه. راقب العدد بنفسك.','مرجع العدد: موسوعة الأحاديث، 3309','هذه الرواية تصف حجة الوداع؛ لا تُنقل أحكام إحرام الحج منها تلقائياً إلى العمرة المفردة.'],
bn:['চক্রের গণনা','কতদূর পৌঁছেছেন?','প্রতিটি সম্পূর্ণ তাওয়াফের চক্কর বা সাঈ পর্ব নিজে নথিভুক্ত করুন। অগ্রগতি শুধু এই যন্ত্রে থাকে; গণনাটি ইবাদতের শুদ্ধতা নিশ্চিত করে না।','তাওয়াফ','সাঈ','নথিভুক্ত','আপনার নথি অনুযায়ী বাকি','একটি সম্পূর্ণ করেছি','পূর্বাবস্থায়','গণনা নিয়ে নিশ্চিত নই','মুছুন','এই গণনার নথি মুছবেন?','সন্দেহপূর্ণ গণনা এই সরঞ্জাম মীমাংসা করতে পারে না। নথি বদলালে ধর্মীয় বিধান নির্ধারিত হয় না; আপনার অবস্থা সম্পর্কে যোগ্য গাইডকে জিজ্ঞাসা করুন।','সাতটি নথিভুক্ত। এতে ইবাদতের শুদ্ধতা বা অন্য শর্ত পূরণ নিশ্চিত হয় না।','অগ্রগতি পুনরুদ্ধার বা সংরক্ষণ করা যায়নি। নিজে গণনা রাখুন।','গণনার সূত্র: HadeethEnc, 3309','এই বর্ণনা বিদায় হজ সম্পর্কে। হজের ইহরাম-সংক্রান্ত নির্দেশনা স্বয়ংক্রিয়ভাবে স্বতন্ত্র উমরাহর নির্দেশিকা নয়।'],
hi:['चक्कर की गणना','आप कहाँ तक पहुँचे?','हर पूरा तवाफ चक्कर या सई चरण स्वयं दर्ज करें। प्रगति केवल इस उपकरण पर रहती है; गणना अनुष्ठान की वैधता प्रमाणित नहीं करती।','तवाफ','सई','दर्ज','आपके रिकॉर्ड के अनुसार शेष','एक पूरा किया','पूर्ववत','गिनती का भरोसा नहीं','रीसेट','इस गणना का रिकॉर्ड मिटाएँ?','यह उपकरण संदिग्ध गिनती तय नहीं कर सकता। रिकॉर्ड बदलने से धार्मिक निर्णय तय नहीं होता; अपनी स्थिति पर योग्य मार्गदर्शक से पूछें।','सात दर्ज हुए। यह अनुष्ठान की वैधता या अन्य आवश्यकताओं की पूर्ति प्रमाणित नहीं करता।','प्रगति बहाल या सहेजी नहीं जा सकी। स्वयं गिनती रखें।','गणना का स्रोत: HadeethEnc, 3309','यह वर्णन विदाई हज का है। हज-विशिष्ट इहराम निर्देश अपने आप स्वतंत्र उमराह की मार्गदर्शिका नहीं हैं।'],
ur:['چکروں کا شمار','آپ کہاں تک پہنچے؟','طواف کا ہر مکمل چکر یا سعی کا مرحلہ خود درج کریں۔ پیش رفت صرف اس آلے پر محفوظ رہتی ہے؛ شمار مناسک کی صحت کی تصدیق نہیں کرتا۔','طواف','سعی','درج شدہ','آپ کے ریکارڈ کے مطابق باقی','ایک مکمل کیا','واپس','شمار میں یقین نہیں','صاف کریں','اس شمار کا ریکارڈ صاف کریں؟','یہ آلہ مشکوک شمار کا فیصلہ نہیں کر سکتا۔ ریکارڈ بدلنے سے شرعی حکم طے نہیں ہوتا؛ اپنی صورت حال کے بارے میں مستند رہنما سے پوچھیں۔','سات درج ہوئے۔ یہ مناسک کی صحت یا باقی تقاضوں کی تکمیل کی تصدیق نہیں کرتا۔','پیش رفت بحال یا محفوظ نہ ہو سکی۔ شمار خود یاد رکھیں۔','شمار کا حوالہ: HadeethEnc، 3309','یہ روایت حجۃ الوداع کی ہے۔ حج کے احرام سے متعلق ہدایات خود بخود الگ عمرے کی رہنمائی نہیں بنتیں۔'],
id:['Penghitung putaran','Sudah sampai di mana?','Catat sendiri setiap putaran Tawaf atau lintasan Sai yang selesai. Kemajuan hanya tersimpan di perangkat ini; penghitung tidak menjamin keabsahan ibadah.','Tawaf','Sai','Tercatat','Sisa menurut catatan Anda','Satu selesai','Urungkan','Ragu dengan hitungan','Atur ulang','Hapus catatan penghitung ini?','Penghitung tidak dapat menyelesaikan keraguan hitungan. Mengubah catatan tidak menetapkan hukum agama; tanyakan keadaan Anda kepada pembimbing yang berkualifikasi.','Tujuh tercatat. Ini tidak menjamin keabsahan ibadah atau terpenuhinya persyaratan lain.','Kemajuan tidak dapat dipulihkan atau disimpan. Catat hitungan sendiri.','Rujukan hitungan: HadeethEnc, 3309','Riwayat ini menggambarkan Haji Wada. Petunjuk Ihram khusus Haji tidak otomatis menjadi panduan Umrah tersendiri.'],
es:['Contador de vueltas','¿Hasta dónde has llegado?','Registra cada vuelta de Tawaf o tramo de Sai completado. El progreso queda solo en este dispositivo; el contador no certifica la validez del rito.','Tawaf','Sai','Registrado','Restante según tu registro','Completé uno','Deshacer','No estoy seguro del número','Reiniciar','¿Borrar el registro de este contador?','El contador no resuelve una cuenta dudosa. Modificar el registro no determina el dictamen religioso; consulta a un guía cualificado sobre tu situación.','Siete registrados. Esto no certifica la validez del rito ni el cumplimiento de sus otros requisitos.','No se pudo recuperar o guardar el progreso. Lleva la cuenta por tu cuenta.','Referencia del número: HadeethEnc, 3309','Este relato describe el Hayy de despedida. Sus instrucciones de Ihram específicas del Hayy no son automáticamente una guía de Umrah independiente.'],
fr:['Compteur de tours','Où en êtes-vous ?','Enregistrez vous-même chaque tour de Tawaf ou trajet de Sai terminé. La progression reste sur cet appareil ; le compteur ne certifie pas la validité du rite.','Tawaf','Sai','Enregistré','Restant selon votre relevé','Un terminé','Annuler','Je doute du compte','Réinitialiser','Effacer le relevé de ce compteur ?','Le compteur ne peut pas trancher un compte incertain. Modifier le relevé ne détermine pas le jugement religieux ; consultez un guide qualifié sur votre situation.','Sept enregistrés. Cela ne certifie ni la validité du rite ni le respect de ses autres exigences.','La progression n’a pas pu être restaurée ou enregistrée. Gardez vous-même le compte.','Référence du nombre : HadeethEnc, 3309','Ce récit décrit le Hajj d’adieu. Ses instructions d’Ihram propres au Hajj ne constituent pas automatiquement un guide d’Umrah indépendante.'],
de:['Rundenzähler','Wie weit sind Sie gekommen?','Tragen Sie jede abgeschlossene Tawaf-Runde oder Sai-Strecke selbst ein. Der Fortschritt bleibt auf diesem Gerät; der Zähler bestätigt nicht die Gültigkeit des Rituals.','Tawaf','Sai','Erfasst','Laut Ihrem Eintrag verbleibend','Eine abgeschlossen','Rückgängig','Ich bin unsicher über die Anzahl','Zurücksetzen','Einträge dieses Zählers löschen?','Der Zähler kann eine ungewisse Anzahl nicht klären. Das Ändern der Einträge entscheidet nicht über die religiöse Beurteilung; fragen Sie einen qualifizierten Begleiter zu Ihrer Situation.','Sieben erfasst. Dies bestätigt weder die Gültigkeit des Rituals noch die Erfüllung anderer Anforderungen.','Der Fortschritt konnte nicht wiederhergestellt oder gespeichert werden. Behalten Sie die Anzahl selbst im Blick.','Quelle zur Anzahl: HadeethEnc, 3309','Dieser Bericht beschreibt den Abschieds-Hajj. Seine Hajj-spezifischen Ihram-Anweisungen sind nicht automatisch ein Leitfaden für eine eigenständige Umrah.'],
};
export function progressCopy(language:DisplayLanguage){const v=rows[language];return {counter:v[0],heading:v[1],intro:v[2],tawaf:v[3],sai:v[4],recorded:v[5],remaining:v[6],completed:v[7],undo:v[8],unsure:v[9],reset:v[10],confirm:v[11],doubt:v[12],seven:v[13],saveFailed:v[14],reference:v[15],boundary:v[16]};}

const journeyRows:Record<DisplayLanguage,string[]>={
 en:['Choose where your question belongs','Pilgrimage','Umrah','Hajj','Put this question in the evidence tool','Open counter','Open original reference','official journey reference','Topic questions and guidance below are shown in English.'],
 ar:['اختر موضع سؤالك','النسك','العمرة','الحج','ضع السؤال في أداة الفحص','افتح العداد','افتح المرجع الأصلي','دليل الرحلة الرسمي',''],
 bn:['আপনার প্রশ্নের বিষয় বেছে নিন','তীর্থযাত্রা','উমরাহ','হজ','এই প্রশ্ন যাচাইয়ের সরঞ্জামে দিন','গণনা খুলুন','মূল সূত্র খুলুন','আনুষ্ঠানিক যাত্রার সূত্র','নিচের বিষয়ভিত্তিক প্রশ্ন ও নির্দেশনা ইংরেজিতে দেখানো হয়েছে।'],
 hi:['अपने प्रश्न का विषय चुनें','तीर्थयात्रा','उमराह','हज','यह प्रश्न प्रमाण जाँच में डालें','गणना खोलें','मूल स्रोत खोलें','आधिकारिक यात्रा स्रोत','नीचे विषयों के प्रश्न और मार्गदर्शन अंग्रेज़ी में दिखाए गए हैं।'],
 ur:['اپنے سوال کا موضوع منتخب کریں','مناسک','عمرہ','حج','یہ سوال شواہد کی جانچ میں ڈالیں','شمار کھولیں','اصل حوالہ کھولیں','سفر کا سرکاری حوالہ','ذیل کے موضوعاتی سوالات اور رہنمائی انگریزی میں دکھائی گئی ہیں۔'],
 id:['Pilih topik pertanyaan Anda','Ibadah','Umrah','Haji','Masukkan pertanyaan ini ke alat bukti','Buka penghitung','Buka rujukan asli','rujukan perjalanan resmi','Pertanyaan topik dan panduan di bawah ditampilkan dalam bahasa Inggris.'],
 es:['Elige el tema de tu pregunta','Peregrinación','Umrah','Hayy','Llevar esta pregunta a la herramienta de pruebas','Abrir contador','Abrir referencia original','referencia oficial del recorrido','Las preguntas temáticas y la orientación de abajo se muestran en inglés.'],
 fr:['Choisissez le thème de votre question','Pèlerinage','Umrah','Hajj','Soumettre cette question à l’outil de preuves','Ouvrir le compteur','Ouvrir la référence originale','référence officielle du parcours','Les questions thématiques et les conseils ci-dessous sont affichés en anglais.'],
 de:['Wählen Sie das Thema Ihrer Frage','Pilgerfahrt','Umrah','Hajj','Diese Frage in das Belegwerkzeug übernehmen','Zähler öffnen','Originalquelle öffnen','offizielle Reisequelle','Die Themenfragen und Hinweise unten werden auf Englisch angezeigt.'],
};
export function journeyCopy(language:DisplayLanguage){const v=journeyRows[language];return {heading:v[0],ritual:v[1],umrah:v[2],hajj:v[3],question:v[4],counter:v[5],reference:v[6],official:v[7],fallback:v[8]};}
