import type {ClaimLanguage} from './claim-language';
const copy:Record<ClaimLanguage,string[]>={
 en:['Recent checks','Save this check on this device','Saved on this device','Nothing saved yet.','Load question','View saved receipt','Download saved receipt','Delete','Clear saved checks','Saved only when you choose. Up to eight per tool in this browser; no account sync. Loading a question does not run verification. Saved receipts are historical local copies, not newly verified results.','Saving is unavailable or the saved data is invalid. Verification still works.'],
 ar:['الفحوص الأخيرة','احفظ هذا الفحص على الجهاز','محفوظ على هذا الجهاز','لا توجد فحوص محفوظة.','حمّل السؤال','عرض السجل المحفوظ','تنزيل السجل المحفوظ','حذف','حذف الفحوص المحفوظة','الحفظ اختياري؛ حتى ثمانية فحوص لكل أداة في هذا المتصفح دون مزامنة حساب. تحميل السؤال لا يبدأ التحقق. السجلات نسخ محلية سابقة وليست نتائج تحقق جديدة.','الحفظ غير متاح أو البيانات غير صالحة. يظل التحقق متاحاً.'],
 bn:['সাম্প্রতিক যাচাই','এই ডিভাইসে যাচাই সংরক্ষণ করুন','এই ডিভাইসে সংরক্ষিত','এখনও কিছু সংরক্ষিত নেই।','প্রশ্ন লোড করুন','সংরক্ষিত রেকর্ড দেখুন','সংরক্ষিত রেকর্ড ডাউনলোড','মুছুন','সংরক্ষিত যাচাই মুছুন','শুধু আপনার পছন্দে সংরক্ষণ। এই ব্রাউজারে প্রতি টুলে আটটি; অ্যাকাউন্টে সিঙ্ক নয়। প্রশ্ন লোড করলে যাচাই চলে না। রেকর্ড পুরোনো স্থানীয় কপি, নতুন যাচাই নয়।','সংরক্ষণ অনুপলব্ধ বা তথ্য ভুল। যাচাই কাজ করে।'],
 hi:['हाल की जाँच','इस डिवाइस पर जाँच सहेजें','इस डिवाइस पर सहेजा गया','अभी कुछ नहीं सहेजा।','प्रश्न लोड करें','सहेजा रिकॉर्ड देखें','सहेजा रिकॉर्ड डाउनलोड','हटाएँ','सहेजी जाँच हटाएँ','केवल आपके चुनने पर सहेजता है। इस ब्राउज़र में हर टूल के आठ रिकॉर्ड; खाते से सिंक नहीं। प्रश्न लोड करने से जाँच नहीं चलती। रिकॉर्ड पुराने स्थानीय प्रतिरूप हैं, नई जाँच नहीं।','सहेजना उपलब्ध नहीं या डेटा अमान्य है। जाँच काम करती है।'],
 ur:['حالیہ جانچ','یہ جانچ اس ڈیوائس پر محفوظ کریں','اس ڈیوائس پر محفوظ','ابھی کچھ محفوظ نہیں۔','سوال لوڈ کریں','محفوظ ریکارڈ دیکھیں','محفوظ ریکارڈ ڈاؤن لوڈ','حذف','محفوظ جانچ حذف کریں','صرف آپ کے انتخاب پر محفوظ ہوتا ہے۔ اس براؤزر میں ہر ٹول کے آٹھ ریکارڈ؛ اکاؤنٹ سے ہم آہنگ نہیں۔ سوال لوڈ کرنا تصدیق نہیں چلاتا۔ ریکارڈ پرانی مقامی نقول ہیں، نئی تصدیق نہیں۔','محفوظ کرنا دستیاب نہیں یا ڈیٹا غلط ہے۔ تصدیق کام کرتی ہے۔'],
 id:['Pemeriksaan terbaru','Simpan pemeriksaan di perangkat ini','Tersimpan di perangkat ini','Belum ada yang disimpan.','Muat pertanyaan','Lihat catatan tersimpan','Unduh catatan tersimpan','Hapus','Hapus pemeriksaan tersimpan','Hanya disimpan jika dipilih. Maksimal delapan per alat di browser ini; tanpa sinkronisasi akun. Memuat pertanyaan tidak menjalankan verifikasi. Catatan adalah salinan lokal lama, bukan hasil verifikasi baru.','Penyimpanan tidak tersedia atau data tidak valid. Verifikasi tetap bekerja.'],
 es:['Comprobaciones recientes','Guardar en este dispositivo','Guardado en este dispositivo','Todavía no hay nada guardado.','Cargar pregunta','Ver registro guardado','Descargar registro guardado','Eliminar','Borrar comprobaciones guardadas','Solo se guarda si lo eliges. Hasta ocho por herramienta en este navegador; sin sincronización. Cargar una pregunta no verifica. Los registros son copias históricas locales, no resultados nuevos.','No se puede guardar o los datos no son válidos. La verificación sigue funcionando.'],
 fr:['Examens récents','Enregistrer sur cet appareil','Enregistré sur cet appareil','Aucun examen enregistré.','Charger la question','Voir le relevé enregistré','Télécharger le relevé','Supprimer','Effacer les examens enregistrés','Enregistrement uniquement à votre choix. Huit par outil dans ce navigateur ; sans synchronisation. Charger une question ne lance pas l’examen. Les relevés sont des copies locales historiques, pas de nouveaux résultats.','Stockage indisponible ou données invalides. La vérification fonctionne toujours.'],
 de:['Letzte Prüfungen','Auf diesem Gerät speichern','Auf diesem Gerät gespeichert','Noch nichts gespeichert.','Frage laden','Gespeicherten Beleg ansehen','Gespeicherten Beleg herunterladen','Löschen','Gespeicherte Prüfungen löschen','Speicherung nur auf Wunsch. Bis zu acht je Werkzeug in diesem Browser; keine Kontosynchronisierung. Laden startet keine Prüfung. Belege sind historische lokale Kopien, keine neuen Ergebnisse.','Speichern nicht verfügbar oder Daten ungültig. Die Prüfung funktioniert weiterhin.']
};
export const recentCopy=(language:ClaimLanguage)=>copy[language];
