import type {ClaimLanguage} from './claim-language';
// Questions, not precomputed religious answers or a claim of search popularity.
const questions:Record<ClaimLanguage,{main:string[];hadith:string[];pilgrimage:string[]}>= {
 en:{main:['Is eating pork forbidden in Islam?','What does the Quran say about fasting in Ramadan?','What does the Quran say about treating parents kindly?','What do Islamic sources say about backbiting?','Does the Quran say that every living thing was made from water?','What do Islamic sources say about giving charity?'],hadith:['What do Hadith sources say about intentions?','What do Hadith sources say about kindness to neighbours?','What do Hadith sources say about making things easy?'],pilgrimage:['What does the Quran say about Safa and Marwa?','How many circuits are in Tawaf?','What does the Quran say about remembrance after leaving Arafat?','What do Hadith sources say about the farewell Tawaf?']},
 ar:{main:['هل أكل لحم الخنزير حرام في الإسلام؟','ماذا يقول القرآن عن صيام رمضان؟','ماذا يقول القرآن عن الإحسان إلى الوالدين؟','ماذا تقول المصادر الإسلامية عن الغيبة؟','هل يقول القرآن إن كل شيء حي خُلق من الماء؟','ماذا تقول المصادر الإسلامية عن الصدقة؟'],hadith:['ماذا تقول الأحاديث عن النيات؟','ماذا تقول الأحاديث عن الإحسان إلى الجيران؟','ماذا تقول الأحاديث عن التيسير؟'],pilgrimage:['ماذا يقول القرآن عن الصفا والمروة؟','كم عدد أشواط الطواف؟','ماذا يقول القرآن عن الذكر بعد الإفاضة من عرفات؟','ماذا تقول الأحاديث عن طواف الوداع؟']},
 bn:{main:['ইসলামে শূকরের মাংস খাওয়া কি হারাম?','রমজানের রোজা সম্পর্কে কুরআন কী বলে?','মা-বাবার সঙ্গে ভালো আচরণ সম্পর্কে কুরআন কী বলে?','গিবত সম্পর্কে ইসলামী সূত্র কী বলে?','কুরআন কি বলে প্রতিটি জীবন্ত বস্তু পানি থেকে তৈরি?','সদকা সম্পর্কে ইসলামী সূত্র কী বলে?'],hadith:['নিয়ত সম্পর্কে হাদিস কী বলে?','প্রতিবেশীর সঙ্গে ভালো আচরণ সম্পর্কে হাদিস কী বলে?','সহজ করার বিষয়ে হাদিস কী বলে?'],pilgrimage:['সাফা ও মারওয়া সম্পর্কে কুরআন কী বলে?','তাওয়াফে কতটি চক্কর আছে?','আরাফাত থেকে ফেরার পর আল্লাহকে স্মরণ সম্পর্কে কুরআন কী বলে?','বিদায়ী তাওয়াফ সম্পর্কে হাদিস কী বলে?']},
 hi:{main:['क्या इस्लाम में सूअर का मांस खाना हराम है?','रमज़ान के रोज़े के बारे में कुरआन क्या कहता है?','माता-पिता से अच्छा व्यवहार करने के बारे में कुरआन क्या कहता है?','पीठ पीछे बुराई के बारे में इस्लामी स्रोत क्या कहते हैं?','क्या कुरआन कहता है कि हर जीवित चीज़ पानी से बनाई गई?','दान के बारे में इस्लामी स्रोत क्या कहते हैं?'],hadith:['नीयत के बारे में हदीस क्या कहती है?','पड़ोसियों से अच्छा व्यवहार करने के बारे में हदीस क्या कहती है?','आसानी करने के बारे में हदीस क्या कहती है?'],pilgrimage:['सफ़ा और मरवा के बारे में कुरआन क्या कहता है?','तवाफ़ में कितने चक्कर होते हैं?','अरफ़ात से लौटने के बाद अल्लाह को याद करने के बारे में कुरआन क्या कहता है?','विदाई तवाफ़ के बारे में हदीस क्या कहती है?']},
 ur:{main:['کیا اسلام میں سور کا گوشت کھانا حرام ہے؟','قرآن رمضان کے روزوں کے بارے میں کیا کہتا ہے؟','قرآن والدین کے ساتھ اچھے سلوک کے بارے میں کیا کہتا ہے؟','اسلامی مصادر غیبت کے بارے میں کیا کہتے ہیں؟','کیا قرآن کہتا ہے کہ ہر زندہ چیز پانی سے بنائی گئی؟','اسلامی مصادر صدقے کے بارے میں کیا کہتے ہیں؟'],hadith:['احادیث نیتوں کے بارے میں کیا کہتی ہیں؟','احادیث پڑوسیوں کے ساتھ اچھے سلوک کے بارے میں کیا کہتی ہیں؟','احادیث آسانی کرنے کے بارے میں کیا کہتی ہیں؟'],pilgrimage:['قرآن صفا اور مروہ کے بارے میں کیا کہتا ہے؟','طواف میں کتنے چکر ہوتے ہیں؟','قرآن عرفات سے واپسی کے بعد ذکر کے بارے میں کیا کہتا ہے؟','احادیث طواف وداع کے بارے میں کیا کہتی ہیں؟']},
 id:{main:['Apakah memakan daging babi dilarang dalam Islam?','Apa yang Al-Quran katakan tentang puasa Ramadan?','Apa yang Al-Quran katakan tentang berbuat baik kepada orang tua?','Apa yang sumber Islam katakan tentang ghibah?','Apakah Al-Quran mengatakan setiap makhluk hidup dibuat dari air?','Apa yang sumber Islam katakan tentang sedekah?'],hadith:['Apa yang sumber Hadis katakan tentang niat?','Apa yang sumber Hadis katakan tentang berbuat baik kepada tetangga?','Apa yang sumber Hadis katakan tentang memudahkan urusan?'],pilgrimage:['Apa yang Al-Quran katakan tentang Safa dan Marwa?','Berapa putaran dalam Tawaf?','Apa yang Al-Quran katakan tentang mengingat Allah setelah meninggalkan Arafah?','Apa yang sumber Hadis katakan tentang Tawaf perpisahan?']},
 es:{main:['¿Está prohibido comer cerdo en el islam?','¿Qué dice el Corán sobre el ayuno de Ramadán?','¿Qué dice el Corán sobre tratar bien a los padres?','¿Qué dicen las fuentes islámicas sobre hablar mal de alguien a sus espaldas?','¿Dice el Corán que todo ser vivo fue creado del agua?','¿Qué dicen las fuentes islámicas sobre dar caridad?'],hadith:['¿Qué dicen los hadices sobre las intenciones?','¿Qué dicen los hadices sobre tratar bien a los vecinos?','¿Qué dicen los hadices sobre facilitar las cosas?'],pilgrimage:['¿Qué dice el Corán sobre Safa y Marwa?','¿Cuántas vueltas tiene el Tawaf?','¿Qué dice el Corán sobre recordar a Allah después de salir de Arafat?','¿Qué dicen los hadices sobre el Tawaf de despedida?']},
 fr:{main:['Manger du porc est-il interdit en islam ?','Que dit le Coran sur le jeûne du Ramadan ?','Que dit le Coran sur la bonté envers les parents ?','Que disent les sources islamiques sur la médisance ?','Le Coran dit-il que tout être vivant a été créé à partir de l’eau ?','Que disent les sources islamiques sur la charité ?'],hadith:['Que disent les hadiths sur les intentions ?','Que disent les hadiths sur la bonté envers les voisins ?','Que disent les hadiths sur le fait de faciliter les choses ?'],pilgrimage:['Que dit le Coran sur Safa et Marwa ?','Combien de tours compte le Tawaf ?','Que dit le Coran sur le rappel d’Allah après avoir quitté Arafat ?','Que disent les hadiths sur le Tawaf d’adieu ?']},
 de:{main:['Ist der Verzehr von Schweinefleisch im Islam verboten?','Was sagt der Koran über das Fasten im Ramadan?','Was sagt der Koran über Freundlichkeit gegenüber Eltern?','Was sagen islamische Quellen über üble Nachrede?','Sagt der Koran, dass jedes Lebewesen aus Wasser geschaffen wurde?','Was sagen islamische Quellen über Wohltätigkeit?'],hadith:['Was sagen Hadith-Quellen über Absichten?','Was sagen Hadith-Quellen über Freundlichkeit gegenüber Nachbarn?','Was sagen Hadith-Quellen darüber, Dinge zu erleichtern?'],pilgrimage:['Was sagt der Koran über Safa und Marwa?','Wie viele Runden hat der Tawaf?','Was sagt der Koran über das Gedenken an Allah nach dem Verlassen von Arafat?','Was sagen Hadith-Quellen über den Abschieds-Tawaf?']}
};
export function starterQuestions(language:ClaimLanguage,service:'main'|'pilgrimage',corpus:'auto'|'quran'|'hadith'){const copy=questions[language];return service==='pilgrimage'?copy.pilgrimage:corpus==='hadith'?copy.hadith:copy.main;}
