import type {DisplayLanguage} from './display-copy';
const labels:Record<DisplayLanguage,readonly string[]>={
 en:['Your workspace','Explore more','Daily essentials','Every question deserves','a clear source.','A little more clarity. A little less doubt.','Understanding begins with the source.','View an example','New question','Original sources','Traceable evidence','Clear limits','Read the original Quran and Hadith passages.','Follow each reference back to its source.','Understand what a result can and cannot establish.','Supporting tools','Learn, prepare and keep track of your journey.','Prayer times, Qibla and calendar.','Our approach','Answer','Source evidence','Curated example · no new AI check'],
 ar:['مساحة العمل','استكشف المزيد','أدواتك اليومية','لكل سؤال،','مصدرٌ واضح.','وضوح أكثر. تساؤلات أقل.','الفهم يبدأ من المصدر.','شاهد مثالاً','سؤال جديد','النصوص الأصلية','أدلة قابلة للتتبع','حدود واضحة','اقرأ النصوص الأصلية من القرآن والحديث.','تتبّع كل إحالة إلى مصدرها.','افهم ما تثبته النتيجة وما لا تثبته.','أدوات مساعدة','تعلّم واستعد وتابع رحلتك.','مواقيت الصلاة والقبلة والتقويم.','منهجنا','الإجابة','أدلة المصدر','مثال مُعد مسبقاً · دون فحص جديد'],
 bn:['আপনার কর্মক্ষেত্র','আরও দেখুন','দৈনন্দিন সরঞ্জাম','প্রতিটি প্রশ্নের জন্য','একটি স্পষ্ট সূত্র।','আরও স্পষ্টতা। কম সংশয়।','বোঝার শুরু মূল সূত্র থেকে।','একটি উদাহরণ দেখুন','নতুন প্রশ্ন','মূল সূত্র','অনুসরণযোগ্য প্রমাণ','স্পষ্ট সীমা','কুরআন ও হাদিসের মূল পাঠ পড়ুন।','প্রতিটি উদ্ধৃতির মূল সূত্র দেখুন।','ফলাফল কী প্রমাণ করে আর কী করে না, বুঝুন।','সহায়ক সরঞ্জাম','শিখুন, প্রস্তুতি নিন ও যাত্রার অগ্রগতি রাখুন।','নামাজের সময়, কিবলা ও ক্যালেন্ডার।','আমাদের পদ্ধতি','উত্তর','সূত্রের প্রমাণ','প্রস্তুত উদাহরণ · নতুন AI যাচাই নয়'],
 hi:['आपका कार्यक्षेत्र','और देखें','दैनिक उपकरण','हर प्रश्न के लिए','एक स्पष्ट स्रोत।','अधिक स्पष्टता। कम संदेह।','समझ की शुरुआत स्रोत से होती है।','एक उदाहरण देखें','नया प्रश्न','मूल स्रोत','जाँचने योग्य प्रमाण','स्पष्ट सीमाएँ','कुरआन और हदीस के मूल अंश पढ़ें।','हर संदर्भ के मूल स्रोत तक जाएँ।','समझें कि परिणाम क्या साबित कर सकता है।','सहायक उपकरण','सीखें, तैयारी करें और यात्रा पर नज़र रखें।','नमाज़ का समय, क़िबला और कैलेंडर।','हमारी पद्धति','उत्तर','स्रोत प्रमाण','तैयार उदाहरण · नई AI जाँच नहीं'],
 ur:['آپ کی جگہ','مزید دیکھیں','روزمرہ کے اوزار','ہر سوال کے لیے','ایک واضح ماخذ۔','زیادہ وضاحت۔ کم ابہام۔','سمجھ کی ابتدا ماخذ سے ہوتی ہے۔','ایک مثال دیکھیں','نیا سوال','اصل ماخذ','قابلِ تتبع شواہد','واضح حدود','قرآن اور حدیث کی اصل عبارت پڑھیں۔','ہر حوالے کے اصل ماخذ تک جائیں۔','سمجھیں کہ نتیجہ کیا ثابت کر سکتا ہے اور کیا نہیں۔','معاون اوزار','سیکھیں، تیاری کریں اور سفر کا ریکارڈ رکھیں۔','نماز کے اوقات، قبلہ اور تقویم۔','ہمارا طریقہ','جواب','ماخذ کے شواہد','تیار کردہ مثال · نئی AI جانچ نہیں'],
 id:['Ruang kerja Anda','Jelajahi lainnya','Perlengkapan harian','Setiap pertanyaan layak mendapat','sumber yang jelas.','Lebih jelas. Lebih sedikit keraguan.','Pemahaman dimulai dari sumber.','Lihat contoh','Pertanyaan baru','Sumber asli','Bukti yang dapat ditelusuri','Batasan yang jelas','Baca teks asli Al-Quran dan Hadis.','Telusuri setiap rujukan ke sumbernya.','Pahami apa yang dapat dan tidak dapat dibuktikan.','Alat pendukung','Belajar, bersiap, dan catat perjalanan Anda.','Waktu salat, kiblat, dan kalender.','Pendekatan kami','Jawaban','Sumber bukti','Contoh siap pakai · tanpa pemeriksaan AI baru'],
 es:['Tu espacio','Explora más','Herramientas diarias','Cada pregunta merece','una fuente clara.','Más claridad. Menos dudas.','Comprender empieza por la fuente.','Ver un ejemplo','Nueva pregunta','Fuentes originales','Pruebas rastreables','Límites claros','Lee los pasajes originales del Corán y los hadices.','Sigue cada referencia hasta su fuente.','Comprende qué puede establecer un resultado.','Herramientas de apoyo','Aprende, prepárate y registra tu recorrido.','Horarios de oración, Qibla y calendario.','Nuestro método','Respuesta','Fuentes de pruebas','Ejemplo preparado · sin nueva verificación de IA'],
 fr:['Votre espace','Explorer','Outils du quotidien','Chaque question mérite','une source claire.','Plus de clarté. Moins de doutes.','Comprendre commence par la source.','Voir un exemple','Nouvelle question','Sources originales','Preuves traçables','Limites claires','Lisez les passages originaux du Coran et des hadiths.','Suivez chaque référence vers sa source.','Comprenez ce que le résultat permet ou non de conclure.','Outils complémentaires','Apprenez, préparez et suivez votre parcours.','Horaires de prière, Qibla et calendrier.','Notre méthode','Réponse','Sources de preuves','Exemple préparé · aucune nouvelle vérification IA'],
 de:['Ihr Arbeitsbereich','Mehr entdecken','Alltagswerkzeuge','Jede Frage verdient','eine klare Quelle.','Mehr Klarheit. Weniger Zweifel.','Verständnis beginnt bei der Quelle.','Beispiel ansehen','Neue Frage','Originalquellen','Nachvollziehbare Belege','Klare Grenzen','Lesen Sie die Originaltexte aus Koran und Hadith.','Verfolgen Sie jeden Verweis bis zur Quelle.','Verstehen Sie die Aussagekraft und Grenzen des Ergebnisses.','Ergänzende Werkzeuge','Lernen, vorbereiten und den Weg festhalten.','Gebetszeiten, Qibla und Kalender.','Unsere Methode','Antwort','Quellenbelege','Vorbereitetes Beispiel · keine neue KI-Prüfung'],
};
export function studioCopy(language:DisplayLanguage){const v=labels[language];return {workspace:v[0],explore:v[1],daily:({ar:'الإعدادات والأدوات',en:'Settings & Tools',bn:'সেটিংস ও সরঞ্জাম',hi:'सेटिंग और उपकरण',ur:'ترتیبات اور اوزار',id:'Pengaturan & Alat',es:'Ajustes y herramientas',fr:'Réglages et outils',de:'Einstellungen & Werkzeuge'})[language],headline:v[3],headlineEnd:v[4],eyebrow:v[5],motto:v[6],example:v[7],newQuestion:v[8],original:v[9],traceable:v[10],limits:v[11],originalNote:v[12],traceableNote:v[13],limitsNote:v[14],tools:v[15],journeyNote:v[16],dailyNote:v[17],method:v[18],answer:v[19],sources:v[20],sample:v[21]};}
