import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {cloudSpeechReady,synthesizeSpeech,validateSpeechInput,validateWav,SPEECH_MODEL} from '../src/lib/cloud-speech';
function wav(){const bytes=Buffer.alloc(48);bytes.write('RIFF');bytes.writeUInt32LE(40,4);bytes.write('WAVE',8);bytes.write('fmt ',12);bytes.writeUInt32LE(16,16);bytes.writeUInt16LE(1,20);bytes.writeUInt16LE(1,22);bytes.writeUInt32LE(24000,24);bytes.writeUInt32LE(48000,28);bytes.writeUInt16LE(2,32);bytes.writeUInt16LE(16,34);bytes.write('data',36);bytes.writeUInt32LE(4,40);return bytes;}
let directory:string;
beforeEach(()=>{directory=mkdtempSync(join(tmpdir(),'isnadlens-speech-'));vi.spyOn(process,'cwd').mockReturnValue(directory);vi.stubEnv('GEMINI_API_KEY','not-a-real-key');vi.stubEnv('ISNADLENS_GOOGLE_FREE_TIER_CONFIRMED','true');});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals();vi.unstubAllEnvs();rmSync(directory,{recursive:true,force:true});});
describe('free-tier natural speech',()=>{
 it('refuses unconfirmed configuration and private/oversized text before network',async()=>{const network=vi.fn();vi.stubGlobal('fetch',network);vi.stubEnv('ISNADLENS_GOOGLE_FREE_TIER_CONFIRMED','false');expect(cloudSpeechReady()).toBe(false);await expect(synthesizeSpeech({text:'An explanation.',language:'en',voice:'Achernar'})).rejects.toThrow('SPEECH_NOT_CONNECTED');expect(()=>validateSpeechInput({text:'Contact person@example.com',language:'en',voice:'Achernar'})).toThrow('SPEECH_PRIVATE_TEXT_REFUSED');expect(()=>validateSpeechInput({text:'a'.repeat(2401),language:'en',voice:'Achernar'})).toThrow('SPEECH_INPUT_INVALID');expect(network).not.toHaveBeenCalled();});
 it('preserves exact displayed text in the verbatim input and caches valid audio without another provider request',async()=>{const text='هذه قراءة مساعدة للنص المعروض.';let posted:any;const network=vi.fn(async(_url,options)=>{posted=JSON.parse(options.body);return new Response(JSON.stringify({steps:[{type:'model_output',content:[{type:'audio',mime_type:'audio/wav',data:wav().toString('base64')}]}]}),{status:200});});vi.stubGlobal('fetch',network);const first=await synthesizeSpeech({text,language:'ar',voice:'Sulafat'});const second=await synthesizeSpeech({text,language:'ar',voice:'Sulafat'});expect(posted.model).toBe(SPEECH_MODEL);expect(posted.input[0].content[0].text).toBe(text);expect(first.audio.equals(wav())).toBe(true);expect(first.cacheHit).toBe(false);expect(second.cacheHit).toBe(true);expect(network).toHaveBeenCalledOnce();expect(first.textHash).toBe(second.textHash);});
 it('retains failed requests in the quota and stops before a third request; no automatic retry',async()=>{const network=vi.fn(async()=>new Response('{}',{status:429}));vi.stubGlobal('fetch',network);const input={text:'A public explanation.',language:'en',voice:'Achernar'};await expect(synthesizeSpeech(input)).rejects.toThrow('SPEECH_PROVIDER_QUOTA_STOP');await expect(synthesizeSpeech(input)).rejects.toThrow('SPEECH_PROVIDER_QUOTA_STOP');await expect(synthesizeSpeech(input)).rejects.toThrow('SPEECH_FREE_QUOTA_STOP');expect(network).toHaveBeenCalledTimes(2);expect(JSON.parse(readFileSync(join(directory,'artifacts','private','speech','quota.json'),'utf8')).requests).toBe(2);});
 it('rejects text-only/provider malformed audio rather than pretending it generated speech',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({steps:[{type:'model_output',content:[{type:'text',text:'No audio'}]}]}),{status:200})));await expect(synthesizeSpeech({text:'A public explanation.',language:'en',voice:'Achernar'})).rejects.toThrow('SPEECH_AUDIO_INVALID');expect(()=>validateWav(Buffer.from('not audio'))).toThrow('SPEECH_AUDIO_INVALID');});
});
