import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {validateRecording,extractTranscript,transcribeRecording,MAX_RECORDING_BYTES,TRANSCRIPTION_MODEL} from '../src/lib/voice-input';
let directory:string;const audio=Buffer.concat([Buffer.from('RIFF'),Buffer.alloc(4),Buffer.from('WAVE'),Buffer.alloc(32)]);
beforeEach(()=>{directory=mkdtempSync(join(tmpdir(),'isnadlens-dictation-'));vi.spyOn(process,'cwd').mockReturnValue(directory);vi.stubEnv('GEMINI_API_KEY','test-key');vi.stubEnv('ISNADLENS_GOOGLE_FREE_TIER_CONFIRMED','true');});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals();vi.unstubAllEnvs();rmSync(directory,{recursive:true,force:true});});
describe('reviewable voice dictation',()=>{
 it('rejects oversized, wrong-signature, unsupported language and non-audio input before provider use',async()=>{const network=vi.fn();vi.stubGlobal('fetch',network);expect(()=>validateRecording(Buffer.alloc(MAX_RECORDING_BYTES+1),'audio/wav','auto')).toThrow('RECORDING_INVALID');expect(()=>validateRecording(audio,'text/plain','en')).toThrow('FORMAT_UNSUPPORTED');expect(()=>validateRecording(Buffer.from('not audio'),'audio/mp4','en')).toThrow('FORMAT_UNSUPPORTED');await expect(transcribeRecording(audio,'audio/wav','xx' as any)).rejects.toThrow('RECORDING_INVALID');expect(network).not.toHaveBeenCalled();});
 it('preserves original script and wording, never returns an answer or verification result',async()=>{const transcript='کیا اسلام میں جوا حرام ہے؟';let posted:any;vi.stubGlobal('fetch',vi.fn(async(_url,options)=>{posted=JSON.parse(options.body);return new Response(JSON.stringify({status:'completed',steps:[{type:'model_output',content:[{type:'text',text:transcript}]}]}));}));const result=await transcribeRecording(audio,'audio/wav','auto');expect(result).toEqual({transcript,model:TRANSCRIPTION_MODEL});expect(posted.store).toBe(false);expect(posted.input[0].data).toBe(audio.toString('base64'));expect(posted.generation_config.transcription_config.language_codes).toEqual([]);expect(posted.generation_config.transcription_config.mode).toEqual({type:'verbatim'});});
 it('maps all nine manual languages to supported locales without changing the transcript',()=>{for(const language of ['ar','en','bn','hi','ur','id','es','fr','de'])expect(validateRecording(audio,'audio/wav',language)).toBe('audio/wav');});
 it('refuses empty and overlong transcripts rather than silently truncating or inventing speech',()=>{expect(()=>extractTranscript({output_text:''})).toThrow('NO_SPEECH_DETECTED');expect(()=>extractTranscript({output_text:'x'.repeat(1201)})).toThrow('TRANSCRIPT_TOO_LONG');expect(()=>extractTranscript({status:'failed',output_text:'fabricated'})).toThrow('UNAVAILABLE');});
 it('refuses an unconfirmed project and does not retry quota failures',async()=>{const network=vi.fn(async()=>new Response('{}',{status:429}));vi.stubGlobal('fetch',network);vi.stubEnv('ISNADLENS_GOOGLE_FREE_TIER_CONFIRMED','false');await expect(transcribeRecording(audio,'audio/wav')).rejects.toThrow('NOT_CONNECTED');expect(network).not.toHaveBeenCalled();vi.stubEnv('ISNADLENS_GOOGLE_FREE_TIER_CONFIRMED','true');await expect(transcribeRecording(audio,'audio/wav')).rejects.toThrow('PROVIDER_QUOTA_STOP');expect(network).toHaveBeenCalledOnce();});
});
