import {DocumentationPage} from '../components/DocumentationPage';
function Content({ar}:{ar:boolean}){
 const t=(a:string,e:string)=>ar?a:e;
 const sections=[
  ['سؤال الإنسان أولًا','Start with the human question','يحافظ التطبيق على السؤال الأصلي. يمكن اقتراح توضيح قريب عند الغموض، مع تأكيد المستخدم أو تعديل السؤال؛ ولا يُحوَّل طلب غير متعلق بالمجال إلى ادعاء ديني مصطنع.','The app preserves the original question. Ambiguous wording can receive a closely related clarification for the user to confirm or edit. An unrelated request is not rewritten into an invented religious claim.'],
  ['مصدر يمكن تتبّعه','Retrieve traceable sources','يبحث التطبيق في نصوص القرآن والحديث المقبولة. وعند الحاجة يمكن اكتشاف مراجع عبر QuranEnc وHadeethEnc وAl-Ifta، ثم التحقق من النصوص المقبولة؛ رابط الويب وحده لا يصبح دليلًا موثّقًا.','The app searches admitted Quran and Hadith texts. When needed, bounded discovery can find references through QuranEnc, HadeethEnc and Al-Ifta for checking against admitted texts. A web link alone does not become verified evidence.'],
  ['سلامة الاقتباس منفصلة عن صحة الاستدلال','Check quotation integrity separately from meaning','تُفحص مطابقة الاقتباس بالنص المحفوظ وإصداره وموضعه وبصمته. ثم يُراجع مدى صلة الدليل بالسؤال، مع السياق والقيود والاستثناءات. صحة الاقتباس وحدها لا تثبت صحة النتيجة.','Quotation checks compare the text, edition, location and fingerprint with the stored source. A separate review examines relevance, context, qualifications and exceptions. A matching quotation alone does not establish a correct conclusion.'],
  ['جواب ودليل وحدود في مساحة واحدة','Show the answer, evidence and limits together','تعرض مساحة التحقق التفسير ونص المصدر وإحالته وحالة المراجعة. تُقدَّم الأدلة التي اعتمد عليها الجواب عند إمكان تحديدها. إذا لم يكتمل التقييم أو لم تكف الأدلة، يظل ذلك واضحًا؛ وعدم العثور على دليل ليس إثباتًا لخطأ الادعاء.','The workspace shows the explanation, source text, citation and review status together. Answer-linked evidence is prioritized when identifiable. Incomplete assessment or insufficient evidence remains explicit; failing to retrieve evidence does not prove a claim false.'],
  ['النص المنشور والتفسير الآلي','Distinguish publisher text from AI explanation','تُعرض درجة الحديث وتخريجه وشرحه بوصفها بيانات الناشر، لا حكمًا مستقلًا من النموذج. وتظهر ترجمة المعاني المنشورة منفصلة عن التفسير الآلي. تختلف تغطية الترجمات بين اللغات.','Hadith grades, attribution and commentary are publisher metadata, not independent authentication by the model. Published translations of meanings are distinguished from AI explanations. Translation coverage varies by language.'],
  ['حدود لا تخفيها الواجهة','Keep limitations visible','القرآن أصل الاستدلال والسنة تشرح وتبيّن وتخصص. لا يصدر التطبيق فتوى شخصية، ولا يدّعي إجماعًا أو اعتمادًا علميًا. مسائل الاجتهاد والخلاف تحتاج إلى أهل الاختصاص. نتائج الاختبارات المنشورة عيّنات تطوير، وليست ضمانًا عامًا للصحة.','The Quran is foundational and the Sunnah explains and qualifies meaning. The app does not issue personal fatwas or claim consensus or scholarly endorsement. Interpretive disputes need qualified review. Published tests are development samples, not a general accuracy guarantee.'],
 ];
 return <><p className="eyebrow">{t('منهج التحقق · محدّث في ٦ أكتوبر ٢٠٢٦','How it works · Updated 6 October 2026')}</p><h1>{t('من السؤال إلى دليل يمكن تتبّعه.','From a question to traceable evidence.')}</h1><p className="hero-intro">{t('بنيت عدسة الإسناد لمساعدتي على فحص ما أقرؤه وأسمعه بالرجوع إلى القرآن والحديث. يفحص التطبيق فهم الإنسان وادعاءه، ولا يحاكم صدق القرآن.','I built IsnadLens to help examine what I read and hear against Quran and Hadith evidence. It checks human claims and interpretations; it does not assess the truth of the Quran.')}</p><p className="documentation-note">{t('مشروع فردي من إعداد رضوان الرحمن، بمساعدة أدوات الذكاء الاصطناعي في التطوير والاختبار. لا يمثّل اعتمادًا من جهة علمية.','An individual project by Redwanur Rahman, developed and tested with AI assistance. It does not represent scholarly endorsement.')}</p>{sections.map(([a,e,ap,ep],i)=><section key={e}><h2>{i+1}. {t(a,e)}</h2><p>{t(ap,ep)}</p></section>)}<section><h2>{t('اختبار موثّق وتحسين مستمر','Documented testing and improvement')}</h2><p>{t('يتضمن سجل التطوير ٤٢٥ سؤالًا مختلف النص عبر ١٢ مجموعة تقييم رئيسية. حققت آخر مجموعة كاملة ٢٩ من ٣٠، مع توضيح الإجابة المقيّدة وحدود التقييم. اختبارات البرمجيات دون اتصال تُعرض منفصلة عن الأسئلة الحية.','The development record covers 425 distinct question texts across 12 major evaluation sets. The latest complete batch achieved 29/30, with its qualified answer and evaluation limits explained. Offline software checks are reported separately from live questions.')}</p><div className="source-links"><a href="/evaluation/latest">{t('النتائج وملاحظات التقييم','Results and evaluation notes')} ↗</a><a href="/sources">{t('المصادر وحقوق الاستخدام','Sources and attribution')} ↗</a></div></section><a className="primary-button" href="/">{t('العودة إلى مساحة التحقق','Return to verification')} ↗</a></>;
}
export default function MethodPage(){return <DocumentationPage arabic={<Content ar/>} english={<Content ar={false}/>}/>;}
