'use client';
import {useEffect,useRef,useState} from 'react';
import type {ClaimLanguage} from '@/lib/claim-language';
import type {ImageReading} from '@/lib/image-input';
import {imageCopy,imageQuotaCopy} from '@/lib/image-copy';
export function ImageInput({language,disabled,onText}:{language:ClaimLanguage;disabled:boolean;onText:(text:string)=>void}){
 const t=imageCopy(language);const [ready,setReady]=useState<boolean|null>(null);const [file,setFile]=useState<File|null>(null);const [url,setUrl]=useState('');const [reading,setReading]=useState<ImageReading|null>(null);const [draft,setDraft]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const epoch=useRef(0);const controller=useRef<AbortController|null>(null);const picker=useRef<HTMLInputElement|null>(null);
 function discard(clearPicker=true){epoch.current++;controller.current?.abort();setFile(null);setReading(null);setDraft('');setBusy(false);setError('');if(clearPicker&&picker.current)picker.current.value='';}
 function select(value:File|undefined){if(disabled||busy||!value)return;discard(false);if(!['image/png','image/jpeg','image/webp'].includes(value.type)||!value.size||value.size>10_000_000){setError(t[7]);return;}setFile(value);}
 useEffect(()=>{const c=new AbortController();fetch('/api/image-input',{signal:c.signal}).then(r=>r.json()).then(data=>setReady(Boolean(data.available))).catch(()=>{if(!c.signal.aborted)setReady(false);});return()=>c.abort();},[]);
 useEffect(()=>{if(!file){setUrl('');return;}const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u);},[file]);
 useEffect(()=>{if(disabled)discard();},[disabled]);
 useEffect(()=>()=>{epoch.current++;controller.current?.abort();},[]);
 async function read(){if(!file||busy||disabled)return;const generation=epoch.current;const c=new AbortController();controller.current=c;setBusy(true);setError('');setReading(null);setDraft('');
  try{const response=await fetch('/api/image-input',{method:'POST',headers:{'Content-Type':file.type},body:file,signal:c.signal});const data=await response.json();if(response.status===429)throw new Error('quota');if(!response.ok||!['read','unclear','no_text'].includes(data.status)||typeof data.transcript!=='string'||!Array.isArray(data.claims))throw new Error('failed');if(generation===epoch.current){setReading(data);setDraft(data.claims[0]??(data.transcript.length<=1200?data.transcript:''));}}
  catch(error){if(!c.signal.aborted&&generation===epoch.current)setError(error instanceof Error&&error.message==='quota'?imageQuotaCopy[language]:t[7]);}finally{if(generation===epoch.current)setBusy(false);}
 }
 return <section id="image-input" className="image-input" aria-label={t[0]} onPaste={event=>{const image=Array.from(event.clipboardData.files).find(f=>f.type.startsWith('image/'));if(image){event.preventDefault();select(image);}}} style={{marginBlock:'1rem',maxWidth:'100%'}}><h3>{t[0]}</h3><p className="context-note">{t[9]}</p>{ready===false?<p role="status">{t[13]}</p>:<><label style={{display:'block'}}>{t[1]}<input ref={picker} type="file" accept="image/png,image/jpeg,image/webp" disabled={!ready||disabled||busy} onChange={e=>select(e.target.files?.[0])} style={{display:'block',maxWidth:'100%'}}/></label>{file&&<><img src={url} alt={t[8]} style={{display:'block',maxWidth:'100%',maxHeight:360,objectFit:'contain',marginBlock:8}}/><button type="button" disabled={busy||disabled} onClick={()=>void read()}>{busy?t[3]:t[2]}</button><button type="button" onClick={()=>discard()}>{t[6]}</button></>}{reading&&<><p className="context-note">{t[10]}</p>{reading.status!=='read'&&<p role="status">{reading.status==='unclear'?t[14]:t[15]}</p>}{reading.transcript&&<details><summary>{t[12]}</summary><p dir="auto" style={{whiteSpace:'pre-wrap'}}>{reading.transcript}</p></details>}{reading.claims.length>1&&<label style={{display:'block'}}>{t[11]}<select aria-label={t[11]} onChange={e=>setDraft(reading.claims[Number(e.target.value)])} defaultValue="0" style={{display:'block',maxWidth:'100%'}}>{reading.claims.map((claim,index)=><option key={index} value={index}>{claim.slice(0,90)}</option>)}</select></label>}<label style={{display:'block'}}>{t[4]}<textarea aria-label={t[4]} value={draft} maxLength={1200} dir="auto" onChange={e=>setDraft(e.target.value)} style={{width:'100%',minHeight:100}}/></label><button type="button" disabled={disabled||!draft.trim()} onClick={()=>{onText(draft);discard();document.querySelector<HTMLTextAreaElement>('#claim')?.focus();}}>{t[5]}</button></>}</>}{error&&<p role="alert">{error}</p>}</section>;
}
