'use client';
import {useEffect,useRef,useState} from 'react';
import type {ClaimInputSelection,ClaimLanguage} from '@/lib/claim-language';
const words:Record<ClaimLanguage,string[]>={
 en:['Voice input','Record','Stop','Transcribe','Use this text','Discard','Review and edit before verification. Recording is limited to 45 seconds. Google receives audio only when you press Transcribe; its free service may use audio to improve its products. Avoid private information.','Microphone or recording is unavailable. You can still type.','Speech could not be transcribed. Try a shorter, clearer recording or type.','Transcribing…','Review the transcript','Recording…','Free voice input is unavailable. You can still type.'],
 ar:['إدخال صوتي','سجّل','إيقاف','تحويل إلى نص','استخدم النص','حذف التسجيل','راجع النص قبل التحقق. مدة التسجيل 45 ثانية كحد أقصى. يُرسل الصوت إلى Google فقط عند ضغط تحويل إلى نص، وقد تستخدمه الخدمة المجانية لتحسين منتجاتها. تجنب المعلومات الخاصة.','الميكروفون أو التسجيل غير متاح. يمكنك الكتابة.','تعذر تحويل الصوت إلى نص. جرّب تسجيلاً أقصر وأوضح أو اكتب.','جارٍ تحويل الصوت…','راجع النص','جارٍ التسجيل…','الإدخال الصوتي المجاني غير متاح. يمكنك الكتابة.'],
 bn:['ভয়েস ইনপুট','রেকর্ড','থামান','লিখিত পাঠে রূপান্তর','এই পাঠ ব্যবহার করুন','বাতিল','যাচাইয়ের আগে পাঠ পর্যালোচনা করুন। সর্বোচ্চ ৪৫ সেকেন্ড। রূপান্তর চাপলে অডিও Google-এ পাঠানো হবে; বিনামূল্যের পরিষেবা পণ্য উন্নয়নে তা ব্যবহার করতে পারে। ব্যক্তিগত তথ্য বলবেন না।','মাইক্রোফোন বা রেকর্ডিং নেই। লিখতে পারেন।','অডিও রূপান্তর করা যায়নি। সংক্ষিপ্ত ও স্পষ্টভাবে বলুন বা লিখুন।','রূপান্তর হচ্ছে…','পাঠ পর্যালোচনা করুন','রেকর্ড হচ্ছে…','বিনামূল্যের ভয়েস ইনপুট নেই। লিখতে পারেন।'],
 hi:['आवाज़ से लिखें','रिकॉर्ड','रोकें','लिखित पाठ बनाएँ','यह पाठ इस्तेमाल करें','हटाएँ','सत्यापन से पहले पाठ जाँचें। अधिकतम 45 सेकंड। लिखित पाठ बनाएँ दबाने पर ही ऑडियो Google को भेजा जाता है; निःशुल्क सेवा उत्पाद सुधार के लिए इसका उपयोग कर सकती है। निजी जानकारी न बोलें।','माइक्रोफ़ोन या रिकॉर्डिंग उपलब्ध नहीं। आप लिख सकते हैं।','आवाज़ समझ नहीं आई। छोटा और स्पष्ट रिकॉर्ड करें या लिखें।','पाठ बन रहा है…','पाठ जाँचें','रिकॉर्ड हो रहा है…','निःशुल्क आवाज़ सुविधा उपलब्ध नहीं। लिख सकते हैं।'],
 ur:['آواز سے لکھیں','ریکارڈ','روکیں','متن بنائیں','یہ متن استعمال کریں','حذف کریں','تصدیق سے پہلے متن دیکھیں۔ زیادہ سے زیادہ 45 سیکنڈ۔ متن بنائیں دبانے پر ہی آڈیو Google کو بھیجی جاتی ہے؛ مفت سروس اسے مصنوعات بہتر بنانے کے لیے استعمال کر سکتی ہے۔ نجی معلومات نہ دیں۔','مائیکروفون یا ریکارڈنگ دستیاب نہیں۔ لکھ سکتے ہیں۔','آواز کا متن نہیں بن سکا۔ مختصر اور واضح ریکارڈ کریں یا لکھیں۔','متن بن رہا ہے…','متن دیکھیں','ریکارڈ ہو رہا ہے…','مفت صوتی سہولت دستیاب نہیں۔ لکھ سکتے ہیں۔'],
 id:['Masukan suara','Rekam','Berhenti','Transkripsikan','Gunakan teks ini','Buang','Tinjau teks sebelum verifikasi. Maksimal 45 detik. Audio dikirim ke Google hanya saat menekan Transkripsikan; layanan gratis dapat memakainya untuk meningkatkan produk. Hindari informasi pribadi.','Mikrofon atau perekaman tidak tersedia. Anda masih bisa mengetik.','Audio tidak dapat ditranskripsikan. Rekam lebih singkat dan jelas atau ketik.','Mentranskripsikan…','Tinjau transkrip','Merekam…','Masukan suara gratis tidak tersedia. Anda masih bisa mengetik.'],
 es:['Entrada de voz','Grabar','Detener','Transcribir','Usar este texto','Descartar','Revisa el texto antes de verificar. Máximo 45 segundos. El audio se envía a Google solo al pulsar Transcribir; el servicio gratuito puede usarlo para mejorar sus productos. Evita información privada.','Micrófono o grabación no disponible. Puedes escribir.','No se pudo transcribir. Graba más breve y claro o escribe.','Transcribiendo…','Revisar transcripción','Grabando…','Entrada de voz gratuita no disponible. Puedes escribir.'],
 fr:['Saisie vocale','Enregistrer','Arrêter','Transcrire','Utiliser ce texte','Supprimer','Relisez avant vérification. Maximum 45 secondes. Google reçoit le son uniquement après Transcrire ; le service gratuit peut l’utiliser pour améliorer ses produits. Évitez les informations privées.','Microphone ou enregistrement indisponible. Vous pouvez écrire.','Transcription impossible. Enregistrez plus brièvement et clairement ou écrivez.','Transcription…','Relire la transcription','Enregistrement…','Saisie vocale gratuite indisponible. Vous pouvez écrire.'],
 de:['Spracheingabe','Aufnehmen','Stoppen','Transkribieren','Diesen Text verwenden','Verwerfen','Vor der Prüfung den Text kontrollieren. Höchstens 45 Sekunden. Audio wird erst bei Transkribieren an Google gesendet; der kostenlose Dienst kann es zur Produktverbesserung nutzen. Keine privaten Angaben.','Mikrofon oder Aufnahme nicht verfügbar. Sie können tippen.','Transkription fehlgeschlagen. Kürzer und deutlicher aufnehmen oder tippen.','Transkription…','Transkript prüfen','Aufnahme…','Kostenlose Spracheingabe nicht verfügbar. Sie können tippen.']};
export function VoiceInput({language,inputLanguage,disabled,onText}:{language:ClaimLanguage;inputLanguage:ClaimInputSelection;disabled:boolean;onText:(text:string)=>void}){
 const t=words[language];const [ready,setReady]=useState<boolean|null>(null);const [recording,setRecording]=useState(false);const [blob,setBlob]=useState<Blob|null>(null);const [url,setUrl]=useState('');const [transcript,setTranscript]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const recorder=useRef<MediaRecorder|null>(null);const stream=useRef<MediaStream|null>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const controller=useRef<AbortController|null>(null);const generation=useRef(0);const starting=useRef(false);
 function release(){if(timer.current)clearTimeout(timer.current);timer.current=null;stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;}
 function discard(){generation.current++;controller.current?.abort();if(recorder.current){recorder.current.onstop=null;if(recorder.current.state!=='inactive')recorder.current.stop();}release();starting.current=false;setRecording(false);setBusy(false);setBlob(null);setTranscript('');setError('');}
 useEffect(()=>{const c=new AbortController();fetch('/api/transcribe',{signal:c.signal}).then(r=>r.json()).then(data=>setReady(Boolean(data.available))).catch(()=>{if(!c.signal.aborted)setReady(false);});return()=>c.abort();},[]);
 useEffect(()=>{if(!blob){setUrl('');return;}const u=URL.createObjectURL(blob);setUrl(u);return()=>URL.revokeObjectURL(u);},[blob]);
 useEffect(()=>{if(disabled)discard();},[disabled]); // Prevent a recording competing with an active verification.
 useEffect(()=>()=>{generation.current++;controller.current?.abort();if(recorder.current){recorder.current.onstop=null;if(recorder.current.state!=='inactive')recorder.current.stop();}release();},[]);
 async function start(){
  if(starting.current||recording||busy||disabled)return;discard();starting.current=true;const epoch=generation.current;
  try{
   if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined')throw new Error('unsupported');
   const media=await navigator.mediaDevices.getUserMedia({audio:true});if(epoch!==generation.current){media.getTracks().forEach(track=>track.stop());return;}stream.current=media;
   const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(type=>MediaRecorder.isTypeSupported(type));if(!mime)throw new Error('unsupported');
   const r=new MediaRecorder(media,{mimeType:mime,audioBitsPerSecond:32000});recorder.current=r;const chunks:Blob[]=[];let size=0;
   r.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);size+=e.data.size;if(size>1_000_000&&r.state!=='inactive')r.stop();}};
   r.onerror=()=>{discard();setError(t[7]);};r.onstop=()=>{release();setRecording(false);if(epoch!==generation.current)return;const audio=new Blob(chunks,{type:r.mimeType});if(!audio.size||audio.size>1_000_000)setError(t[8]);else setBlob(audio);};
   r.start(1000);setRecording(true);timer.current=setTimeout(()=>{if(r.state!=='inactive')r.stop();},45000);
  }catch{release();setError(t[7]);}finally{starting.current=false;}
 }
 async function transcribe(){if(!blob||busy)return;setBusy(true);setError('');const c=new AbortController();controller.current=c;const epoch=generation.current;
  try{const response=await fetch('/api/transcribe',{method:'POST',headers:{'Content-Type':blob.type,'x-claim-language':inputLanguage},body:blob,signal:c.signal});const data=await response.json();if(!response.ok||typeof data.transcript!=='string'||!data.transcript.trim()||data.transcript.length>1200)throw new Error('failed');if(epoch===generation.current)setTranscript(data.transcript);}
  catch{if(!c.signal.aborted&&epoch===generation.current)setError(t[8]);}finally{if(epoch===generation.current)setBusy(false);}
 }
 return <section style={{marginBlock:'1rem',maxWidth:'100%'}} aria-label={t[0]}><h3>{t[0]}</h3><p className="context-note">{t[6]}</p>{ready===false?<p role="status">{t[12]}</p>:<><button type="button" disabled={!ready||disabled||busy} onClick={()=>recording?recorder.current?.stop():void start()}>{recording?t[2]:t[1]}</button>{recording&&<span role="status"> {t[11]}</span>}{blob&&<><audio controls src={url||undefined} style={{display:'block',width:'100%',marginBlock:8}}/><button type="button" disabled={busy||disabled} onClick={()=>void transcribe()}>{busy?t[9]:t[3]}</button></>}{(blob||recording||busy)&&<button type="button" onClick={discard}>{t[5]}</button>}{transcript&&<><label style={{display:'block'}}>{t[10]}<textarea value={transcript} onChange={e=>setTranscript(e.target.value)} maxLength={1200} dir="auto" style={{minHeight:100,width:'100%'}}/></label><button type="button" disabled={disabled||!transcript.trim()} onClick={()=>{onText(transcript);discard();}}>{t[4]}</button></>}</>}{error&&<p role="alert">{error}</p>}</section>;
}
