import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {loadHadith} from '@/lib/hadith';
import {getQuranTranslationAdmission} from '@/lib/quran-translations';
import {DocumentationPage} from '../components/DocumentationPage';
export default function SourcesPage(){
 let translations:ReturnType<typeof getQuranTranslationAdmission>|null=null;
 try{translations=getQuranTranslationAdmission();}catch{}
 const notice=readFileSync(join(process.cwd(),'data/TANZIL-NOTICE.txt'),'utf8');
 let version:string|null=null;
 let hadithSources:{language:string;version:string;notice:string;raw_sha256:string}[]=[];
 try{const data=loadHadith();version=data.manifest.version;hadithSources=data.manifest.sources;}catch{}
 function content(ar:boolean){
  const t=(a:string,e:string)=>ar?a:e;
  return <><p className="eyebrow">{t('المصدر والإصدار وحقوق الاستخدام','Sources, editions and attribution')}</p><h1>{t('النص يبقى كما نشره مصدره.','Source text stays as published.')}</h1><p className="hero-intro">{t('الاقتباس الأصلي والترجمة المنشورة والتفسير الآلي موارد مختلفة، وتظهر هويتها بوضوح. التغطية الحالية المقبولة متاحة في مساحة التحقق.','Original quotations, published translations and AI explanations are distinct resources, clearly identified. Current admitted coverage is available in the verification workspace.')}</p>
  <section><h2>{t('القرآن الكريم','Quran')} · Tanzil Project</h2><p>{t('إصدار Uthmani 1.1 لعرض النص، وإصدار Simple Clean 1.1 للبحث المطابق. حُفظ النص في كل إصدار دون تغيير، ورُبط الإصداران بموضع السورة والآية فقط.','Uthmani 1.1 provides display text; Simple Clean 1.1 supports matching and search. Each edition is preserved unchanged and linked only by surah and ayah.')}</p><div className="source-links"><a href="https://tanzil.net" target="_blank" rel="noopener noreferrer">Tanzil ↗</a><a href="https://tanzil.net/docs/Text_License" target="_blank" rel="noopener noreferrer">{t('شروط استخدام النص','Text licence')} ↗</a></div><h3>{t('إشعار الناشر الأصلي','Original publisher notice')}</h3><pre dir="ltr" lang="en">{notice}</pre></section>
  <section><h2>{t('الأحاديث','Hadith')} · HadeethEnc</h2><p>{t('نص الحديث وحكم الناشر والتخريج والشرح والفوائد حقول مصدرية محفوظة دون تغيير. حكم الناشر ليس تصحيحًا مستقلًا من عدسة الإسناد.','Hadith text, publisher grade, attribution, commentary and benefits are preserved source fields. Publisher grading is not independent authentication by IsnadLens.')}</p><p>{t('إصدار المجموعة المقبولة:','Admitted collection version:')} <bdi>{version??t('غير متاح حاليًا','currently unavailable')}</bdi></p><p>{t('تختلف أعداد الترجمات بين اللغات التسع؛ لا يعني توفر اللغة أن كل حديث مترجم إليها.','Translation counts vary across the nine languages; an available language does not mean every hadith has a translation.')}</p><div className="source-links"><a href="https://hadeethenc.com/en/home" target="_blank" rel="noopener noreferrer">HadeethEnc · {t('المصدر وسياسات الناشر','Source and publisher policies')} ↗</a></div>{hadithSources.map(source=><details className="publisher-source-notice" key={source.language}><summary><bdi>{source.language} · {source.version}</bdi> — {t('إشعار الناشر الأصلي','Original publisher notice')}</summary><pre dir={['ar','ur'].includes(source.language)?'rtl':'ltr'} lang={source.language}>{source.notice}</pre><code dir="ltr">Workbook SHA-256: {source.raw_sha256}</code></details>)}</section>
  {translations&&<section><h2>{t('ترجمات معاني القرآن','Quran translations of meanings')} · QuranEnc</h2><p>{t('تظهر الترجمات المنشورة إلى جانب الأصل العربي الثابت، ولا تستبدل الدليل المحفوظ ولا تعيد تقييم السؤال استقلالًا. تُحفظ حواشي الناشر وبياناته وإصداراته.','Published translations accompany the unchanged Arabic original. They do not replace sealed evidence or independently reassess a question. Publisher footnotes, metadata and editions are preserved.')}</p><a href={translations.terms_url} target="_blank" rel="noopener noreferrer">{t('شروط الناشر','Publisher terms')} ↗</a>{translations.sources.map(source=><p key={source.language} dir="ltr"><bdi>{source.language} · {source.key} · {source.version} · {source.record_count}</bdi></p>)}<details><summary>{t('إشعار الناشر الأصلي','Original publisher notice')}</summary><pre dir="ltr">{translations.notice}</pre></details><p>{t('تتوفر الترجمة القرآنية البنغالية برابط الناشر المباشر، بينما توثيق إصدارها المطلوب في المجموعة لم يكتمل بعد. هذا قيد إدراج مصدر، وليس حكمًا على اللغة. إصدارات الحديث البنغالية مقبولة على نحو منفصل.','The Bengali Quran translation is available through a direct publisher link while its required collection-edition verification remains incomplete. This is a source-admission limitation, not a judgment on the language. Bengali Hadith editions are admitted separately.')}</p><a href="https://quranenc.com/en/browse/bengali_zakaria" target="_blank" rel="noopener noreferrer">বাংলা · QuranEnc ↗</a></section>}
  <section><h2>{t('التلاوة المسجلة','Recorded recitation')}</h2><p>{t('تُبث تلاوة الآية الكاملة بصوت مشاري راشد العفاسي مباشرة من EveryAyah. ليست مولّدة بالذكاء الاصطناعي ولا يعيد التطبيق استضافتها. الحقوق لأصحابها. يُربط التسجيل بالنص عبر رقم السورة والآية؛ التسجيل والاقتباس موردان منفصلان.','Full-verse recitation by Mishary Rashid Alafasy streams directly from EveryAyah. It is not AI generated or rehosted by IsnadLens. Rights remain with their holders. Audio and quoted text are distinct resources linked by surah and ayah.')}</p><a href="https://everyayah.com/" target="_blank" rel="noopener noreferrer">EveryAyah ↗</a></section><p>{t('هذه الصفحة توثّق المصادر وحقوق استخدامها؛ ولا تمنح اعتمادًا علميًا للتفسير الآلي.','This page documents sources and attribution; it does not confer scholarly endorsement on AI explanations.')}</p></>;
 }
 return <DocumentationPage arabic={content(true)} english={content(false)}/>;
}
