import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { loadHadith } from '@/lib/hadith';
export default function SourcesPage() {
  const notice = readFileSync(join(process.cwd(), 'data/TANZIL-NOTICE.txt'),'utf8');
  let hadithVersion:string|null=null;
  let hadithSources:{language:string;version:string;notice:string;raw_sha256:string}[]=[];
  try { const data=loadHadith(); hadithVersion=data.manifest.version; hadithSources=data.manifest.sources; } catch { /* Unvalidated source notices are not promoted to admitted status. */ }
  return <div className="site-shell method-page" dir="rtl"><header className="topbar"><a className="brand" href="/">عدسة الإسناد · IsnadLens</a><a href="/">العودة إلى مساحة الفحص ↗</a></header><main className="method-content"><p className="eyebrow">المصدر والإصدار وحقوق الاستخدام</p><h1>النص يبقى كما نشره مصدره.</h1><section><h2>القرآن الكريم · Tanzil Project</h2><p>المصدر: <a href="https://tanzil.net" target="_blank" rel="noopener noreferrer">Tanzil Project</a>. إصدار Uthmani 1.1 لعرض النص، وإصدار Simple Clean 1.1 للبحث المطابق. حُفظ النص في كل إصدار دون تغيير، وربطناهما بموضع السورة والآية فقط.</p><p lang="en" dir="ltr">Arabic source quotations are unchanged publisher text. English interface explanations are project-authored and are not authoritative Quran translations.</p><p><a href="https://tanzil.net/docs/Text_License" target="_blank" rel="noopener noreferrer">Tanzil text licence / شروط استخدام النص ↗</a></p><h3>إشعار الناشر الأصلي · Original publisher notices</h3><pre dir="ltr" style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',fontSize:'14px',lineHeight:1.7}}>{notice}</pre></section><section><h2>الأحاديث · HadeethEnc</h2><p>المصدر: <a href="https://hadeethenc.com" target="_blank" rel="noopener noreferrer">موسوعة الأحاديث النبوية · HadeethEnc</a>. اقتباسات الحديث، وحكم الناشر، والتخريج، والشرح، والفوائد تُعرض كحقول مصدرية محفوظة دون تغيير. لا ننسب حكم الناشر إلى النموذج، ولا ندّعي تصحيحاً مستقلاً.</p><p>إصدار المجموعة المحفوظة: <bdi>{hadithVersion??'يظهر بعد قبول المجموعة في تغطية المصادر'}</bdi>. بيانات الإصدار وبصمة كل اقتباس تظهر في سجل الفحص. قد تختلف أعداد الترجمات بين العربية والإنجليزية والبنغالية والهندية والأردية والإندونيسية؛ لا نفترض أن كل سجل متاح بكل لغة.</p><p><a href="https://hadeethenc.com/en/home" target="_blank" rel="noopener noreferrer">شروط وسياسات الناشر · Publisher terms and policies ↗</a></p>{hadithSources.map(source=><details className="publisher-source-notice" key={source.language}><summary><bdi>{source.language} · {source.version}</bdi> — إشعار الناشر الأصلي</summary><pre dir={['ar','ur'].includes(source.language)?'rtl':'ltr'} lang={source.language} style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',fontSize:'13px',lineHeight:1.9}}>{source.notice}</pre><code dir="ltr">Workbook SHA-256: {source.raw_sha256}</code></details>)}<p lang="en" dir="ltr">Source: HadeethEnc. Publisher text and metadata are preserved unchanged. Publisher grades are not independent grading by IsnadLens. Source translations and AI explanations are displayed distinctly; coverage varies by language.</p></section><p>تُعرض التغطية الفعلية المقبولة في مساحة الفحص. هذه الصفحة لا تمنح مراجعة شرعية للتفسير الناتج عن النموذج. لا تشمل المصادر الحالية ترجمات القرآن أو نصوص دليل الحج والعمرة.</p></main></div>;
}

