import {readFile,writeFile} from 'node:fs/promises';
import {applicationTreeHash} from './holdout-protocol.mjs';
const run=JSON.parse(await readFile('artifacts/pilot5-first-pass-2026-10-05.json','utf8'));
const audit=JSON.parse(await readFile('artifacts/pilot5-mechanical-audit-2026-10-05.json','utf8'));
if(await applicationTreeHash()!==run.freeze.application_tree_sha256)throw Error('APPLICATION_CHANGED');
// Principal source/prose review after inspecting the two complete responses.
const notes={P1:'2:280 supports respite for a debtor in hardship until ease; English/Arabic preserve that condition, without compulsory forgiveness or an individual debt judgment.',P2:'6:59 explicitly includes falling leaves in Allah’s knowledge; English/Arabic preserve the statement without adding separate doctrinal conclusions.',P3:'Operational stop. Correct ridicule passage 49:11 was retrieved, but SPEND_BUDGET_STOP prevented a complete assessment/review. Not a wrong religious answer and not a satisfactory answer.'};
const cases=run.cases.map(c=>({id:c.id,completed_answer:c.id!=='P3',satisfactory:c.id!=='P3',note:notes[c.id],source_bytes_and_nested_seals_passed:audit.cases.find(a=>a.id===c.id).source_bytes_and_nested_seals_passed}));
if(cases.length!==3||cases.some(c=>!c.note||!c.source_bytes_and_nested_seals_passed)||run.operational_stop!=='P3'||run.pilot_commitment_sar>.75)throw Error('REVIEW_OR_BUDGET_FAILURE');
const report={kind:'incomplete_five_question_pilot_principal_review_not_accuracy_certification',created_at:new Date().toISOString(),planned:5,attempted:3,completed_answers:2,satisfactory_completed_answers:2,untested:['P4','P5'],operational_stop:'P3',reason:'SPEND_BUDGET_STOP',full_pilot_gate_passed:false,benchmark_score:null,source_and_seal_checks_passed:audit.source_and_seal_checks_passed,pilot_commitment_sar:run.pilot_commitment_sar,maximum_pilot_sar:.75,final_development_sar:run.final_development_sar,development_cap_sar:39,limits:['Two completed answers cannot establish five-question success, a 90% release target, general accuracy or native-language certification.','Budget reservation uses a conservative UTF-8-byte input-token upper bound plus maximum output; it can stop calls even when settled cost is below the pilot cap.','No retry, production edit or larger run after the pilot budget guard. Original frozen benchmarks unchanged.'],cases};
await writeFile('artifacts/pilot5-principal-review-2026-10-05.json',JSON.stringify(report,null,2),{flag:'wx'});console.log(JSON.stringify({...report,cases:undefined,limits:undefined}));
